### ISSUE TITLE
core package listing won't show 50 more

### ISSUE THREAD

**Issue by Maniacal** [habitat-sh/habitat#1053]
https://app.habitat.sh/#/pkgs/core

At the bottom you can click to show 50 more

![image](https://cloud.githubusercontent.com/assets/957718/16745272/b102e9c2-477a-11e6-9076-cd8724fe7c51.png)

but when you do you just get the same 50 again

![image](https://cloud.githubusercontent.com/assets/957718/16745279/bf1a59aa-477a-11e6-9e14-0961f4f49e47.png)

**Comment by metadave** [comment]
confirmed, same results for me

**Comment by metadave** [comment]
associated code:  https://github.com/habitat-sh/habitat/blob/master/components/depot/src/server.rs#L955-L977

After clicking `Load 50 more`:
![habitat_-_automation_that_travels_with_the_app__and_slack](https://cloud.githubusercontent.com/assets/58244/16745450/e11084ea-4783-11e6-81ba-fa61ac539679.png)

**Comment by smith** [comment]
This is happening because it appears that Fastly is not receiving the `Range` header that is sent with the request, and it always starts the `X-Content-Range` (the `Content-Range` header that is supposed to be there is also being stripped by Fastly.)

I'd like to get a working acceptance environment, that lets us break our Fastly settings without bothering anybody, before taking more action on this.

**Comment by smith** [comment]
I changed the settings like Fastly recommended on our acceptance environment, and now we do get a `Content-Range` header in the response, but it still has the same behavior. I suspect that this is because they are stripping the `Range` header from the request. I emailed Fastly support and am awaiting a response.

**Comment by smith** [comment]
Got a reply from Fastly:

Stephen Basile (Fastly) Jul 26, 10:43 AM PDT

> HI Nathan,
>
> I apologize for the delay in replying. Varnish does strip the Range header when going to origin.
> Here's how you can preserve it:
>
>     sub vcl_recv {
>       set req.http.X-Range = req.http.Range;
>     }
>
>     sub vcl_pass {
>       if (req.http.X-Range) {
>         set bereq.http.Range = req.http.X-Range;
>         unset bereq.http.X-Range;
>       }
>     }
>
> You would of course use this code in combination with passing the requests in vcl_recv, which you confirmed is preserving Content-Range.
> 
> Stephen

Going to try this.

**Comment by smith** [comment]
Tried this (and some permutations of it) in acceptance and it wasn't working. Emailing Fastly back.

**Comment by smith** [comment]
We could make the client send `X-Range` in addition to `Range` and make the server handle that as well. That would fix the problem but would require us to make client and server-side changes.

**Comment by smith** [comment]
This has been fixed.
