### ISSUE TITLE
Documentation Add - How to run a private hab depot

### ISSUE THREAD

**Issue by bscott** [habitat-sh/habitat#1060]
Hello 

This is for me to add some documentation on running a private Habitat Depot. PR's welcome!

**Comment by metadave** [comment]
see also: https://github.com/habitat-sh/habitat/issues/1048

**Comment by bscott** [comment]
@metadave Awesome! thanks, that will give me good context on the documentation I'll write for the private repo, any suggestions where in the docs I should place it?

**Comment by metadave** [comment]
how about as a subheading under https://www.habitat.sh/docs/share-packages-overview/ ?

cc @davidwrede @juliandunn

**Comment by davidwrede** [comment]
@metadave, @bscott, yeah, it makes sense to have it as a subheading under the share-packages-overview topic. And thanks for taking a stab at this, @bscott!

**Comment by davidwrede** [comment]
Hey @bscott, I'm starting to rough out what some content for this might look like. If you're still interested in contributing to it, I'd love to sync up and talk about it.

**Comment by looprock** [comment]
Since I haven't seen any movement on this and finding documentation on this, imho, critical component, is incredibly difficult I thought I'd drop this FYI here. I found this in slack history today:

https://gist.github.com/jtimberman/f939e9c822c581bc7168026f3fa4211c

**Comment by eeyun** [comment]
This is complicated currently. Since the builder pieces are under rapid development the depot and it's packages are likely to change drastically in the short term which means the gist above might be out of date in short order. 

We could possibly get a PR open to the docs that includes @jtimberman 's walkthrough but we might also want to make sure community members know that the gist might not exactly be canon (yet).

If anyone is interested in opening that PR all of our docs are also open-sourced and can be found here: https://github.com/habitat-sh/habitat/tree/master/www/source/docs

@jtimberman do you have any feeling one way or the other about opening a PR to the docs with your walkthrough content?

**Comment by mattray** [comment]
@bdangit shared this with me, looks promising and I'm sure he'd appreciate the help keeping it up to date
https://github.com/bdangit/chef-depot

**Comment by bdangit** [comment]
Thanks @mattray 

Yes. PRs greatly appreciated.

Btw all the recipes are built off @jtimberman's gist.  So if you are lazy like me then when we can keep committing code back to depot cookbook.  :smile:

**Comment by jtimberman** [comment]
@eeyun We should definitely get something documented in the Habitat docs, rather than a hard-to-find gist. I don't have cycles for doing that, though.

**Comment by eeyun** [comment]
I'll try and look into this asap.

**Comment by davidwrede** [comment]
@eeyun I'll be free in a day or two to help out getting this content into the docs.

**Comment by meringu** [comment]
+1

**Comment by tashimi** [comment]
Hey there - 

Please check out our Builder Depot docker container for more info on this: https://github.com/habitat-sh/habitat/blob/master/BUILDER_CONTAINER.md

**Comment by luisdavim** [comment]
Still nothing?

**Comment by tashimi** [comment]
You can follow these milestones to see the status of work for automating on-prem: 
https://github.com/habitat-sh/builder/milestones
