### ISSUE TITLE
Helper command to run do_check after the build is complete

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#1170]
Occasionally, I intend to `export DO_CHECK=true` before a build but then forget, or make a typo, or fall victim to some other common calamity caused by the human condition.  When iterating on a plan that takes a very long time to build, the realization that you are going to need to start the build again can be heartbreaking.  If you regain your presence of mind quickly enough, you might save yourself some time by overriding `do_clean()` and `do_unpack()`, but for some software definitions that is also very hard as you may also have to comment out calls to `patch` or `sed` that aren't idempotent.

I'd like to be able to run the `do_check()` function of my plan, in the context it would be run had I remembered to set DO_CHECK=true, after the build has been completed.  Maybe it would look like this:

```
record gcc build /src/gcc
# realize your mistake
# but don't cry, because the studio has your back:
check /src/gcc
```

This might not work for all plans since the `install` steps may be destructive in some way.  However, I think it would probably work for most plans in `core-plans`.

**Comment by miketheman** [comment]
I like! Would this run something that is effectively overriding most of the callbacks?

Would it make sense to have some top-level in-studio commands that do only this, like `install` too?

**Comment by smurawski** [comment]
I'd love to see if, in the studio, we could arbitrarily run some or all build phases, like

```
build myproject --check
```

This would let you iterate on a particular step or do the thing you forgot.

**Comment by fnichol** [comment]
I can see the value here--especially if the `do_build()` is expensive. I'm wondering how far a small `plan.sh` hack like this could go:

```sh
do_download() {
  # call do_check(), and exit fast, haha
  do_check
  build_line "Early exiting"
  exit 0
}
```

**Comment by rsertelon** [comment]
Another way of seeing this could be: Should we enable checks by default?

If the `do_check()` default implementation does nothing, it might be best to always run `do_check()`. If it is implemented, it means that the plan owner created tests to make sure the built target is OK and I would think that if a test fails, the build would fail too.

This way, the problem here would become 'How can I not run check when building a package' ;) And the `DO_CHECK=false` might help then.

I understand this is a non backward compatible change, but I really feel it is worth it.

**Comment by stevendanna** [comment]
This is still an issue, but we can close this out if y'all would like.  I think increasingly we are moving away from do_check in favor of tests that live outside the plan.
