### ISSUE TITLE
Allow execution of dependent plan hook

### ISSUE THREAD

**Issue by russellseymour** [habitat-sh/habitat#1346]
When developing a new Habitat plan that has dependencies on other plans it is sometimes necessary to be able to call the dependent plan `init` and / or `run` hook.

For example I have been working on a plan that will run the Jenkins WAR in Tomcat.  My plan had `core/tomcat8` as a dependency.  The Tomcat8 plan has hooks for the `run` and `init` commands.

For the Jenkins plan I am downloading the WAR file and putting in the `webapps` directory.  However I do not have a `run` hook as I want to be able to use the Tomcat one as I do not need any changes.

This is probably a recurrent issue for situations where a deployment of a package into a container engine occurs, e.g. Tomcat, JBoss etc.

I have a few ideas for workarounds but they feel like `hacks`.  Thinking of something like `hook_for()` for the supervisor to call a different hook if required.

/cc @fnichol

**Comment by bdangit** [comment]
A while ago in habi-slack, we discussed how to layer packages where `myapp` > `tomcat` > `jdk8`.  `myapp` and `jdk8` are just the application binaries, but in order to run them you need to start `tomcat`.

The thought of executing the hook that is defined in `tomcat` seemed very natural, but then when you actually try to do that you'll want to some how want to templatize the hooks inside tomcat and then you just start going down a weird dependency hell.

The simplest and most sane thing to do is just to copy the `tomcat` stuff into your `$pkg_svc_path` during runtime.  And then your `hooks` will run naturally from your `myapp` context.  You have more control and flexibility.  I would rather trust that people who put packages up built the app correctly, but during runtime, I need to customize my start processes the way I want it in a safe manner that suits me.  That customization can only be determined by me not any of my dependencies.

Please note, tech stacks that operate like tomcat where tomcat expects things in a certain folder location is not 12 factor friendly.  We should break free from these configuration type styles and go for more binary + configuration, where configuration inputs can be set when you start the binary from any location (ie. myapp -c myconfig.yaml)

**Comment by eeyun** [comment]
@russellseymour thank you for opening up this discussion!

This is something we've talked about internally quite a bit and it feels to me like it might not be a very delightful user experience to head down this path. I can totally understand (specially in legacy apps) the desire to do something like this but I think @bdangit is correct in his comment. I'm open to hearing other opinions if folks feel particularly militant about it, but for now this isn't likely to be something we will implement.

In the strange case of having some blocker where this is an obligation (hey who knows, right?) you could always source or execute the run hook from another package by calling `./$(hab pkg path <origin>/<package>)/hooks/run` . For now I am going to close this issue. If there are more feelings about it or if new community members want to weigh in please feel free to comment!
