### ISSUE TITLE
RFC: Semver support in Habitat plans

### ISSUE THREAD

**Issue by lilianmoraru** [habitat-sh/habitat#1459]
Currently `Habitat` does not support defining dependencies in a semver style.
That's why we need to use workarounds like: [boost159](https://app.habitat.sh/#/pkgs/core/boost159/1.59.0/20160708172826), [postgresql94](https://app.habitat.sh/#/pkgs/bixu/postgresql94/9.4.9/20161021154118), [erlang18](https://app.habitat.sh/#/pkgs/core/erlang18/18.3/20161103210131), [jdk8?](https://app.habitat.sh/#/pkgs/core/jdk8/8u111/20161104002306), [jre8?](https://app.habitat.sh/#/pkgs/core/jre8/8u111/20161104002615), [readline6](https://github.com/habitat-sh/core-plans/pull/181), `icu56`(coming), other coming...

Could we have `Habitat` support `semver` style dependencies?
Example with `readline` could look something like this:
```
pkg_deps=(core/glibc =core/readline/6)
```
This would make sure that if the package is rebuilt, than it uses the latest `6.x.x` version.

Or:
```
pkg_deps=(>=core/glibc/2.22 =core/readline/6.3)
```
Would use at least `glibc 2.22` and the latest `readline 6.3.x`.

One issue that needs to be raised is that currently `pkg_version` can be anything.
I myself used it to say `pkg_version=master` where the package would be the latest version from Git.

How could the folder structure look in `core-plans`?, example:
```
core-plans/readline/base/plan.sh
core-plans/readline/6/plan.sh - sources ${PLAN_CONTEXT}/../base/plan.sh
core-plans/readline/7/plan.sh - sources ${PLAN_CONTEXT}/../base/plan.sh
```

**Comment by beddari** [comment]
There has been a lot of discussions around this earlier if you dig through. Nothing has really happened, though(?) which is a bit sad.

Right now, this is one of the largest UX issues in Habitat in my opinion. I support the idea :+1: but don't have much details to add.

**Comment by eeyun** [comment]
Theres a lot to consider with an RFC like this because the way we currently handle versions of packages is tied to lots and lots of the codebase including all of the build-service bits and depot behavior which doesnt even take into account how this affects packages being built over source providers that ignore semver altogether.

For the sake of anyone who is interested in adding to the discussion the current versioning scheme/process is documented here: https://github.com/habitat-sh/core-plans/blob/master/CONTRIBUTING.md#package-name-conventions

I'm personally all for continuing the dialogue if it's useful to people but up to this point the downsides of attempting to make a change like this _appear_ to outweigh the upsides. That being said, the folks who have the most clarity on the subject though are going to be @reset, @adamhjk and @juliandunn

**Comment by adamhjk** [comment]
I have a pretty solid point of view here, but I'm tied up for the rest of the day. I'll get to this soon. :)

**Comment by reset** [comment]
I'm going to answer for @adamhjk here because I know that we're on the same page.

The short answer is no, it's _impossible_ to accomplish this as described. Not all software projects use SemVer for their versioning so this isn't a guarantee that we can provide in our UX. It's the intent of the Habitat packaging system to favor the upstream's choice of how they want you to consume their software. As @eeyun pointed out, we've got a guide on how to name the software to help assist maintainers with this but we after chatting about this topic yesterday and today we realize we've got a few things we need to clarify.

Let's take PostgreSQL and Ruby for an example to work through. PostgreSQL provides 6 release channels (9.6, 9.5, 9.4, 9.3, 9.2, and 9.1). Ruby provides 4 (2.3, 2.2, 2.1, 2.0). This would map to `core/postgresql96`, `core/postgresql95`, etc and `core/ruby23`, `core/ruby22`, etc. The big difference between PostgreSQL and Ruby is that PostgreSQL doesn't want you to track the idea of "head" at all while Ruby is perfectly ok with that. This is because it's just not safe to upgrade your instance of PostgreSQL between minor versions without performing some additional work while with Ruby that's pretty much just fine. We outline this in the naming conventions described in the guide that @eeyun linked and try to get the point across through examples but we should, and will, take a pass to clarify further.

This would mean that we've named our PostgreSQL package incorrectly - it should be `core/postgresql96` and not `core/postgresql`. Remember, PostgreSQL does not want you to track head. Ruby is also technically named incorrectly as `core/ruby` (it should be `core/ruby23`), but it's not really an issue because Ruby is fine with tracking head.

Through this discussion we realized that we're not only missing some clarity in the naming conventions guide, we're also missing a feature. You want to ask for `core/postgresql` but that's just not safe. In this case we need a type of package which occupies that space but it's just a list of suggested packages. "Did you mean `core/postgresql96`, `core/postgresl95`, ... ?". For Ruby we don't need to stop and get clarification on what the package builder meant, instead we can just provide another similar type of package which is just a pointer to the latest Ruby, so `core/ruby` actually is just a pointer to `core/ruby23`.

**Comment by adamhjk** [comment]
Another aspect to this is the desire for someone building packages to track software "off" of a given upstreams HEAD. When a project approaches things as PostgreSQL or Ruby do, core can naturally provide a path for each of the currently releasing HEAD (6 and 4, respectively). When a project instead intends for people to stay on a single go forward HEAD, we provide only one named package. If you want to link to a specific version, you can do that, but the upstream doesn't provide a supported way for you to stay pinned in a safe way. 

To handle that, origins make it possible to have more specific dependencies - essentially allowing individuals to become new upstream HEADs. This puts the penalty on maintenance where it belongs - you're opting out of the upstreams perspective on their own software, and in so doing you're taking ownership of your new HEAD.

**Comment by beddari** [comment]
A future "noop metapackage" feature as mentioned above will clear up most of the UX issue I mentioned. Also I'm thinking about how to explain the above reasoning as efficient as possible to others ...

**Comment by rsertelon** [comment]
This should be fixed with https://github.com/habitat-sh/core-plans/pull/1280

**Comment by mwrock** [comment]
closing since RFC has been created in core-plans.
