### ISSUE TITLE
RFC: Health check for plans

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#1470]
When building a package, it would be nice to have something to make sure that some basic things in the package are ok. Sometimes if you don't configure things correctly, you could, for example, produce binaries that are not linked properly and will not work in some cases.

Omnibus has a pretty elaborate system for checking what it produces: https://github.com/chef/omnibus/blob/master/lib/omnibus/health_check.rb

A simple one-liner to start would be `find $pkg_prefix -executable -type f | xargs ldd | grep -i "not found"`

Not sure where exactly this would go but it would be a good sanity check.

**Comment by bdangit** [comment]
Ah. Would it be more correct if this were called an inventory checklist?  Hab already has a health check and it's to grab status of it during runtime.

**Comment by themightychris** [comment]
I wrote about this same thing here: https://forums.habitat.sh/t/should-the-build-process-check-and-warn-about-libs-with-missing-deps/344

In addition to looking for "not found" in `ldd` output, why not also look for any paths that aren't covered by `pkg_deps`? This would stop tons of mysterious runtime failures with clearly present binaries reporting "file not found", sometimes deep into runtime after some secondary lib gets loaded

`do_default_strip` is already `find`ing and looping through all binaries in `$pkg_prefix` so that might be a good place to do it, though that takes the workflow step from "strip binaries" to a more generic "post-process binaries"

**Comment by rsertelon** [comment]
It seems a bit harsh for me that habitat would fail if one `.so` has missing links. At least we should be able to disable the check.

For example, in the `core/jre8` some libraries have missing links, and I think it won't bother most of this package's users because they are either covering deprecated java APIs or because they are irrelevant server-side. I'm new to package maintenance (always been on consumer side before) so I might be completely mistaken... :)

**Comment by themightychris** [comment]
@rsertelon I would argue a plan should exclude/delete such libraries from its artifact output since they're essentially corrupt and will not work consistently. Don't export what can't be supported.

It would be reasonable though for there to be a way to turn such errors into mere warnings.

**Comment by rsertelon** [comment]
This one seems really similar to #1465

**Comment by mwrock** [comment]
Closing this in favor of #1465 which seems close enough to cover this as well.
