### ISSUE TITLE
Make compression level configurable

### ISSUE THREAD

**Issue by smartb-pair** [habitat-sh/habitat#1522]
Our experiments Habitizing our Python monolith have been slowed down by very long build times for the `.hart` artifact - the compression step especially takes nearly 6 minutes. A method for speeding this up (lower compression option?) would be great.

@bixu works with us and says that Habitat us using `xz` internally, so maybe there could be a flag we can pass to `hab pkg build` to control the program's compression level?

cc @arochaf

**Comment by eeyun** [comment]
@smartb-pair would you be willing to share with us a bit of repro detail on this? Some of the decisions we made around compression were early on so we're definitely willing to revisit this, especially considering the progress in the codebase since those decisions were made.

We'd like to look at this but some more details would be awesome.

Thank you!

**Comment by adamhjk** [comment]
Are you building inside of a docker based studio on a Mac?

**Comment by bixu** [comment]
Yeah actually we are in the worst cases.

Given the slowness of xhyve (sp?) file access, maybe the right first step is to add some sort of timing information to the `hab pkg build` output so that it's easier to see where the most time is being spent? I think even on our AWS-based Jenkins host the compression step takes several minutes.

Alternatively we can try vendoring some of our bigger Python modules like SciPy...

**Comment by adamhjk** [comment]
Yeah, it's all because dockers driver implements the file sharing in user space, and does so very badly. There literally isn't a way out of it besides not using file sharing - this is why my development of habitat moved into a VM, even though the docker workflow was so convenient. I would expect the docker case to be something like 4x worse than without docker involved.

Adding timing output would be fine. It feels like there is very little risk in allowing a build time flag to reduce the compression ratio. 

The next question is whether we want to support more than one compression algorithm. We could extend the `hart` format to allow that, but at the cost of more dependencies. The default settings are certainly err-ing on the side of tighter compression at the cost of CPU and wallclock time.

**Comment by smartb-pair** [comment]
My feeling is that a compression-level flag is enough.  Build timings feel like a benefit in general - most of us start caring about this at some point.

**Comment by smith** [comment]
> Build timings feel like a benefit in general - most of us start caring about this at some point.

I spent a fair bit of time experimenting with suggestions on this page: http://stackoverflow.com/questions/5014823/how-to-profile-a-bash-shell-script-slow-startup

I think strace can give you a lot of timing data too, but I don't know it very well.

I would love to be able to run a build and see how long everything took, and it's certainly possible so I hope somebody gets to making it before I do.
