### ISSUE TITLE
How to clone private git repositories, or: How to inject secrets into a plan.sh / the studio?

### ISSUE THREAD

**Issue by igalic** [habitat-sh/habitat#1543]
The studio is a very restricted — and, chrooted — environment.
This makes it particularly hard to clone *private* git repositories.
What's the best way to accomplish this?
How do you inject secrets into your plan.sh, or how do you pass them thru to the studio?

**Comment by reset** [comment]
Thanks for filing a GitHub Issue.

In the Habitat org, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Habitat?" are better answered by our awesome community on the [Habitat forums]( https://forums.habitat.sh/), or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists here. On StackOverflow, please tag your question with the "habitat" label so that it shows up in this list.

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
