### ISSUE TITLE
Dead nodes are not aged out of the supervisor ring

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#1544]
[This may only be an issue starting with 0.14 hab-butterfly]

When a supervisor in a ring is restarted, the GUID/IP still sticks around in the ring census and does not age out. When a runtime binding is used, it will include the dead nodes. The runtime binding may need to filter out confirmed dead nodes.

**Comment by adamhjk** [comment]
You can at least route around this issue by checking to see if the member is alive - they all have a {{member.alive}} setting. 

That said, I think it's worth aging things out - what we really need is to have a longer conversation about how to implement this, and either we do it just on members, or we do it for any rumor.

**Comment by adamhjk** [comment]
There are two issues here. The first is in the title of the issue - dead nodes do not age out. We need to have a solution for this, likely as part of a larger conversation about garbage collection thresholds within Butterfly.

The second is the practical issue - which is that, inside a template, you need to be careful to only include `alive` members if thats your intent.

```
{{#each bind.database}}
{{#if alive}}
{{/alive}}
{{/each}}
```

Would give you the list of only alive members, and would be the equivalent of the behavior you want. We investigated adding a helper to make this pattern more common - the issue here is that it would require essentially duplicating the functionality of the `each` helper, and modifying its internal loop logic to deal with the specific guard. While possible, its both more work, and not really any more clear to the end user.

We propose to simply update the documentation for this use case, so people aren't surprised by the behavior.

**Comment by adamhjk** [comment]
Leaving this issue open, as the problem in the title still stands.

**Comment by reset** [comment]
In the current master branch we have helpers for filtering dead nodes from our config templates and there are no known issues with dead nodes hanging around.

We will need a way to garbage collect but we should open another issue for that since it's quite a large feature in itself
