### ISSUE TITLE
Add support for using existing PGP/GPG keys for package signing/validation

### ISSUE THREAD

**Issue by msuriar** [habitat-sh/habitat#1726]
I already have GPG keys that I use for code/commit signing; it would be useful to use the existing PKI infrastructure for this rather rolling yet another set of credentials.

**Comment by smith** [comment]
Thanks for the suggestion.

Interestingly, Habitat originally started off using GPG as the signing method, but due to performance and user experience considerations it now uses its own implementation using libsodium.

If this is something that's necessary, it could probably be provided by some external tool or compatibility layer, but it's not something that's going to be worked on in Habitat core by the core team in the foreseeable future.

If you're interested, the code that provides the crypto is here: https://github.com/habitat-sh/habitat/blob/master/components/core/src/crypto/mod.rs

Going to close this, and I think opening a discussion on https://forums.habitat.sh/ could be useful for other people who are interested in pursuing such a feature.
