### ISSUE TITLE
[security][ux] Do not build software as root

### ISSUE THREAD

**Issue by moretea** [habitat-sh/habitat#1733]
At the moment, software is build as the `root` user. Besides that this is a potential cause of a hoard of security issues, it makes it possible for software that is being build to influence other files in `/hab/pkgs`.

I'm running into this problem with `pecl`, a way to install php packages.
What I would expect is that my package would not be able modify files in `/hab/pkgs/core/php5/*` (or for that matter any file in `/hab`.), but apparently it is.

To solve this, I would suggest to use several build users, and make the `/hab/pkgs` readable, but not writeable to those build users. Multiple build users are needed to isolate concurrent builds from each other.

**Comment by bdangit** [comment]
> "it makes it possible for software that is being build to influence other files in `/hab/pkgs`"

While this is true that other files could be modified during *buildtime*, habitat only packages your files that are placed into `$pkg_prefix` during `do_install()` phase.  `$pkg_prefix` is normally `/hab/pkgs/origin/pkg_name/pkg_version/builddatetime/`.  This means habitat will not package modified files under another $pkg_name like `core/php`.  It will only be for `core/pecl` or whatever you typed in `build myorigin/mything`

Furthermore, during runtime, you can rest assured that any dependencies you had will be what is directly from the depot unless you had uploaded a modified version of core/php.  However, it won't be possible if you are not part of the origin `core`.  It also will be challenging to do because when you build core/php, you would rebuilding the core/php from its plan.sh and it won't contain any modified files that pecl had performed.  It could be done, but it will be challenging. 

Now with that said, if pecl is modifying any of your dependencies files and you needed them during runtime, you'll have to think about how will do that during runtime instead of buildtime.  If your intention is not to modify php, then you need to look at how pecl can be configured to keep all in your own pecl context at buildtime.  Then when you are ready to run pecl during runtime, it will be safe to run.

With great power comes great responsibility... :)


As far as other security issues that are attached to `root`, I don't think its unreasonable to run as root during buildtime.  You can only mess up yourself.  During runtime however, its important to respect root.  You are of course running the binary and it will also be underneath the hab-sup which is also running root.

**Comment by moretea** [comment]
Before we dive too deep in the PHP case; it's just an illustration of why this is a problem. I'd like to keep the discussion focused on the design of Habitat.

> While this is true that other files could be modified during buildtime, habitat only packages your files that are placed into $pkg_prefix during do_install() phase

My point is that because you are allowed to modify your entire studio, you won't notice that some programs are bad actors w.r.t how Habitat expects things to work, by writing in locations that are not going to end up being packaged. It's a lot easier from a debugging perspective if things fail when the logical error that is made by the package manager occurs, instead of having to think of all possible impurities in some package manager.

> Now with that said, if pecl is modifying any of your dependencies files and you needed them during runtime, you'll have to think about how will do that during runtime instead of buildtime. If your intention is not to modify php, then you need to look at how pecl *can be configured to keep all in your own pecl context at buildtime*. Then when you are ready to run pecl during runtime, it will be safe to run.

Exactly. However, this is hard to find out since PECL doesn't crash during build time. Resolving dependencies should be done at build time, where you'd fetch all the packages and install them in a proper place. It should be quite simple to point PHP or PECL to this alternative location.
In ruby, one would simply set `GEM_HOME`, but have no clue what exactly should be done for PHP.

Nix solves all these design issues by by making everything in the nix store (`/nix/store/<cryptohash>-$name-$version/`) read only and having build users that build the package in a temporary build directory.

**Comment by moretea** [comment]
> As far as other security issues that are attached to root, I don't think its unreasonable to run as root during buildtime. _You can only mess up yourself_.

Not if this is run in a shared build system. Anyhow, I'd argue that the principle of least required permissions applies here.

> During runtime however, its important to respect root. You are of course running the binary and it will also be underneath the hab-sup which is also running root.

This is a problem as well. AFAICS at the moment, everything is run as the `hab` user. E.g. I don't want my application server to have access to the files that are managed by postgres; this completely circumvents any security systems implemented in postgres. I'll open an other issue about this shortly.

**Comment by reset** [comment]
@moretea correct me if I'm misunderstanding, but since the build is running in a throw away jail it would seem that this is ultimately a request to enhance isolation between builds?

We recommend only re-using a studio between builds when you're iterating on plans. That's why the interactive studio became a thing, really. Once you commit your plan to source control and begin running builds I wouldn't recommend re-using the studio.

Perhaps there's another use here or there's something missing that the studio isn't providing?

**Comment by reset** [comment]
@moretea it's been a bit since we've heard from you on this issue, do you still want to keep the discussion going?

**Comment by moretea** [comment]
There are two behaviours here at play.

| Behaviour during build | Docker | Nix | Habitat |
|---------|-----------|------|-----------|
| Overwriting any file   | By design | Forbidden | Allowed |
| Changes | Propagated to next image layer | Not applicable  | Not propagated in build artifact |
 
The main point here is that the combination of allowing to overwrite any file during the build and not propagating those changes moves the observation of failure further away from where it actually happens. Furthermore, it would appear to work if you'd try to debug this issue from within a development studio. This makes it in the general case _very_ hard to debug.

Creating a fresh studio for new builds does not solve that problem IMHO.

**Comment by adamhjk** [comment]
I see what you're asking for. Essentially, if you are building `core/foo`, and that build script writes into `$(pkg_path_for core/bar)`, you want to get a permissions error, rather than polluting the existing package path. 

I don't have a nix instance handy, so I'm not sure what the permissions are during build. From a lifetime of building Debian packages, you basically:

a) Must not run ./configure and friends under fake root.
b) Should run the build process as a 'regular' user
c) Fake the root user for installation and archiving - this would result in permission errors if you tried to deal with root-owned /hab/pkgs.

Something like that would work for you, yes?

**Comment by mattray** [comment]
Related: https://github.com/habitat-sh/habitat/issues/4625
