### ISSUE TITLE
Make docker image habitat/devshell public

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#1745]
Image habitat/devshell which is referenced in the [docker-compose.yml](https://github.com/habitat-sh/habitat/blob/master/docker-compose.yml) is not publicly available:

```
$ docker pull habitat/devshell
Using default tag: latest
Error response from daemon: repository habitat/devshell not found: does not exist or no pull access
```

**Comment by fnichol** [comment]
That is a good point--we don't publish the devshell image currently. This is primarily so that each developer has an opportunity to build the newest/freshest toolchain from scratch rather than relying on the core team to test, certify, and manage a canonical version. If a developer attempts to create the devshell image and is unsuccessful, the team considers this a bug and we'll address it--one way we attempt to aggressively consume latest versions of dependencies and fix-forward our development environment. My weekly ritual (usually first thing on a Monday) is to completely tear down my environment with `make distclean`, update to the latest Docker for Mac and follow the `BUILDING.md` instructions as written. My hope is to catch issues before anyone else does.

**Comment by fnichol** [comment]
And yes, I'd agree that #1746 will make our development environment even easier and natural for existing Docker Compose users. Yay!
