### ISSUE TITLE
Service tries to copy run hook before initialization

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#1797]
When starting `core/postgresql` with master I'm getting the following output:

```
hab-sup(MR): Butterfly Member ID 93093da795ee484c81861d08b43d58d7
hab-sup(SR): Adding core/postgresql/9.6.1/20170203184423
hab-sup(MR): Starting butterfly on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
hab-sup(SC): Updated pg_ident.conf 0e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8
hab-sup(SC): Updated postgresql.conf 26dee9e7c2dc0ba5505943b92b7dcc34e6dfdf4aa644a06f4e5c72571b988f1e
hab-sup(SC): Updated pwfile 30087c89f3dfc2b2179a2b567a67f094cf1cd8b1c6e3cc1473aef95fe65de533
hab-sup(SC): Updated recovery.conf aa2fc9588ec7a06b0269507f6f0764efbd2952da466bc20ab49cfcd08ee1b86e
postgresql.default(SR): Failed to copy run hook: hab-sup(ER)[src/error.rs:368:8]: the source path is not an existing regular file
postgresql.default(SR): Executing hooks; f8f292cf8bbe4bab9b6eeb1d9d2ddc15 is the leader
postgresql.default(SR): Initializing
```

It looks like the `run` hook is being copied before the service has been initialized. I think this behaviour started after the recent refactoring by @reset.
Haven't identified the root cause yet.

**Comment by reset** [comment]
@bodymindarts ah man, sorry for the breakage! I haven't seen this behaviour just yet, let me see if I can replicate it and I'll write back. Will probably be able to look at this within the next two days.

**Comment by mwrock** [comment]
I just started noticing this today (which does not men its the first time I have seen it) expanding on my demo. I have not investigated yet but I'm betting we unnecessarily attempt to copy the run file early in hab start. It does not "break" the startup but certainly adds ugly stderr noise and may give the perception of a breakage. The supervisor initialization function definitely performs the copy AFTER running the init hook which is why I think we just have an extra call to copy_run somewhere.

**Comment by mwrock** [comment]
I dont have time right now to give this a propper end to end attention but opened the above PR #1799 with what I am pretty sure is the fix.
