### ISSUE TITLE
Properly Intercept ctrl+c Interrupts in Windows Supervisor

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1843]
### The Story
Habitat will intercept POSIX signals and forward them on to the supervised child process. Since ctrl+C is transmitted via SIGINT on linux, it is able to propperly respond and gracefully shut down. On Windows, everything is abruptly shut down.

### Acceptance Criteria:
Run the supervisor on windows
Enter Ctrl+C in the supervisor shell
Observe the "good bye" message from habitat

**Comment by mwrock** [comment]
This is now a more urgent issue since the supervisor creates a lock file to prevent supervisorsd from stepping on one another. On Windows ctrl+c performs a hard, abrupt shutdown and therefore the lock file is not cleaned. This means a user needs to manually delete the lock file prior to running the supervisor again.

**Comment by adamhjk** [comment]
Can windows trap the signal?

**Comment by mwrock** [comment]
I know it can intercept it but the semantics differ. I'm researching it now.

**Comment by mwrock** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms685049(v=vs.85).aspx looks to be the magic.

**Comment by reset** [comment]
Fixed in #2014
