### ISSUE TITLE
Supervisor cannot run on Windows nano due to admin check

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1852]
The supervisor cannot currently run on windows nano because it receives the following error:
192.168.137.143: PS C:\Users\vagrant\Documents> hab start core/habitat-aspnet-sample --bind database:mysql.default --peer 192.168.1.141:9638
∵ Missing package for core/hab-sup/0.17.0-dev
hab : ∅ Installing a package requires root or administrator privileges. Please
retry this command as a super user or use a privilege-granting facility such as
sudo.
+ CategoryInfo : NotSpecified: (∅ Instal...ch as sudo.:String)
[], RemoteException
+ FullyQualifiedErrorId : NativeCommandError
✗✗✗
✗✗✗ Root or administrator permissions required to complete operation
✗✗✗
I'm betting this is due to winrm issues and currently winrm is the only way to connect to nano to run the supervisor.

**Comment by mwrock** [comment]
First, since this issue was filed, Microsoft no longer distributes Nano Server as a VM. It is only available as a container image. Therefore it is highly unlikely to be accessed via winrm. However, the default user on nano is `ContainerUser` as opposed to `ContainerAdministrator` so the admin check will fail. However, that will no longer prevent the supervisor from operating as it did when this issue was filed.

There is an issue with the license check on nano. There is no `HOME` directory. So searching for the license file in that location, which is where it would look because the user is a normal user panics.
