### ISSUE TITLE
Error message for `pkgPathFor` needs to be clearer

### ISSUE THREAD

**Issue by smurawski** [habitat-sh/habitat#1904]
`hab-sup` 0.18.0

When a hook or config file is generated with `pkgPathFor`, the initial run will fail with an error about the lack of a service config (since the context doesn't exist yet).  This error is misleading and plan authors probably aren't aware of the internal constructs of the supervisor and when they are ready or not.

We just need a better error message.

**Comment by smurawski** [comment]
Also, the reason that this issue is cropping up is that the ServiceConfig cannot be properly deserialized until there is some census information available, which makes the first pass of evaluating pkgPathFor fail.  I'd be happy to pair with someone on fixing this.

**Comment by bodymindarts** [comment]
@smurawski I've just run into this bug. Perhaps we can pair on it sometime next week.

**Comment by smurawski** [comment]
@bodymindarts I'm out at a conference all next week on the west coast, but I could definitely find some time in the early morning there (Monday, Tuesday, or Wednesday are best) to sync up.  We can sort out a time in Slack if that'd work.

**Comment by bodymindarts** [comment]
After debugging this a bit it looks like I actually ran into https://github.com/habitat-sh/habitat/pull/1788
The deserialization of the ServiceConfig failed due to an integer in the structure exported via a binding.
This is the printout of the error comming from [this](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/templating/helpers.rs#L83-L84) line.
`hab-sup(TP): Deserialize error: Syntax(Message("invalid type: integer `8080`, expected any valid TOML value"), 0, 0)`

The timing issue mentioned in this ticket doesn't seem to be an issue since afaict the hook actually renders correctly even the first time! Just deserializing integerers is an issue.

**Comment by bodymindarts** [comment]
Opened https://github.com/habitat-sh/habitat/issues/2067 to address the issue I am seeing.

It looks like the timing issue mentioned here has been resolved because even on the first run I can see the hook being rendered correctly, despite the error message.

I agree the message is misleading but actually wonder if it should ever float up to the user. If anything else than a serialized ServiceConfig gets passed as context to handlebars thats a programmer error.

**Comment by bodymindarts** [comment]
@smurawski has this been taken care of now?

**Comment by smurawski** [comment]
Yep!  I updated the error message in #2077
