### ISSUE TITLE
`hab pkg binlink` should default to /usr/local/bin

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#1920]
By default `hab pkg binlink` links into /bin. According to https://linux.die.net/man/7/hier /bin is for "executable programs which are needed in single user mode and to bring the system up or repair it.", /usr/bin is for programs installed by the system package manage, and /usr/local/bin is for locally installed programs.

If you binlink into /bin or /usr/bin you could have unexpected consequences resulting from operations your operating system does.

/usr/local/bin should be the default.

Perhaps also, it should test which of these directories exist, so that if you are on a more limited system where /usr/local does not exist, it would show /usr/bin as the default.

**Comment by lamont-granquist** [comment]
i think mac and smartos also wouldn't allow you to write to /bin or /usr/bin and that seems to be becoming increasingly prevalent.    on mac you have to use /usr/local, and on smartos you have to use /opt/local.

**Comment by reset** [comment]
@fnichol cc'ing you since you did the initial implementation of `binlink`. I'm inclined to agree with @smith here but I think we did this for the studio originally, yeah? If that's true - perhaps it means the binlink destination should just be overridden in the studio by default and the actual defaul should be `/usr/local/bin`?

**Comment by adamhjk** [comment]
I think the argument that /bin is for executables needed in single user mode is a very legacy argument, and not super relevant on modern linux boxes (when was the last time you did the full "classic" partitioning scheme, with separate /, /usr, /root, /home, and /var partitions? Yeah, me neither.) 

I'm fine with using `/usr/local/bin`, personally.

![gif-keyboard-15202191813920324454](https://cloud.githubusercontent.com/assets/4304/23775606/5d8d4a9a-04de-11e7-9eeb-20435b1dd9a7.gif)

**Comment by fnichol** [comment]
Yeah, the driving reason behind the default location was that `/bin` was virtually guaranteed to exist and to be in `$PATH` by default. Previously it was defaulting to `/usr/bin` (slightly less evil), but I kept running into minimal systems (busybox, alpine, etc.) where `/usr/bin` may not exist. @lamont-granquist is totally correct about some distros having read-only or permission-denied write access to system level dirs and maybe that's enough to try a different default? Most likely `/usr/local/bin` is a safest next-bet. We'd most likely want to create any parent dirs for it and assume that the directory is on `$PATH` (as before). Any PRs for this need a quick codebase review to make sure we aren't taking advantage of our current default target directory (it would also be a breaking change, but that's fine--just need to call it out in release notes).

**Comment by lamont-granquist** [comment]
Yeah but the bigger problem is that if you're linking into /bin or /usr/bin then you're clobbering distro installed binaries.  That is generally never what someone wants to do by default.  We do that very specifically with /usr/bin/chef-client in omnibus packages because we assert we own chef-client and we hate distro packaging compared to omnibus packages.  But installing the habitat bash over /bin/bash by default is pretty rude.  If someone goes out of their way to want to do that, I'm totally cool with it, and it should be a very short flag away for those people (right to keep and bear footguns and chainsaws and all that) but the default should be something like /usr/local/bin.

The chef-client use case probably does argue that this default should be overridable in the plan.sh so that plan authors can assert /usr/bin over /usr/local/bin if it really makes more sense for that package.

**Comment by lamont-granquist** [comment]
Another possibility is supporting overriding from an env var or rc file so that every plan.sh gets overridden to /usr/bin -- if someone wants to build HabitatOS i'm okay with it being as easy as possible...

**Comment by adamhjk** [comment]
What if we just fell back? We scan PATH for /usr/local/bin, use that if we find it. If we don't, we look for /usr/bin, and finally /bin.

**Comment by lamont-granquist** [comment]
Yep that.  👍

**Comment by lamont-granquist** [comment]
To be clear I was noodling about ideas yesterday that are probably YAGNI for now.  I doubt we need anything much more substantial than @adamhjk's algorithm there...  Habitat doesn't really have to worry about SmartOS or MacOS right this second.

**Comment by mwrock** [comment]
We are converging on `/usr/local/bin`

**Comment by christophermaier** [comment]
Closing per discussion in #4119
