### ISSUE TITLE
Back channels in postgres

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#1968]
Metadata regarding channels are currently stored in memory on the depot. The metadata will now be stored in OriginSrv (previously known as Vault)

**Comment by nellshamrell** [comment]
Brief notes from a meeting with @mwrock 

* 3 main chunks of data in depot 
  * keys (currently backed by postgres)
  * packages (currently backed by redis)
  * channels (currently stored in memory)

* Packages and Channels need to be refactored to use Postgres as backing

* Builder-depot
  * front end
  * depot api
  * src/server.rs
     * routes table toward bottome of file
     * routes map to function
     * all have similar signature
        * take request object
        * return result
    * calls conn.route
    * message types 
      * when creating an origin key, 2 key message types involved
        * OriginPublicKeyCreate
        * OriginPublicKey
        * message types defined in builder-protocol
* Builder-originsrv
  * owns database itself
  * responsibility - everything to do with an origin
  * key parts
    * migrations
    * mode.rs
      * define a handler (string), then call handler in handler.rs
      * always takes args req, sock, and state
        * pull what you need out of args
     * datastore.rs 
        * narrow focus - just getting data in and out
        * actually calls DB with SQL

**Comment by nellshamrell** [comment]
Here is my understanding of the problem as well as my proposed solution.  Would love comments and feedback!

https://gist.github.com/nellshamrell/b1d296b943c52de5625611e46920bdb9

**Comment by mwrock** [comment]
I think you are right on track @nellshamrell !

**Comment by nellshamrell** [comment]
## Implementation Checklist:

### In Builder protocol
Define protocols for channels in builder-protocol/protocols/originsrv.proto

- [ ] OriginChannel
- [ ] OriginChannelListRequest
- [ ] OriginChannelListResponse
- [ ] OriginChannelCreate
- [ ] OriginChannelDelete
- [ ] OriginChannelPackageListRequest
- [ ] OriginChannelPackageListResponse
- [ ] OriginChannelPackageLatestGet
- [ ] OriginChannelPackageVersionGet
- [ ] OriginChannelPackageVersionLatestGet
- [ ] OriginChannelPackageVersionReleaseGet
- [ ] OriginChannelPackageVersionReleasePromote

### In Builder-originsrv

Add migrations and stored procedures for builder-originsrv in src/data_store.rs
- [ ] list_channels_by_origin
- [ ] create_origin_channel
- [ ] delete_origin_channel_by_name
- [ ] list_packages_by_channel
- [ ] get_origin_channel_package_by_latest
- [ ] get_origin_channel_package_by_release
- [ ] promote_origin_channel_package_release

Add handlers for channels in handler.rs
- [ ] origin_channel_list
- [ ] origin_channel_create
- [ ] origin_channel_delete
- [ ] origin_channel_package_list
- [ ] origin_channel_pacakge_get
- [ ] origin_channel_package_latest_get
- [ ] origin_channel_package_release_get
- [ ] origin_channel_package_release_promote

Call channels handlers from mod.rs
- [ ] "OriginChannelListRequest" => handlers::origin_channel_list(message, sock, state)
- [ ] "OriginChannelCreate" => handlers::origin_channel_create(message, sock, state)
- [ ] "OriginChannelDelete" => handlers::origin_channel_delete(message, sock, state)
- [ ] "OriginChannelPackageListRequest" => handlers::origin_channel_package_list(message, sock, state)
- [ ] "OriginChannelPackageLatestGet" => handlers::origin_channel_package_latest_get(message, sock, state)
- [ ] "OriginChannelPackageVersionGet" => handlers::origin_channel_package_version_get(message, sock, state)
- [ ] "OriginChannelPackageVersionLatestGet" => handlers::origin_channel_package_version_latest_get(message, sock, state)
- [ ] "OriginChannelPackageVersionReleaseGet" => handlers::origin_channel_package_release_get(message, sock, state)
- [ ] "OriginChannelPackageVersionReleasePromote" => handlers::origin_channel_package_release_promote(message, sock, state)

## In Builder-depot

(Checklist to be added)
 * Refactor to store data in postgres, rather than memory
 * each action in server.rs should open a connection and pass the protocol and expected result
 * i.e. conn.route::<OriginChannelCreate, OriginChannel>(&request)

**Comment by nellshamrell** [comment]
Re: packages API
```
chefsalim [11:45 AM] 
This is a very small nitpick @nellshamrell
[11:45]  
Currently, when constructing the channel path to promote a package, we have to do this:
[11:45]  
let path = format!(“channels/{}/{}/pkgs/{}/{}/{}/promote”,
                          ident.origin,
                          channel,
                          ident.name,
                          ident.version.unwrap(),
                          ident.release.unwrap());

[11:45]  
The ident is broken up

nellshamrell [11:45 AM] 
ah

chefsalim [11:46 AM] 
It would be nice to do something like how we put upload package
[11:46]  
let path = format!(“pkgs/{}“, ident);

nellshamrell [11:46 AM] 
good point!

chefsalim [11:46 AM] 
this code is in builder-depot-client/src/lib.rs

nellshamrell [11:46 AM] 
ty!
```

**Comment by reset** [comment]
Channels are backed in postgres good enough for use today, we should open up additional issues if we want to make some more improvements
