### ISSUE TITLE
Adding dependencies in scaffolding fails

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#2073]
In a scaffold, if you do something like:

```
_scaffolding_begin() {
  pkg_deps=(${pkg_deps[@]} core/coreutils core/node)
}
```

and then try to run a program in one of those packages' `pkg_bin_dirs`, it will fail, not able to find that program.

This is because hab-plan-build calls `_set_environment` before it calls `_load_scaffolding`, and `_set_environment` uses the values of `pkg_deps` and `pkg_build_deps` to populate the environment variables such as PATH.

If you add packages to those arrays after `_set_environment` has been called, it won't set environment variables for them.

**Comment by rhass** [comment]
@smith Would it be possible for me to work with you tomorrow to try out my fix against your code as well? You might be able to do it on your own, but I have been having to set `HAB_ORIGIN=core` to use plan-build with the changes since there are a few internal bits which seem expect `core` for `plan-build` rather than any random origin.
