### ISSUE TITLE
`hab service load` not picking up `HAB_PACKAGENAME='config="value"`

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#2096]
As far as I can tell `hab service load` is not picking up the environment variable to configure the service the way `hab service start` is.
I would like to verify / fix this but I cannot find the code that reads this variable out in the `hab start` case.
Perhaps @reset can point me there.

**Comment by fnichol** [comment]
@bodymindarts I'm pretty sure it actually lives way down in `ServiceConfig`/`Svc` [code](https://github.com/habitat-sh/habitat/blob/8d4463df30fbc93de33f578525df5cb9861925fc/components/sup/src/manager/service/config.rs#L496-L516) which violates one of our emergent rules: don't use environment variables deep in the business logic code (it belongs out at the edges as close to arg parsing as you can get). As such, it might not actually belong here long term and worse, this code gets executed in the Supervisor process which won't have access to separate the `hab service load` process. I hope this helps you to start looking--I think it's beyond reasonable that a user would expect this behavior.

**Comment by bodymindarts** [comment]
@fnichol okay thanks for pointing that spot out. Looks like there is no quick way to do this so I will leave it as is for now.

**Comment by reset** [comment]
Environment variables will only be honored by `hab sup run` and `hab start` (on first run). We don't think it's a good idea to honor an environment variable set on `hab service load` since there isn't any environment being set up. We can definitely make seeding initial configuration easier. You can currently do it by writing a `user.toml`, but that feature seems to be a little too obscure as is.

@smith is writing up a follow up issue to help get the discussion going on how to move foward with initial seeding

**Comment by smith** [comment]
#2119 has been opened to add a command to write out a user.toml, which could be used in place of this.
