### ISSUE TITLE
Add support for git credential pass-through to studio.

### ISSUE THREAD

**Issue by rhass** [habitat-sh/habitat#2099]
As a developer, I would like to be able to access private repositories which require some form of authentication to clone and for security reasons I do not want to store the credentials within the plan itself.

See the following thread discussion on slack (hopefully it doesn't vanish into the ether): https://habitat-sh.slack.com/archives/C0VBY57UP/p1492113443402203
https://habitat-sh.slackarchive.io/general/page-100

**Comment by bdangit** [comment]
There is this feature that was added way back to support sourcing of `.studiorc` files if it exists.  When you enter the studio, Hab would automatically source it.  You could potentially place any git creds like tokens and/or any other secrets that need to get passed.

**Comment by reset** [comment]
The primary development scenario that we are working towards is to have the developer clone their software onto their host machine and then enter a studio from there. With that said, pulling from git from within the studio is something that you may still need to do given this scenario. For example, you may have a build tool which pulls a dependency from a private git repo which requires these credentials as part of the build process itself.

I'm going to mark this as help wanted for now. I think @bdangit is on the right track with the `.studiorc` file. If this works well we should promote this in the docs and ensure there's a global `.studiorc` which would prevent you from needing to create one for each software project to get common credentials such as these into your studios.

**Comment by rhass** [comment]
I am going to close this as I .studiorc does what we need.

**Comment by danielsdeleo** [comment]
Copying this from the other issue:

...in my opinion the experience (using `.studiorc` for this functionality) falls short of hab's standards. The way it's done now is referenced in this documentation issue: https://github.com/habitat-sh/habitat/issues/3145 but it seems silly for everyone to need to cargo-cult that code around.

If at all possible, authentication should just follow me in to the studio so I don't think about it. If some extra configuration is actually required (maybe my SSH key has a non-standard name or whatever), it would be nice if I got an error message that helped me figure out what to do. It's tricky since the build tool is in charge but maybe some magic could be done by wrapping `git clone` and annotating the error message in some way.

**Comment by rahulwa** [comment]
[Can anybody help me to pass host ssh key to studio (like while doing hab studio enter) so that can be accessed at build time.](https://github.com/habitat-sh/habitat/issues/3145#issuecomment-334865837)

**Comment by rsertelon** [comment]
Maybe the new secret sharing feature of studio can help? (can't find doc though)
