### ISSUE TITLE
`hab sup load` should not return status 1 when service is already loaded.

### ISSUE THREAD

**Issue by rhass** [habitat-sh/habitat#2111]
Habitat returns non-zeroi status when running the command `hab sup load` against a service which has already been loaded. The expected behavior is to return a non-zero status to prevent breaking automation which may run this command more than once, and present the similar message which suggests "unload" if the intention is to regenerate the spec file.

- [x] The OS (including version) where you are running any of the Habitat commands.
Ubuntu 16.04.2
- [x] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:
```
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_core::os::process::imp: Calling execvp(): ("/hab/pkgs/core/hab-sup/0.20.0/20170407020554/bin/hab-sup") ["load", "core/postgresql"]
hab-sup(MN)[src/main.rs:232:23]: Service already loaded, unload 'core/postgresql' and try again
```

**Comment by rhass** [comment]
Alternatively, if we want to keep the return as a non-zero status we should add a command to check to see if the service has been loaded such as `status` or `info`.

**Comment by reset** [comment]
@rhass I had it return a non-zero because this command accepts arguments which configure the service. There's no way to change a service without first unloading it, so I added a `--force` flag to the `load` command to simulate an `unload`/`load` (aka `reload`). I think it's appropriate to keep this a non-zero exit code but we could change it to something more informative to explain that we understood your request but there was already an existing service loaded.

Totally, we should add a `status` and perhaps a `list` command

**Comment by fnichol** [comment]
@rhass Yeah, agreed that we are currently missing a `status`/`list` kind of subcommand which would help out here. If we were to add a more helpful error message would that help?

**Comment by smith** [comment]
#2118 has been opened to add `hab sup status`.

**Comment by reset** [comment]
Closing this in favor of #2118. Thanks for the suggestion @rhass!
