### ISSUE TITLE
sys.ip always reports 127.0.0.1 (when 0.22.* and 0.21.0 supervisors are communicating)

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#2298]
In a template `{{bind.database.first.sys.ip}}` is always reporting `127.0.0.1`. Don't quite know why yet.

**Comment by bodymindarts** [comment]
It seems like this issue only comes up when a service supervised by 0.22.1 was trying to consume a service running on supervisor 0.21.0.

**Comment by reset** [comment]
@bodymindarts it's absolutely because of the differing versions. When I refactored the SysInfo struct I realized that it was TOML and it should have been a protobuf file but I forgot to make the change. I'm unfortunately going to have to break this protocol one more time to swap it from TOML to a protobuf. This will prevent this from happening again
