### ISSUE TITLE
[studio] improve filesystem and mount points handling inside studio

### ISSUE THREAD

**Issue by tixxdz** [habitat-sh/habitat#2390]
In order to help us troubleshoot the issue, please be sure to include the following information if applicable:

   Fedora: 4.10.8-200.fc25.x86_64

   hab --version
   hab 0.23.0/20170511215221

**Issue:**
When you enter the studio hab builds the environment, however when we exit studio, habitat does not clean its environment and mount points propagate back to the initial mount namespace or parent namespace.

The following mount points are related to hab:
`devtmpfs on /hab/studios/home--tixxdz--dev/dev type devtmpfs (rw,nosuid,seclabel,size=1527760k,nr_inodes=381940,mode=755)`

`devpts on /hab/studios/home--tixxdz--dev/dev/pts type devpts (rw,relatime,seclabel,gid=5,mode=620,ptmxmode=000)`

`devpts on /dev/pts type devpts (rw,relatime,seclabel,gid=5,mode=620,ptmxmode=000)`

`proc on /hab/studios/home--tixxdz--dev/proc type proc (rw,relatime)`

`sysfs on /hab/studios/home--tixxdz--dev/sys type sysfs (rw,relatime,seclabel)`

`tmpfs on /hab/studios/home--tixxdz--dev/run type tmpfs (rw,relatime,seclabel)`

`/dev/mapper/fedora-root on /hab/studios/home--tixxdz--dev/src type xfs (rw,relatime,seclabel,attr2,inode64,noquota)`

If I exit studio then I should not see them, however they are still there, maybe they are pinned by supervisor.

There are two issues here:

1. Mount points of hab studio should not propagate back to parent mount namespace.

2. When hab studio terminates it should unmount all mounts, a safer approach maybe to freeze them or remount readonly then unmount.

After investigating more it seems that hab studio does not create a mount namespace I think it should.
Inside studio by reading `/proc/self/ns/`
`lrwxrwxrwx 1 root root 0 May 17 12:44 mnt -> 'mnt:[4026531840]'`

Outside studio:
`lrwxrwxrwx. 1 tixxdz tixxdz 0 May 17 14:44 mnt -> mnt:[4026531840]`

I am not even sure if these mount points are shared between different studios.

So unless there is a real good reason to share the same mount namespace and mount points. I would suggest to create:

1. new mount namespace with `unshare(CLONE_NEWNS)`  https://linux.die.net/man/2/unshare
    So we are in a different working space for each studio

2. Then remount root / with `MS_SLAVE|MS_REC`
    http://man7.org/linux/man-pages/man2/mount.2.html
    Disconnect root or mark it as slave, so new mount points won't propagate back to the parent mount
    namespace and other instances of hab or studio won't notice each other...

3.  Create the root directory of studio if necessary can be done before too...

4.  Create all those mount points that we need: procfs, sysfs, devpts, ... under the root of studio.

5.  Change to new root by:
     `chdir(root),`
     `mount(root, "/", NULL, MS_MOVE, NULL)`
     `chroot(".")`
     `chdir("/")`

6.  Finally remount root again with MS_SHARED so studio works as expected on most setups.
     `mount(NULL, "/", NULL, MS_SHARED|MS_REC, NULL)`

These will allow to have total separate instances of studio and builds, of course to optimize the cache then it can be created before and bind mounted inside each instance of studio, saving space, the directories can even be suffixed with the appropriate hab version to not mix plans between different instances!

These steps will fix issue (1). To fix issue (2) when studio exits it has to unmount all mounts. Even if the mount points need to be shared for supervisor, I believe they should not run in the initial mount namespace, at least create a new mount namespace for all services that are handled by supervisor, still having separate mount namespaces allow better separation.

Thanks!

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] The OS (including version) where you are running any of the Habitat commands.
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

**Comment by rsertelon** [comment]
@elliott-davis I know you've been working on something related to mounts, does this look like it?

**Comment by rsertelon** [comment]
@elliott-davis gentle ping :p

**Comment by eeyun** [comment]
There are a few things bound up in this issue. The mounting work that elliott was working on I don't think applies here actually but was more related specifically to the worker in builder and our airlock environment. 

We leave those mounts in place because the behavior we want is for users to be able to re-enter a studio if they're building inside an interactive chroot-based studio. It provides a bit more permanence than the docker based studio (which can now also be used on Linux) and I doubt we'll want to change this behavior to automatically clean up when using a native Linux studio. 

Now that TOTALLY ISN'T to say that we are handling all of the studio creation and mounting totally correctly, just a bit of perspective on why we don't automatically clean up after we exit. WRT to the namespacing and shared mount points, the only thing I think _could_ be problematic is the package cache. I can't remember whether or not we mount that in from the host or not.

Further discussion on this it would be good to bring in @fnichol but @elliott-davis, fletcher and myself are going to be out of pocket for a few weeks. Sorry for the slow update on this one!
