### ISSUE TITLE
Builder services not auto-recovering from rt:route:2

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2433]
Builder services can get into a state where they are not registered with the router. They should be able to auto-recover and get re-registered without having to re-start the router, but currently that is not happening.

**Comment by chefsalim** [comment]
We are seeing this quite frequently on acceptance currently.

**Comment by nellshamrell** [comment]
Recording my debugging process in this gist and updating it as I go along.

https://gist.github.com/nellshamrell/8ce276a4f67e40926543e6d78b746c6f

**Comment by nellshamrell** [comment]
Quick question on this:

Does a builder service = originsrv, sessionsrv, etc?  Would originsrv be one builder service?

Additionally, after some investigation, it seems like this error is generated when the router cannot find a shard that used to be there.  So would this be related to shards somehow disappearing, or the entire service itself?

**Comment by nellshamrell** [comment]
Is a service made up of many servers?

**Comment by raskchanky** [comment]
Yes, originsrv is one builder service.

I haven't dug into the router code before, but from looking at it just now, it looks like this error happens when the router can't find a server/service to handle the protocol for the incoming message.  The router looks like it maintains an internal mapping of protocols to metadata about who/what can handle those protocols.  It's entirely possible that the names of the variables are leading us astray here, but I don't think that shards are literally disappearing.

The distinction between servers and services is a little blurry for me, and might just be a naming choice rather than a distinction between separate entities.  I think e.g. originsrv is one service, but I'm guessing you can have multiple instances of that service running at once.

Shards are specific to the database and not to any one service, as far as I know.  They're there to partition the data in a way that's easier to scale.

**Comment by reset** [comment]
@raskchanky is spot on. I'll go through some terminology here and try to do my best to clear some things up.

Server - a builder application server. These are `originsrv`, `sessionsrv`, `jobsrv`, and `scheduler`. Out of these `originsrv` and `sessionsrv` are the only two which are actually sharded
Shard - a bucket of data being hosted by a server. A server may host 1 or more shards

Servers connect to the router and talk over two ports. One is a "request/response" port and the other is a "heartbeat" port. We should be retiring servers which are hosting shards out of the Router's internal memory map once we no longer are receiving a heartbeat.

The problematic piece here seems to be when a new server connects. OnConnect we send a registration message which indicates to the Router that we are going to be hosting some shards. I think that what is happening is we have not yet determined that the original server hosting these shards has gone away so we ignore this registration message. Later, we drop our previous registrations since we are no longer receiving a heartbeat.

I haven't taken the time to debug things yet but this is all the information I would have before I started debugging myself. Good luck @nellshamrell!

**Comment by nellshamrell** [comment]
@chefsalim have you seen this happening mainly when adding an additional instance of a builder-application server? (i.e. when adding in another instance or originsrv).  Of does this seem to happen on new deploys?  Or randomly?

**Comment by nellshamrell** [comment]
Still working on replicating this locally - [here are the steps I have taken so far](https://gist.github.com/nellshamrell/4c1902b345ac93cd3be25a8bf5548a28)

**Comment by raskchanky** [comment]
@reset It's interesting you mention that `originsrv` and `sessionsrv` are the only two which are actually sharded.  Both `jobsrv` and `scheduler` register 128 shards with the router, in addition to `originsrv` and `sessionsrv`.  Looking at the db, `scheduler` only has `shard_0` but `jobsrv` does indeed have 128 shards.  I wonder if the disconnect between what `scheduler` actually has and what it's registering with the router is related to this error.

**Comment by raskchanky** [comment]
Also I don't see where the router ever drops any registrations from its `servers` map.

**Comment by raskchanky** [comment]
One way to trigger this error is to restart the router, then try any API request.  It will fail immediately with `rt:route:2`, which makes sense because the router's `servers` map is empty after a fresh start.  The existing services aren't aware that the router restarted and the router doesn't know about any of them any more.

**Comment by nellshamrell** [comment]
Confirmed - starting all services, then rebooting the router does indeed replicate this error message.  I'm starting to wonder if the list of servers in router should be persistent somehow?

**Comment by nellshamrell** [comment]
Summary of my understanding atm.

1) User starts Router
2) User starts Originsrv and Sessionsrv
3) Originsrv and Sessionsrv register themselves with Router
4) Router restarts (user caused or otherwise)
5) Router is no longer aware of Originsrv and Sessionsrv, any requests that need to access them receive route:2 error in response
6) User restarts Originsrv and Sessionsrv
7) Originsrv and Sessionsrv register with router
8) Requests to OriginSrv and Sessionsrv are again routed to the correct services

As to how to fix this...I'm wondering if the Router's internal server map should be persistent.  Not sure otherwise how to make it re-aware of the originsrv and sessionsrv, but I am definitely open to other thoughts.

**Comment by nellshamrell** [comment]
Though I'm wondering if Sessionsrv and Originsrv will still be periodically pinging the router, and the issue is that the router is rejecting those requests...

**Comment by nellshamrell** [comment]
New idea:

Even after the router is restarted, Sessionsrv and Originsrv will still be sending it a heartbeat packet to make sure it is still there.  Perhaps we should add the ability for the Router to re-register services when it receives a heartbeat from it if it is not aware of that service.

**Comment by raskchanky** [comment]
@nellshamrell From the noodling I did on this last Friday I couldn't tell that the heartbeats were actually working, or if they are, they're not logging it.  If you start up a full builder cluster, you'll notice that builder-worker is the only service that is consistently heartbeating in the logs.  It's possible the other services are heartbeating and just not logging it, but I stopped my investigation with the question of whether heartbeats are even working or not for most services.

**Comment by raskchanky** [comment]
@nellshamrell I also didn't notice where the router ever uses the heartbeat information to remove services from its internal map, which it presumably should?

**Comment by nellshamrell** [comment]
@raskchanky - agreed, adding in heart beat functionality to originsrv and sessionsrv might be the first step.

**Comment by nellshamrell** [comment]
Notes from discussing this with @reset and @raskchanky last week:

Networked servers cannot ask each other if they die - if they do that, you create inversion of way data is supposed to flow and network congestion. 
- will eventually have servers that cannot spin up

Instead, try to always have consistent amount of traffic.

One way to have consistency is to have a heart beat from server initiating a connection (not the listener - the one initiating the connection)
- make connection on connect - send some data
- have handshake - send data to listener
- initial connection handshake
* server make connection to listener
* command port is open
* listener asks "what is your server registration?"
* server making the connection - first message "this is why I am ready"
* listener registers connecting server in its internal map
* currently, listener never drops servers from its internal map (except on reboot)

* need to implement loop on listener and connector
* listener - keep timer for every server registered with it and the last time it heard from it
* listener - tick through normal loop
  - every tick through - needs to determine if needs to tick because hasn't heard from server recently and check to see if it has, or to schedule work
  - certain number that server does not talk to listener - typically 35 seconds
* listener needs to increment timer every time it receives a heart beat - death count, if too long without heartbeat, drop server from internal map

* connector - schedule heartbeats every 35 seconds and reach out to router

Might need to also add to router
* in heartbeat, also sends what shards we care about as part of payload
* or router asks for registration when pinged by a server it does not have registration of (can cause intense traffic)
* suggested to put it in the heartbeat
* heartbeat sends registration for both initial registration and for heartbeat

**Comment by nellshamrell** [comment]
Breaking this down a bit more:

Add a loop to send a heartbeat registration message every 35 seconds (add to each builder application server)
- [ ] originsrv
- [ ] sessionsrv
- [ ] jobsrv
- [ ] scheduler

Add functionality to builder-router
- [ ] keep track of last time it has received a heartbeat from each builder application server in the internal servers map
- [ ] when router has not heard a heartbeat from a builder application server for 35 seconds, remove that server from the internal servers map
