### ISSUE TITLE
[builder] [web-ui] Builder search fails when you include a `/` character

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2440]
Searching packages on https://bldr.habitat.sh/#/pkgs/core e.g. fails if you type a `/` character, which is pretty normal since that's the character we use to separate `origin` and `package name`. 

Reproduce: 
1. Go to https://bldr.habitat.sh/#/pkgs/core
2. Type `core/`
3. Result is `No packages found. Error: Failed to fetch`

**Comment by cnunciato** [comment]
What's happening now is that when the search is for `core/foo`, the client sends a request to:

```
/v1/depot/pkgs/search/core/foo?range=0&distinct=true
```

.. which is matching against the the wrong route on the server, so we end up calling `list_packages` with an ident of `search/core/foo` instead of `search_packages` with `core/foo`.

The client should instead encode that string as an URL-encoded query param:

```
/v1/depot/pkgs/search/core%2Ffoo?range=0&distinct=true
```

.. and the server should decode it and use the slash in the query by ident, which should work. I can handle the first part, but I'll need a little hand-holding for the second.
