### ISSUE TITLE
Hook-only config updates do not restart services

### ISSUE THREAD

**Issue by sethvargo** [habitat-sh/habitat#2448]
- Mac OS 10.12

Given a plan that _only_ has a hook, but that hook has dynamic configuration, Habitat will rewrite the hook, but **will not** restart the service.

Example hook:

```sh
#!/bin/sh

exec http-echo \
  -listen="{{sys.ip}}:{{cfg.port}}" \
  -text="{{cfg.text}}" \
  2>&1
```

In this case, the service listens on `cfg.port` and renders `cfg.text`. When a configuration change is pushed:

```
$ hab config apply http-echo.default 2 <<< "port = 1234"
```

The configuration is changed (the hook actually changes on disk - verified by attaching to the container), but the service is not restarted. As a result, the service is now listening on the old port, but _new_ services would listen on the new port. Additionally, binding would fail, since it would bind to the old port.

As a workaround, creating a config file that depends on any configuration option triggers the service restart.

/cc @adamhjk

**Comment by brentm5** [comment]
As another workaround which I found easier (but is essentially the same thing), just symlink the hook you want to trigger a reload into the habitat configs directory. Makes keeping track of changes easier as you don't have two files to manage.

**Comment by christophermaier** [comment]
I did some digging and found out what's going on here.

[CfgRenderer::compile](https://github.com/habitat-sh/habitat/blob/bbe54c5097e257e3942ab4943b9e0b52b25a9f50/components/sup/src/manager/service/config.rs#L260-L261) returns false if any of the configuration templates get changed. However, it defaults to `false` before iterating; if there's nothing to iterate over (i.e., no configuration files!) then this will always return `false`.

This combines with [this code](https://github.com/habitat-sh/habitat/blob/bbe54c5097e257e3942ab4943b9e0b52b25a9f50/components/sup/src/manager/service/mod.rs#L372-L379) to produce the problem.   If there's new configuration being gossiped around, we *always* recompile the hooks, but we only signal a need for reconfiguration if any configuration templates change. As we have seen, if there are no configuration templates, then this will always be false, we'll never restart the service, even though hooks may have changed.

Since we currently have no idea when hooks change, one solution would be to equip hook recompilation with the same [change-awareness that CfgRenderer::compile has](https://github.com/habitat-sh/habitat/blob/e9308bcd25280b3fd2a3aa143fa0f1536224a387/components/sup/src/manager/service/config.rs#L255-L301) (e.g. add some checksum-and-compare code around [this code in Hook::compile](https://github.com/habitat-sh/habitat/blob/bbe54c5097e257e3942ab4943b9e0b52b25a9f50/components/sup/src/manager/service/hooks.rs#L94)). `Hook::compile` could then return `Result(bool)` instead of `Result(())` to indicate whether there was a change or not. Then we can take the appropriate action when hooks or config files change. We don't want to conflate "reconfigure" and "restart", though. If any hooks change, we should restart, regardless of whether any configuration changes or not (e.g., if you've got config changes and a reconfigure hook, but also have hook changes, you restart and pick up the changes to both.) If you've only got config changes, then you can reconfigure (or restart, as determined by the package's hooks).

**Comment by christophermaier** [comment]
This same issue also manifests when config files are present, but aren't interpolating the variables that hooks are. 

As a concrete example, the `core/vault` plan has a `dev.mode` config value that is interpolated in its [run hook](https://github.com/habitat-sh/core-plans/blob/3cc3397a5bd02f6af2201ca9f34dfb5256a25df1/vault/hooks/run#L5), but not its [sole configuration file](https://github.com/habitat-sh/core-plans/blob/3cc3397a5bd02f6af2201ca9f34dfb5256a25df1/vault/config/settings.hcl). If you change the value of `dev.mode`, your run hook will change, but your configuration file will not, and (due to the aforementioned code) Habitat will not end up restarting the service.

**Comment by christophermaier** [comment]
FYI: we'll be introducing some additional integration testing foundational code with this feature
