### ISSUE TITLE
[builder ux] failed builds don't show up in the builds page

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2573]
Currently, we are only seeing successful builds show up on the builds page for a package.

When a new build kicks off, it shows the build output of the build in progress, but when the build completes, there is no way to see the build output of failed build through the UI.

**Comment by cnunciato** [comment]
So in digging into this, it looks like the view we designed, which lists running, failed and successful builds alongside one another, isn't possible, since we don't (yet) know what version a running build applies to. So instead, we're going to link off to a view that shows the full build history by origin and package name.
