### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2576]
I collect some ideas to improve the documentation in the slack channel #documentation here: 
https://habitat-sh.slack.com/messages/C1K8SSJEB/

**Comment by eeyun** [comment]
@ShalokShalom because we don't archive all of the channels in slack (we're on slack free tier for the project) these messages are  very likely to fall off our history. If you wouldn't mind, lets look at getting each of these opened as separate issues here in GitHub, that would be incredibly helpful.

Thank you!
