### ISSUE TITLE
[Documentation] Create one site about what an artifact is

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2586]
There is currently no page about what an artifact is, while it get mentioned several times: 
https://www.habitat.sh/docs/search/?q=artifact

**Comment by eeyun** [comment]
Since "artifacts" aren't a habitat specific term but more generically a software build/lifecycle term I don't know how much value there is in writing documentation that deep into the stack.

But, it might be good to have a link over to a page in wikipedia or perhaps linuxfromscratch that discusses generally the process toolchain for building software.

**Comment by ShalokShalom** [comment]
If i am new to Habitat and artifacts as well, is all got when i ask the documentation about artifacts nothing. If i google and find them on wikipedia, is still not quite sure, how they are related. 

Is there seriously no special thing to mention about your artifacts?

**Comment by davidwrede** [comment]
I have added a synonym set in our site search engine so that searching for artifact will pull up [package contents](https://www.habitat.sh/docs/reference/package-contents/) and the [Packages](https://www.habitat.sh/docs/concepts-packages/) conceptual topic.

**Comment by rsertelon** [comment]
Maybe this can be closed then? :)
