### ISSUE TITLE
Support scons and other build systems

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2642]
Currently is SCons not supported, like it seems: 

/hab/pkgs/core/hab-plan-build/0.24.1/20170522084013/bin/hab-plan-build: line 2412: make: command not found

So i guess this file expect make and just make? I just dont get yet, why SCons is it core even. 

Waf here looks also nice: https://github.com/waf-project/waf

And here is an overview about different build systems at all: 
https://bitbucket.org/scons/scons/wiki/SconsVsOtherBuildTools

Thanks a lot in advance

**Comment by eeyun** [comment]
The build toolchain is specific to your source code. The default callbacks use make because the majority of software projects use/are aware of the make toolchain. Like other things in habitat, this is 100% about the way you want to build. If your plan requires make you can depend upon `core/scons` in your `pkg_build_deps` and set your callbacks to use scons.

In regards to waf, it appears we don't have a `core/waf` package. If you'd like a `core/waf` package to be available you have a couple of options:
  * Write a `waf` package and open a PR against https://github.com/habitat-sh/core-plans
  * Open an issue against https://github.com/habitat-sh/core-plans

**Comment by ShalokShalom** [comment]
And how does this look like, when i "set my callbacks to use scons"?

I guess i can open an issue about that?

Like: [Documentation] How to use other build systems

**Comment by bdangit** [comment]
@ShalokShalom,

> when i "set my callbacks to use scons"?

You should review https://www.habitat.sh/docs/reference/plan-syntax/#callbacks

> **Callbacks**
> 
> When defining your plan, you have the flexibility to override the default behavior of Habitat in each part of the package building stage through a series of callbacks. _**To define a callback, simply create a shell function of the same name in your plan.sh file and then write your script.**_ If you do not want to use the default callback behavior, you must override the callback and return 0 in the function definition.

So something like:

```
do_build() {
  scons
}
```

Mileage might vary as you may need to add additional logic inside the that callback to make sure stuff is getting built probably.

**Comment by eeyun** [comment]
Yes @bdangit is correct here. It's not a separate system its just updating the build script to call `scons` instead of `make` if that is indeed what you need.

**Comment by ShalokShalom** [comment]
Ah, ok that is sweet. I thought it is something much more complicated, i know how to set callbacks in general already. Does this count for llvm also?

Just just set llvm somewhere in the plan.sh as compiler, yes? :)

**Comment by eeyun** [comment]
Yep!

**Comment by ShalokShalom** [comment]
Yeah i already tried that one. Set llvm in front of .configure, if i remember correctly or so. 
I am currently not on my notebook and will try that one, after that i open an documentation issue about it.

Thanks a lot dear
