### ISSUE TITLE
Butterfly error w/ ProtoBuf "unexpected wire type WireTypeLengthDelimited"

### ISSUE THREAD

**Issue by jtimberman** [habitat-sh/habitat#2671]
Hello,

* Platform: Ubuntu 16.04
* Application: `chef-es/omnitruck/900/20170511200109`
* Habitat: `hab 0.24.1/20170522083228`

Periodically, the service gets into a state where it crashes or otherwise won't restart, and throws the following error:

```
$ sudo hab sup run
hab-sup(MR): Supervisor Member-ID 68c0b662a63347ee8b6647aa5ee8ee2e
hab-sup(MR): Starting myorigin/myapp
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(ER)[src/error.rs:360:8]: Butterfly error: ProtoBuf Error: WireError("unexpected wire type WireTypeLengthDelimited")
```

@mwrock Asked that the next time this occurs that I capture the `/hab/sup/default/data` directory on the affected node(s). It is available here:

https://jtimberman.s3.amazonaws.com/omnitruck-hab-data.tar.gz

**Comment by fnichol** [comment]
Thanks for the data! We'll have something to look into now. There was a version-incompatible change in the wire level between 2 recent versions of the Supervisor (can't remember which ones at the moment) and the fix was to clear the data directory and restart the Supervisor.

**Comment by reset** [comment]
As @fnichol pointed out this is caused by an incompatible protocol change between versions of the Supervisor. It's our intent to allow backwards compatibility with the Supervisor protocol through at least major versions, this was just a slight oversight from some old code in the Supervisor.

To remediate you need to stop all supervisors, delete their data directory `/hab/sup/default/data` and start them back up. This will clear any config you've gossiped so you might want to record that and re-insert it before taking these steps.

Sorry for the inconvenience, it's not something we intend to repeat :)
