### ISSUE TITLE
Community Communications - Operational Status

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2695]
1. We should have a status page to communicate things like outages, maintenance windows, etc.
2. Investigate options for hosting page outside of hab - eg, statuspage.io
3. Investigate integration with Twitter
4. Investigate integration with ChatOps

**Comment by nellshamrell** [comment]
Status page.io seems like a good option.

1) They have a slack integration (I'm working on removing one of our current Slack integrations (we are at the limit for our Slack account) so I can test this out.
2) They also integrate with Twitter - you can authorize a twitter account with it and it will automatically tweet out status updates when you create them.

**Comment by nellshamrell** [comment]
This seems to work quite well - I've created a statuspage.io account and it successfully posts to our Slack (currently in a private channel, but we can easily switch to a public channel).

I propose we 
1) Add all Habitat team members too the statuspage.io account
2) Connect statuspage.io account to the Habitat twitter account
3) Document information on how to access the account, what to post, etc.

**Comment by tashimi** [comment]
Sounds great @nellshamrell!

**Comment by chefsalim** [comment]
Sounds good 👍

**Comment by reset** [comment]
@nellshamrell let's do it!

**Comment by nellshamrell** [comment]
Our statuspage.io account has been connected to our Twitter account and has been documented [here](https://github.com/habitat-sh/habitat/wiki/Incidents).

HOWEVER - I just realized that our status page is NOT public - in order to make it public we need to sign up for a statuspage.io plan, which for the number of team members we have would run us $99 a month (we could go down to two accounts with shared credentials for $29/month).

What are your thoughts on this?

**Comment by nellshamrell** [comment]
@reset got us set up with a paid plan - so this is now good to go!

**Comment by nellshamrell** [comment]
Just added an additional issue to add this to the navigation bar #2823

**Comment by nellshamrell** [comment]
Can we call this closed?
