### ISSUE TITLE
Monitoring breakage / Improvements

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2696]
1. Investigate why we are not seeing alerts in #operations slack channel 
2. Investigate / document what exactly is being currently monitored
3. Come up with a plan / proposal for improving the monitoring

**Comment by raskchanky** [comment]
1. I'm not 100% sure why we're not seeing alerts in the #operations slack channel.  All of the integrations appear to be correct.  Just for good measure, I deleted the Datadog slack integration and re-did it from scratch.

I also discovered that the Fastly integration was broken, which I redid and I think it's working now.  It's difficult to tell for sure.

2. We have 2 monitors in Datadog that we're currently alerting on: 5xx errors from Fastly and low memory.  The low memory monitor is not currently working, so I've deleted it.  From what I can tell, if you want Datadog to actively monitor the health of your infrastructure, you need to install the datadog-agent on each node.  From what I can tell, this is not something we're currently doing, but if we're going to continue using Datadog, it's probably worth doing.

There is also a dashboard that monitors the following items:
* avg fastly requests
* HTTP responses in the 2xx, 4xx and 5xx range as seen from fastly
* avg pingdom response time
* lots of various host related metrics, all of which are non-functional because the agent isn't installed on the depot nodes.

**Comment by raskchanky** [comment]
Reflecting on this now, I think the reason we weren't seeing alerts in the #operations slack channel is because our monitor that does the alerting was tied to the fastly integration, which was broken.  Now that the fastly integration works again, we should start seeing alerts again.

**Comment by raskchanky** [comment]
My conversation with Paul Mooring left me with a few takeaways as to how we can improve our monitoring:

* We need insight into the basic machine metrics on each node - things like free memory, disk space, cpu usage.  The hab plan that I wrote for the datadog agent should help with this.
* We need to establish KPIs for each service and baseline ranges for those KPIs and then alert when the values go outside our defined ranges.
* We should have a way of telling when a specific service is in trouble vs waiting to see when the API throws a 500 - it sounds like the planned Sumo Logic integration will definitely help with this.
* He felt that Datadog was fine for now but would grow to be prohibitively expensive once our infrastructure reached a certain size.
