### ISSUE TITLE
Run habitat as windows service

### ISSUE THREAD

**Issue by guskovd** [habitat-sh/habitat#2766]
It would be great if the process hab-sup.exe "understands" that it can be a windows service
--
Now I have to use utilities like nssm ( https://nssm.cc/ ) to run the supervisor at the start of windows

**Comment by mwrock** [comment]
Thanks filing this. This is pretty high on our windows priority list. Definitely a must have for production scenarios!

**Comment by mwrock** [comment]
Just for technical accuracy, it is likely that hab-launcher will be the service target process but in practice that brings hab-sup into the service control area as well.

**Comment by mwrock** [comment]
I have done a bunch of testing of various scenarios around running habitat as a windows service. I've run it as Local System, Network Service, and a custom admin user. I've run services that run under the identity of the service and also under their own account so that the service needs to create a process with a separate account.

Local System and Network Service had issues because the habitat SID lookup broke using a machine account. A fix is in #3839. Network Service simply will not work and I think that is acceptable. It does not have sufficient privileges to terminate arbitrary processes, which is often necessary when killing the process tree of a service that will not die gracefully. According to Microsoft's docs, the Network Service has minimum privileges on the local computer. I think for what our supervisor is designed to do, thats simply not sufficient and it is acceptable to call that out as an unsupported scenario.

A few things need to happen to finish this off:

- [ ] Implement `hab term` for windows to be called when stopping the windows service
- [ ] Explore the peer watch file as a way to have a starting service attach to a ring. I'm not sure that would work but we need to support joining peers obviously
- [ ] Create a Service harness that implements a windows service loop, handle service events and redirect logging. We could do this in rust using FFI but might be able to do it in .net which would be MUCH simpler. It just needs to be portable back to .net 2.0 in order to support a default 2008R2 install.

**Comment by mwrock** [comment]
Looking more closely at what we'd need to do for a windows term, we'd either need to do something "whacky" (or zaney) or get the IPC stuff going. As a shortcut, we can have our service stop handler attach to  the launcher's console and send it a ctrl+c and then detach. I just tried this in my dummy C# harness and that works perfectly.

**Comment by mwrock** [comment]
From what I can tell using the peer_watcher file should work.

I just retargeted my C# test harness to .net 2 and it compiles just fine. A "real" service harness really won't be much more complex to require a higher version. This means we can port it to any version of windows we support. I think we can keep it in its own repo and package as a hab package. Then add a `hab run --as-service` (or something like that) which will:
* check if a service is installed and start it if it is not running
* If not installed, puill down the latest package
* call `hab pkg exec core/hab-win-service install` which will run a light weight packaged installer that installs the service in the windows service manager

**Comment by mwrock** [comment]
The windows service is now self contained at https://github.com/habitat-sh/windows-service. The readme should explain how it behaves and can be installed.

Before this can be "publicized" the following needs to happen:

- [ ] Issue a new hab client launch that contains the fix for running under `Local System`
- [ ] Upload and promote the windows-service package

**Comment by tashimi** [comment]
Added follow up steps to new card #4345, closing this one.
