### ISSUE TITLE
Add Link to Status Page to Habitat Navigation menu

### ISSUE THREAD

**Issue by nellshamrell** [habitat-sh/habitat#2823]
It should link to https://status.habitat.sh

**Comment by ryankeairns** [comment]
@apriofrost thoughts on where we should place this statuspage.io link? Footer perhaps?

This is for viewing the status of habitat services and often comes into play when our site/app is down... in other words, customers can still get status update info at this location since its separate from our actual site.

**Comment by tashimi** [comment]
We should definitely have habitat.sh/status link to it, and status.habitat.sh, as those are URLs users will sometimes try directly.

**Comment by apriofrost** [comment]
@ryankeairns Yes! I think we can add a 'Status' link at the footer under 'Support'. We may also consider adding the link under 'Quick Link' at Depot dashboard.

**Comment by miketheman** [comment]
Dropping a note here - this doesn't appear to have been implemented, and I was looking for something like this today while the builder/cdn is experiencing more than a blip.
