### ISSUE TITLE
Studio public/private key handling can fail builds

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2875]
Currently, the way the studio is downloading secret and public keys can get us into a situation where  different revisions of a secret key and public key get downloaded and cached, and when it comes time to sign a build, a valid key pair cannot be found, and thus the build fails.

We should optimize the path to always try and download the matching public key for a private key that first gets downloaded.

Example error:
 hab-studio: Destroying Studio at /hab/svc/builder-worker/data/776963474424487936/studio (unknown)
   hab-studio: Creating Studio at /mnt/hab/svc/builder-worker/data/776963474424487936/studio (default)
   hab-studio: Importing core secret origin key
» Importing origin key from standard input
★ Imported secret origin key core-20160612031944.
» Installing core/hab-backline from channel 'stable'
☛ Verifying core/hab-backline/0.26.0-dev/20170707231829
↓ Downloading core-20160810182414 public

....

» Signing testapp_blake2bsums
☛ Signing testapp_blake2bsums with core-20160810182414 to create /hab/pkgs/core/testapp/0.1.0/20170804225751/FILES
✗✗✗
✗✗✗ Crypto error: Secret key is required but not present for core-20160810182414
✗✗✗
   testapp: Build time: 0m0s
   testapp: Exiting on error

**Comment by chefsalim** [comment]
NOTE: We worked around this by updating both prod and acc to the later version of the private keys.

**Comment by fnichol** [comment]
I think this is due to a bug in the core component's key loading logic which `hab pkg sign` uses. In this case it looks like we're copying in core's *secret* key circa 2016-06-06 but then another package downloaded core's *public* key circa 2016-08-04 which is newer. Then when `hab pkg sign` went to load the latest core keypair, it found a newer revision (the 2016-08-04) but which had the public but not the secret key.

What we should do is ask for the latest *secret* key when going to sign and not the latest of either public or secret. I thought we fixed this about a month ago--or possibly someone else found this bug and we need to fix it in either case.

**Comment by elliott-davis** [comment]
Please re-open if this issue still happens
