### ISSUE TITLE
Create new "Getting Started" docs

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2879]
Create an outline for "getting started" docs for an application developer. 

Step by step guide for a new user for how to: 
- Write your first plan 
- Add basic configuration/lifecycle hooks, with links to more information
- Wrap nginx 
- Add a db as a service using optional binds, or a clustered database using required binds
- Practical advice to get off the ground

**Comment by apriofrost** [comment]
Hi @tashimi . As @davidwrede and I were discussing the outline, I'm wondering what the purpose is for including 'wrap nginx' here? My understanding is that this guide is a generic medium-level guide for all kinds of apps. Were you suggesting that it includes a link to the 'how to use core/nginx' blog/guide that Chris N is working on?

**Comment by tashimi** [comment]
No, I want to use the content Chris is writing and provide it as documentation. It's very common for developers to want to use nginx for an application. That content belongs as reference in a how to get started flow.

**Comment by apriofrost** [comment]
Review the outline here: https://docs.google.com/document/d/1YnaDh4DSy-NR1Ec4bWWsIPgjo-4bbuXv6-4Aywsj_78/edit#

**Comment by ShalokShalom** [comment]
First, Habitat seems still to castrate itself, by purely focusing on services, instead of putting desktop apps also into consideration. Secondly, if you seriously like to overhaul the beginner's guide, look at some of the issues, into which I run as such one: https://github.com/habitat-sh/habitat/issues?q=is%3Aopen+is%3Aissue+author%3AShalokShalom+label%3AA-documentation

**Comment by reset** [comment]
@ShalokShalom we appreciate the documentation issues you've opened and they're part of our evaluation of what we need to do to overall our new user experience.

In regards to your first comment, Habitat is a quickly evolving piece of software that draws on a lot of software that you may already be familiar with. We have a lot of ground to cover and our current focus is not on building a replacement user land for general use. It's great that you are passionate in this area, but you will need to tackle this as a community effort for the time being.

**Comment by adamhjk** [comment]
@ShalokShalom It's all community - but most of use have the service use-case, and not the desktop one. So we choose to put our time there, rather than in desktop applications. We're happy to see the desktop applications evolve, but I (for one) am not going to be the person pushing that evolution.

Second, I know english isn't your first language - using the word 'castrate' above makes your post sound aggressively hostile. In particular, it's followed by "if you seriously like to overhaul the beginners guide, look at some of the open issues", which simultaneously demeans the intent of the original contributor and requests that others volunteer their time to work on whats most important to you. Neither of those things are acceptable behavior in the future. Same paragraph, re-written, that wouldn't trigger this warning from me:

"I am worried that habitat is limiting its potential by focusing on services and not also on desktop applications. Also, I opened some issues for things I ran into as a beginner - you might find some of them useful in rebuilding the getting started docs."

**Comment by ShalokShalom** [comment]
How can anybody use Habitat on the desktop, when it's unsuitable?

That is circular reasoning.
> most of use have the service use-case, and not the desktop one.

You can say Habitat is not on the desktop since Habitat is not on the desktop.

How do you know, how much interest is into this topic? How will it be received? 

This is also intended to be mean towards the "beginners guide" since the Nginx chapter seems to suggest, that the only purpose is the packaging of service apps.

> which simultaneously demeans the intent of the original contributor and requests that others volunteer their time to work on whats most important to you

I post those issues about 2 months ago. No answer. Not on a single one. 
Then, somebody else posts the same stuff (essentially) and gets a proper answer instantly. 

How would you feel?

This expands to all the other issues I ever posted here, the very most get closed while they are unsolved for me, without any query. 

Same thing here, 2 posts of mine, exactly tackling this issue, collected by the community in Slack channel, one issue got closed in favor for the other one, while that one contains complete different suggestions in my sense: https://github.com/habitat-sh/habitat/issues/2882

So I had to rename the other one, which result in a total mess. 
When you look at those issues deeply, will you see that it gets tricky to participate, IMHO.

Thanks a lot

**Comment by adamhjk** [comment]
@ShalokShalom open source communities exist because their members exist. I see that you care deeply about desktop software, and have a vision of how habitat can help solve your problems. I, Adam Jacob, do not have that problem, and so the work I do on habitat isn't pointed in that direction. It doesn't mean I don't want to support you in exploring that direction, and in figuring out how to make habitat suitable for your use case. I'm not saying it's not a big deal, or not something worth having. I am saying that, for me, it's not the place I'm spending my time, nor will I be in the near term future. The same is true for a lot of other folks who are actively contributing to habitat. (In some cases because they work for me.)

In terms of the getting started guide, I think it is reasonable that you have to start somewhere, and the place that is the most fleshed out is the service layer. It's not crazy that we would use that as our example.

In regards to filing issues that go unanswered, I'm sorry for your frustration. I will point out that habitat is a community, which means that the people involved in moving a given aspect of the project forward *are those people themselves.* That you file a reasonable issue doesn't mean that it will become the priority for others. In the same way that, because I care about services more than desktop applications, I can't expect that you would suddenly work on the things that are most passionate to me.

One thing I am sure you are experiencing is that there is a set of core team members, and that core team is more tightly coordinated than the rest of the community is. So the fact that @tashimi opened this issue, and that the core team is focusing on it, means that they are precisely dealing with your issues now. I want to be clear - this means that, a team of people, who you do not pay, who have open sourced everything they have done for the last two years, is about to tackle *the specific problem you are most upset about*. They may not tackle it the way you would want, but associating your issues with it is an attempt to keep the system clean. The intent here is to solve the problems.

We want to be a healthy, thriving open source project. That means listening and working with all sorts of folks from all over the world. I'm excited to work with you. But simply advocating for why your point of view is more important than others, or pointing out why when other people pick up things you care about, they should've done it months before - this is not the way we get there.

Best,
Adam

**Comment by ShalokShalom** [comment]
You simply misunderstand me here until. 

I open an issue. Nothing happens. 
Somebody else opens an issue. Things move on. 

> That you file a reasonable issue doesn't mean that it will become the priority for others.

And I never state or expected that. 

I just thought my word counts so much as that one from others. 

So, I see two options: 1) Its about the time. 2) It's about the persons.

You seriously can't tell me, that you feel comfortable when somebody - or a group even - ignore you and some months later get exactly this issue raised up by somebody else and voila: all works. 

So, I am not pointing out that my point of view is more important as others.

I am pointing out - and there is evidence - that your team treats me sometimes like my point of view counts nothing. 

While you see this for sure differently, feels Habitat to me like an illusionary open source project, which is open on the surface and closed in the core. 

Which is, of course, your free decision and that one of everybody else as well. 

I just like to mention how this attitude feels like to a user.

Thanks a lot for all your input.

**Comment by adamhjk** [comment]
I am confused. You opened an issue that is being bundled together, with people *who are not you* about to work on it. Yes, people are now working on it, not because you said it was a problem, but because *they decided they were going to tackle that problem now*.  

Did you send a pull request that's been ignored to update the documentation? Did it get rejected? 
Your suggestions count as much as anyone else's suggestions count. What they don't do is set the priority of other people. There are now others, who are both reading your issue, triaging it, linking it to this issue, and starting the work to fix it. That seems awesome to me.

As for how I feel when something I raised in the past becomes a priority, and then gets solved by people who are not me, I feel *fabulous*. Literally great. Because it means I don't need to do that work anymore. And if I feel like they missed something I thought was important, then I would collaborate with them on its resolution, because I'm passionate about what they are passionate about.

There is nothing illusory about habitat as an open source project, as far as I can tell, other than you being upset that the things you want us to do are not what we are doing, or when we are doing them. Which, I see your point - that must be frustrating. But it's life.

**Comment by ShalokShalom** [comment]
This documentation didn't exist at the point when wrote the issue, which is the reason why I wrote an issue about that, rather than a pull request since anything else is again circular reasoning.

How to write documentation about something that is new to you?

If you think, that it means zero work for me to write those bug reports then think again and consider that the very most users don't do this, exactly because of such treatments. 

I invest energy into this project which then gets blocked and once I mention this, is your argument that I prefer it when others do my job. Circular reasoning #4

It is far more easy to simply use your product, instead to struggle here with you in order to be allowed to contribute and this is a huge reason why people do not contribute.

I see a lot potential in this project, obviously on the desktop even more as the most others here do,  you can take as a compliment.

You think the current state is perfect like it is since it seems perfect for you and there is also a name for the issue behind this: Organizational blindness.

Good luck 

@apriofrost @tashimi @adamhjk @reset  Thanks a lot

**Comment by davidwrede** [comment]
#3108 Captures this basic flow for Ruby web app developers.
