### ISSUE TITLE
Support for Private GitHub Repos

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#2888]
Builder-API, Builder-Web, and Builder-Worker can currently only read data from public GitHub repositories. In order to extend support for private builds, we will need to add support for private GitHub repositories

**Comment by mwrock** [comment]
Where is builder-API and builder-web accessing repos on github? I know builder-worker would do this via building plans that access code from GH. Or maybe api/web are not currently accessing GH and this is simply in preperation of that?

**Comment by scotthain** [comment]
I think part of this is linked to what @fnichol described here https://github.com/habitat-sh/habitat/issues/3097

I could on the wrong track here (or just not understanding all the parts) but here's my concept of what's happening and what we might be able to do.

Currently, when a job creation request hits the API, the API auths to github and dispatches info to the jobsvc. When the worker connects to the jobsvc, it only gets the info stored in here https://github.com/habitat-sh/habitat/blob/master/components/builder-jobsrv/src/server/handlers.rs#L28. This all works fine when running against the `core` origin, since the auth there is explicitly enabled and passed in the config files (and set up previously out of band through the github ux) This auth happens here btw: (https://github.com/habitat-sh/habitat/blob/master/components/builder-api/src/http/handlers.rs#L74)

It seems like there needs to be a few things to make this work, with a few slightly different use cases.
- `core` access (already in place)
- public repo access with arbitrary credentials
- private repo access with arbitrary credentials

It seems appropriate to be able to use an access token previously created for depot access (which most folks already should have). The problem then becomes enabling the API to see that token, and also how the worker gets the token, as it will need to use it to do the actual clone/etc. If I understand correctly the worker currently gets this directly from configuration files. Without overengineering things, I'm thinking there may need to be some method for the worker to authorize itself with the API so it is 'trusted' and so it can get the secrets it needs to do the work.

That's a super long-winded reply, hopefully mostly correct (it's been a few days since I ran some tests through this code).

**Comment by mwrock** [comment]
Yeah it looks like the end user experience into the parts that grab repo artifacts has not been built out (its close) so browsing the habitat site from master code was not showing me where it was accessed. After talking with @reset and doing some code spelunking I see the affected areas:

* github.rs which leverages the GH rest API to download a repo's plan file.
* the worker which clone's a repo using rust's libgit2 bindings

I need to do some POCing of accessing private repos from these 2 entry points. Its possible that the first item mentioned above will happen "for free" because I think we use the GH bearer token of the authenticated user and as long as the user creating/editing a project is authorized, I think the rest invokations will work. I need to sanity check that. Its also possible I suppose that we may want to allow users w/o GH repo access to still edit a project.

**Comment by mwrock** [comment]
We'll need to store a personal access token with a project that accesses a private repo. We can make this an optional field since public repos will not need this token. When making REST api calls and this token exists, we will use it as the bearer token. When cloning a repo and this token exists, we will insert `<token>@` before the host name in the clone url.
