### ISSUE TITLE
Document which scaffoldings can be passed to hab plan init -s

### ISSUE THREAD

**Issue by nellshamrell** [habitat-sh/habitat#3095]
I had to spelunk through the code in order to find out which scaffoldings can be passed to ths $hab plan init -s command.  [I did find it](https://github.com/habitat-sh/habitat/blob/master/components/hab/src/scaffolding.rs#L31), but it would be a far better user experience to have this documented in an easily accessible place.

**Comment by tashimi** [comment]
I'm a little conflicted about this, because not all of the scaffoldings listed in the code are ones that we consider production ready. We have documented the ones we consider production ready here: https://www.habitat.sh/docs/concepts-scaffolding/

Perhaps the best thing to do here is: 
- add the cli command to the current scaffolding doc 
- add a cli command to `hab plan init -s --list` that returns a list of scaffoldings

@reset also wants to add a cli command to get the list of all available `core` packages (or other whitelisted packages) and all available exporters. 

I will do the first item, and the other two are a bit further out (but hopefully not too far out!) and will be nice cli upgrades.

**Comment by tashimi** [comment]
See #3095

**Comment by tashimi** [comment]
To do: once #3162 is merged, add scaffolding type information, export type information,

**Comment by tashimi** [comment]
Closed by #3188
