### ISSUE TITLE
Running `hab service start` causes an internal error 'entered unreachable code'

### ISSUE THREAD

**Issue by mivok** [habitat-sh/habitat#3130]
```
vagrant@vagrant:~$ hab service start
thread 'main' panicked at 'internal error: entered unreachable code', src/main.rs:194:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
vagrant@vagrant:~$ RUST_LOG=debug RUST_BACKTRACE=1 hab service start
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:hab: clap cli args: ["hab", "service", "start"]
DEBUG:hab: remaining cli args: []
thread 'main' panicked at 'internal error: entered unreachable code', src/main.rs:194:21
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
vagrant@vagrant:~$ hab --version
hab 0.31.0/20170907232530
vagrant@vagrant:~$ env | grep HAB
vagrant@vagrant:~$ # (no habitat specific environment variables)
```

- OS - Ubuntu 16.04 in vagrant. I also tried in a habitat studio run from OSX
- Habitat version: hab 0.31.0/20170907232530

Note: this only happens if you type `hab service start`, `hab svc` and `hab sup` variants are fine.

**Comment by christophermaier** [comment]
@mivok Thanks for finding this. Judging by the [offending code](https://github.com/habitat-sh/habitat/blob/578281fb7da03391fce9cfceeb7bc580ce802449/components/hab/src/main.rs#L186-L195) this is indeed a bug.

**Comment by jamessewell** [comment]
Issue seems to occur when calling with an argument which is aliased to another sub-command with an alias for the entered sub-command

ie: `hab service start`

-> service is an alias for svc
-> svc start is an alias to sup start

**Comment by jamessewell** [comment]
No idea how to fix, but I think [this match](https://github.com/habitat-sh/habitat/blob/578281fb7da03391fce9cfceeb7bc580ce802449/components/hab/src/main.rs#L634-L637) is only explicitly matching `svc`, not `svc` and all the aliases

**Comment by rsertelon** [comment]
Method `exec_subcommand_if_called` [here](https://github.com/habitat-sh/habitat/blob/578281fb7da03391fce9cfceeb7bc580ce802449/components/hab/src/main.rs#L623) differs from how the other commands are handled.

Is there any reason this has been done like this? Shouldn't it be added to `start` [here](https://github.com/habitat-sh/habitat/blob/578281fb7da03391fce9cfceeb7bc580ce802449/components/hab/src/main.rs#L84) as the other commands?

**Comment by rsertelon** [comment]
@baumanj I see you assigned yourself to this issue, I was looking at a possible solution. Do you plan on doing it? :)

**Comment by baumanj** [comment]
Looks to me like a general problem with [`exec_subcommand_if_called`](https://github.com/habitat-sh/habitat/blob/6c5a1d232ac251adbe2bc72fff83992837c3b6f4/components/hab/src/main.rs#L647) not respecting aliases since it's called [_before_ CLAP processes the args](https://github.com/habitat-sh/habitat/blob/master/components/hab/src/main.rs#L85-L89):
```rust
    exec_subcommand_if_called(ui)?;

    let (args, remaining_args) = raw_parse_args();
    debug!("clap cli args: {:?}", &args);
    debug!("remaining cli args: {:?}", &remaining_args);
```

I'll try to see if the `exec_subcommand_if_called` code can be restructured to use the CLAP output and thereby respect all the aliases.

**Comment by baumanj** [comment]
Per discussion in [the PR](https://github.com/habitat-sh/habitat/pull/4024#pullrequestreview-76209582), this needs a slightly different approach. Making a `hab` → `hab-sup` dependency breaks the Mac build. Moved back to "In Analysis" while we wait for input from @fnichol and/or @reset.

**Comment by baumanj** [comment]
After chatting with @fnichol, I'm going to take a look at separating out the CLI config (which is really more data than code) into the YAML format provided by CLAP. This could be beneficial for internationalization down the road. However, If the YAML approach isn't modular enough, we can use rust but add a separate crate so we can have

`hab` → `cli` ← `hab-sup`

instead of

`hab` → `hab-sup`

One thing to be aware of is that we can't really avoid having stale usage *information* if executing the aliased command will download a different version of the binary that implements it, but we should be careful that we don't do the actual parsing of the args (aside from `--help`) in the command that does the dispatching.

For example, `hab svc start …` dispatches to `hab-sup start …`. If the version of the CLI config known to `hab` doesn't contain arguments that will be valid in not yet downloaded version of `hab-sup`, we have to be careful to allow that version of `hab-sup` to be downloaded and parse the args itself instead of generating an error from `hab`. So, `hab svc start --help` may not display documentation for `--cool-new-flag` but it should still allow dispatching to `hab-sup start --cool-new-flag`.

**Comment by christophermaier** [comment]
This no longer happens with the 0.56.0 release
