### ISSUE TITLE
Display hooks in execution order and then enhance descriptions

### ISSUE THREAD

**Issue by burtlo** [habitat-sh/habitat#3166]
The hooks references are displayed in alphabetical order. It would be useful to see the most common flows that would trigger these hooks and the order that they execute (e.g. start/restart/reconfigure). Focusing on describing the flow of events up top in those common scenarios and then providing more detailed descriptions for each hook below.

A reference to the runtime settings (https://www.habitat.sh/docs/reference/runtime-settings/) would be helpful.

**Comment by tashimi** [comment]
Ok, I'm going to attempt to approach this in the following way: 
* [ ] Add a reference to runtime settings 
* [ ] Review order of hooks documented and put it in lifecycle flow instead 
* [ ] Either add examples to this doc or write an advanced doc with real examples 
* [ ]  Write a blog about how the postgres plan uses hooks since this is the most complex example of a plan atm (or possibly a builder plan)

**Comment by tashimi** [comment]
Partially addressed by #3195
