### ISSUE TITLE
Refactor accounts and sessions

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#3216]
There are some problems with the way our accounts and sessions are currently setup. Both accounts and sessions shard based on the account name, which in practice, is the GH user name. This is problematic for sessions because in the two places in the codebase where we go to retrieve a session, [here](https://github.com/habitat-sh/habitat/blob/master/components/builder-http-gateway/src/http/helpers.rs#L317) and [here](https://github.com/habitat-sh/habitat/blob/master/components/builder-http-gateway/src/http/middleware.rs#L125), we don't have the GH user name. All we have is the GH auth token. Since the account name is always empty in the `SessionGet` request, the lookup always fails. As a result, we don't actually use our stored sessions at all. Instead, we auth with GH on every authenticated API request. This is not teneble for even the very short term future, as not only is this significantly slower than it needs to be, but once we have actual users and real traffic, GH will rate limit us very quickly and everything will grind to a halt.

I tried to fix this by changing the sharding key for sessions to be the GH token, since that's what we actually use to lookup sessions. That worked beautifully for sessions themselves, as they got re-used and we no longer pinged GH for every authenticated API request. However, the way that accounts and sessions are implemented right now, both accounts and sessions need to be on the same shard, since we have queries that join information from both tables (GH user name and email from accounts, auth token, permissions, and miscellany from sessions). This also introduced the problem that everyone's account got re-created on a new shard, which resulted in a brand new account id, which broke things like the origin_members table, that maps origins to accounts. I wrote some code that automatically migrated accounts over to the new shard so everyone could keep their same account id.

That presents a new problem though because now that accounts are on the same shard that sessions are, we can't look accounts up. Since accounts are sharded on account name, the `AccountGet` message will go to the shard for that account name, which is not where the account is any more. For that matter, we have a message right now to lookup accounts by id (used only by builder-admin) and I can't imagine that it actually works because it's likely looking on the wrong shard.

So the fundamental problem here is the way we have things setup in postgres, accounts and sessions want to be sharded on different keys, yet they want to be queried together, because each one holds half of the relevant information that we care about.

[Here is a branch](https://github.com/habitat-sh/habitat/commit/e908311d24bef43db6f67c8d0d399d71713c7aa7) that has the (currently not fully working) code that I wrote in an attempt to solve this problem.

**Comment by raskchanky** [comment]
I talked this over with @chefsalim and our initial thought is to just not shard sessionsrv, and put everything on shard_0.  That would solve our problems here.

**Comment by chefsalim** [comment]
Not sharding will solve another thorny issue - auditing.  We save the session ids with package uploads, but also want to easily map the session ids to the username and other account info.  Similar auditing will be needed/added for the job scheduler._

**Comment by adamhjk** [comment]
We should be very, very wary of deciding not to shard. The availability design of the build service is one of partial availability through sharding - each component you decide to shard is one where you suddenly have decided to build a global bottleneck, and global failure model, which has lots of repercussions (for example, you then tend to try and get your availability back through more complex data storage layers.)

What you need is a way to look up accounts by session id, and vice-versa. When one is created, you need to issue an RPC call to update the relationship in the other storage system. I can talk more about this later today.

**Comment by mwrock** [comment]
When I first read this issue I had a similar thought to Adam's argument. Especially since sessions will get quite large over time, it becomes an ideal candidate for sharding. To solve issues where we need a cross shard read only view, we may need to denormalize data and duplicate from one table to another thats fairly simple for immutable data like username. Another option may be to maintain an index either in an unsharded table or in something like redis that the app can use to query the right shard for detail. That works well when you just need to display joined data in a single record detail view and is less great when you need to list multiple records in one view.

**Comment by chefsalim** [comment]
Agreed, that is the tradeoff. I would argue in the short term we should make this tradeoff and comb back to take a deeper look at the shard availability design after Oct. Currently, we are running job server and scheduler also all on shard 0.

**Comment by raskchanky** [comment]
I think I see a path forward here that leaves the sharding intact, based on @adamhjk's suggestion.  If we store the account name with the sessions, then it's easy to retrieve what we need when we need it, and it shouldn't matter that accounts and sessions are stored in different shards.  We switch from calling a joined query to making an RPC call to get the info we need.

**Comment by chefsalim** [comment]
Hmm, unless I'm reading this flow wrong, it looks like we are getting the user name during the session create handling here https://github.com/habitat-sh/habitat/blob/master/components/builder-sessionsrv/src/server/handlers.rs#L145 - so when we try to find the session, if we don't have the user name in the message, we retrieve it from github via the token.  So maybe this is not as critical after all?

**Comment by raskchanky** [comment]
@chefsalim Right, we retrieve the name from GH when we try to create the session.  That was never an issue.  The issue is that we try to _find_ an existing session based on the GH user name, which we never have in advance.  We only have the token.  When we're unable to find an existing session based on the blank GH user name we're passing in, we create a new session (every time).  Then we look up the GH user name and store it.

**Comment by adamhjk** [comment]
@chefsalim in the case of the job server and the scheduler, they both make more sense as a non-sharded pool, because you won't get starvation when shards are imbalanced. In neither case did we decide to not shard them for expediency.

As to running a single database, I would encourage the team to consider that you likely need to deploy in a wider way before your release date, given that parallel availability is key to the system. You can set the threshold where you like, but it only will get harder (and be an outage, almost certainly.)

These are decisions that are hard to change, and that are core to the design of the system. Do the work now to get it right, and to spread the knowledge amongst yourselves about how to steward and extend the design.

**Comment by reset** [comment]
Hey everyone,

@adamhjk is correct - we made a concious choice to not shard JobSrv or ScheduleSrv because they are both singleton services. I originally sharded JobSrv because it was expediant to re-use what I had written and I wasn't sure about the guarantees of "fairness" that we should meet. It's clear now that both of these services need to remain a singleton and have a failover mechanism in the form of a hot standby.

I included sharding early in Builder's development to ensure that people kept it in mind from the beginning - it's much more difficult to shard after the fact in my experience. We're unbelievably close to the entire thing working and we shouldn't stop now.

I'm going to take care of the sharding in SessionSrv/OriginSrv and ensure all protocol messages are routed properly and all data is on the appropriate shard. I'm going to review all protocol messages and ensure their `route-key` is appropriate and, if not, I'll be creating a resharder tool which migrates entities from one shard to another.

I'll carefully code review once the improvements are made and ensure that we, as a team, have the knowledge to continue to support and grow the codebase even after the changes. We're almost there for real; I can see the light at the end of the tunnel for the first time in 2 years.

**Comment by chefsalim** [comment]
@raskchanky Thanks, your explanation makes perfect sense :)

@adamhjk @reset - I don't disagree with anything you are saying or the early design decisions, and certainly we can steward it forward. My points are basically : 1) we still don't have sharding fully deployed as envisioned (yep, we seem to be close), 2) even when deployed we are looking at sharding as a partial availability solution, 3) we continue to spend engineering time on it that could be spent elsewhere, 4) we still need and will have to deploy a non-sharding availability solution for the jobsrv and scheduler.  So, in my ideal world, for a mission critical service, I would rather have full availability (support 3 nines or better), and I'd rather have a solution that doesn't make me have to care about where exactly the data is when I want to access is. We don't have to change anything now, but I think we need to have some point where we retro this and maybe consider other improvements then.

**Comment by raskchanky** [comment]
Since we're on the subject of sharding, I'll like to throw in a link to an issue I made back at the beginning of August.

https://github.com/habitat-sh/habitat/issues/2884

I chatted with @christophermaier a bit before writing this issue up, but it seems worth mentioning now, because I'm not sure everyone's seen it and it's relevant to the issue of sharding.  I'll mention that I have no idea what a sharded PG looks like when it's running on multiple servers, and there seems to be very little documentation that describes it.  It's possible that my assumptions about this are false and it will all Just Work™.  But I felt like it was worth bringing up.
