### ISSUE TITLE
Need API endpoint for ignore invitation

### ISSUE THREAD

**Issue by mgamini** [habitat-sh/habitat#3282]
https://github.com/habitat-sh/habitat/blob/25d9ac945430ba58017c75ee4291e3959baa3815/components/builder-web/app/origin/origins-page/origins-page.component.ts#L50

**Comment by raskchanky** [comment]
We also need a way for someone to rescind an invitation after it's been sent out.

**Comment by raskchanky** [comment]
Just clarifying the rules for this API here:

* Ignoring an invitation is done by the recipient and just marks the invitation as `ignored`, which has the effect of preventing the sender from sending another invitation.
* Rescinding an invitation is done by the sender.  If the recipient has already ignored the invitation, then rescinding does nothing.  Otherwise, it deletes the invitation.
