### ISSUE TITLE
Have an official way to install habitat

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#3328]
We need to pick official ways for users to install habitat, and maintain them, and publicize the command to use on our downloads page. 

- `curl | bash `
- `brew install` 

I think we should also add an update command to the habitat cli, i.e. `hab update`, and be able to have the cli check to see if there's a required update (as when we have a regression), and automatically update if there is.

**Comment by predominant** [comment]
I think `curl | bash` is fine as long as the command string suggested contains a hardcoded checksum for the install. Otherwise you're potentially reaching out to the internet (MITM possible) and piping unknown content to bash.

My personal preference is `tarJxf thing.xz` for the binary. This lets people know its a simple binary, allows them to place it wherever on whatever system they have.

**Comment by rsertelon** [comment]
The `hab update` command would be super useful!

**Comment by reset** [comment]
@christophermaier you completed the homebrew tap, yeah? Did it get added to the docs? Can we close this out?

**Comment by christophermaier** [comment]
We've got a [Homebrew tap](https://github.com/habitat-sh/homebrew-habitat) now.
