### ISSUE TITLE
UI should include run commands for exports that Builder is performing

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#3454]
When Builder performs an automatic publishing step, we should add a "run" command to inform users how to run that published package from where it lives. i.e. `docker run <dockerhubid>/<packagename>` which would run the latest package, or run an exact image by adding a `tag`. 

![image](https://user-images.githubusercontent.com/719646/31097541-804cdaf8-a774-11e7-8ca5-bbe97aec7520.png)

cc @ryankeairns

**Comment by rsertelon** [comment]
Linked to #3385

**Comment by cnunciato** [comment]
One thing to keep in mind is that while we know that an integration exists for a given package, we don't (as of today anyway) track whether an image has been published with that integration, so that command stands a good chance of failing. Also, since it's the project settings that contain the external repository details, and that API is (at least currently) restricted to origin members, only origin members would be able to use this feature, unless we were to build some additional APIs for public origins & packages.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #45](https://github.com/habitat-sh/builder/issues/45) via [**ZenHub**](https://www.zenhub.com/)
