### ISSUE TITLE
Hab 0.34.1 needs public key uploaded to public builder on docker export 

### ISSUE THREAD

**Issue by dmajere** [habitat-sh/habitat#3495]
```
hab pkg export docker results/test-webapp-0.2.0-20171004014912-x86_64-linux.hart

[...]

Ω Creating cacerts symlink into /etc
☛ Verifying test/webapp/0.2.0/20171004014912
↓ Downloading test-20171003004300 public origin key
✗✗✗
✗✗✗ [404 Not Found]
✗✗✗
```

**Comment by fnichol** [comment]
Currently, this is correct--you will need your origin's public key uploaded to Builder--this is how the packaging system provides trust so that other consumers of the Docker image can verify the integrity of the packages in the wild.

Having said all of that, there are two changes I've wanted to make that I believe would help your workflow. That's something I'm going to take a look at resolving today and will refer back to this issue. Thank you for reporting!

**Comment by dmajere** [comment]
Yes, but what if user is not going to publish neither his hart package nor his docker image in a public repository? And by user I mean any enterprise that is working on a proprietary project, or simply on an internal component.
Having public key parts uploaded to habitat public depot is not a big deal, but still, what if application build and docker export is done without internet connection to public services?
It is possible, you can download all your app deps, and store them somewhere on a build agent putting to hab cache when you need them.
