### ISSUE TITLE
Proxy error retrieving static files

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#3526]
Seeing the following errors in the logs on acceptance:
Oct 05 02:32:58 ip-10-0-0-136 hab[799]: builder-api-proxy.acceptance(O): 2017/10/05 02:32:58 [error] 879#0: *97612 open() "/hab/svc/builder-api/static/assets/app.css.map" failed (2: No such file or directory), client: 10.0.0.72, server: ip-10-0-0-136, request: "GET /assets/app.css.map HTTP/1.1", host: "bldr.acceptance.habitat.sh"
Oct 05 02:33:01 ip-10-0-0-136 hab[799]: builder-api-proxy.acceptance(O): 2017/10/05 02:33:01 [error] 879#0: *97622 open() "/hab/svc/builder-api/static/assets/app.js.map" failed (2: No such file or directory), client: 10.0.0.72, server: ip-10-0-0-136, request: "GET /assets/app.js.map HTTP/1.1", host: "bldr.acceptance.habitat.sh"

We are getting requests for static assets that are returning errors.

Looking in the assets dir:
app-9279d8703782c6edf1e11b08d6009397847310954df14a1e58115a84e4d8100b.css
app-9279d8703782c6edf1e11b08d6009397847310954df14a1e58115a84e4d8100b.css.map
app-c89e33be61200811b33296c01f4189bc3561d36eb40016bd012e20c2cd8ec37b.js
app-c89e33be61200811b33296c01f4189bc3561d36eb40016bd012e20c2cd8ec37b.js.map
fonts
images

**Comment by fnichol** [comment]
I'm wondering if this is older web client trying to pull down what is now old versions of the CSS and Javascript files? The newer API version would come with a new cache-busting fingerprint meaning it should be safe for us to cache these upstream for a much longer time (theoretically forever?).

Maybe we want to consider setting a longer cache policy for these fingerprinted files? That way `api-proxy` and ultimately Fastly would serve these back after we stop serving them.

Also, I'm wondering why the frontend code isn't getting the hint when they get a new HTML document that the stylesheet and javascript bundles are new. @cnunciato, could this be because the app isn't doing any full-page refreshes, but in-page updates only?

**Comment by chefsalim** [comment]
It looks like this might be an issue where we set source mapping to true for the prod build, but don't actually package in a map file. 

We should either turn off the mapping or add the map.  Reference: https://stackoverflow.com/questions/18499930/missing-map-resource

```
    plugins.push(
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                drop_debugger: false,
                warnings: false
            },
            mangle: false,
            sourceMap: true
        })
    );
```
