### ISSUE TITLE
'HAB_STUDIO_SUP=false' not honoured when included in .studiorc

### ISSUE THREAD

**Issue by therealpadams** [habitat-sh/habitat#3542]
## Meta
- `Darwin ZALANDO-26583 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`
- `hab 0.34.1/20171002011028`

## Problem
I want to start a studio without a supervisor being started automatically. To achieve this I create a .studiorc in /src and it contains 'export HAB_STUDIO_SUP=false'. Upon entering the studio, the supervisor is started anyhow.

## Exploration
- After entering the studio, the env **is** set correctly
- Including the env on the cli (i.e. `env HAB_STUDIO_SUP=false hab studio enter`) works correctly

## Guesswork
- The .studiorc file is not be honoured
- The feature is deprecated and docs have not been updated here: https://www.habitat.sh/docs/reference/#environment-variables

**Comment by therealpadams** [comment]
![tenor-248338671](https://user-images.githubusercontent.com/16607448/31239559-c6cfe7f0-a9fd-11e7-9054-c42605e2ad2e.gif)

**Comment by eeyun** [comment]
Yeah so effectively a user would likely EXPECT that setting `HAB_STUDIO_SUP=false` in the .studiorc would implement an expected behavior of keeping the supervisor from running but the experienced behavior is because we actually read that ENVVAR in before the studio is created in order.

E.g. That envvar gets read in from the outside, rather than from the inside. Perhaps we should change that so this is possible?

**Comment by fnichol** [comment]
So, it looks like I fixed this (by chance/accident) in #3508 which shipped in 0.37.0. With that change, the `.studiorc` is sourced just before checking for the value of `HAB_STUDIO_SUP`. If I turn out to be wrong, we can reopen.
