### ISSUE TITLE
[Interactive Demo] broken instructions for starting services

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#3767]
The first bit of the interactive demo cannot be completed. We ask for the user to start a rails application which has a required bind, but the instructions don't contain the flags required to bind. If you do pass a bind CLI help is prompted. We should rework this just a little bit to take into account the requirement of the database bind

**Comment by davidwrede** [comment]
That's by design. The text after the terminal window states the following:

"You can see in each output that the Supervisor starts up first and then starts up any packaged applications or services. In the case of our Ruby-on-Rails application, the Supervisor recognizes that the application must bind to a database (specified in its plan), before initialization can take place. We will address that problem in the next step."

So I'll push this text (or a modified version of it) above the window to aid in discoverability.
