### ISSUE TITLE
[www] Adjust the home page feature slider

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#3911]
We've received feedback (and personally experienced ;) ) that the home page feature slider rotates too quickly, making it hard to read all the text in each of the 3 panels. 

Let's consider either increasing the time between segues or simply remove the auto rotate leaving just the click-to-advance interaction.

**Comment by ryankeairns** [comment]
cc:/ @apriofrost thoughts on this interaction?

**Comment by apriofrost** [comment]
Hi @mgamini ! Ryan and I had a discussion about this, and we would like to adjust the interaction so that:
when there is a hover or tap action happen on the red square area (see screenshot below), the auto-rotation will pause. 
![image](https://user-images.githubusercontent.com/9401459/32187562-ab2b472e-bd62-11e7-86a5-fd637a5dfc78.png)
What do you think about this approach? If it's too difficult, we can opt for other options. Thanks!

**Comment by mgamini** [comment]
Pausing onMouseEnter should be pretty easy to implement! We could bump up the rotation interval as well.

**Comment by ryankeairns** [comment]
@mgamini sweet, both would be great. I'm not sure what the current delay setting is, but it feels like we could triple it :)
