### ISSUE TITLE
MAX_FILE_UPLOAD_SIZE_BYTES seems too conservative

### ISSUE THREAD

**Issue by gfodor** [habitat-sh/habitat#4066]
When uploading a file via `hab file upload` there is a strict limit of 4096 bytes. For our use case, we have a generic habitat package that provides a web server and we leave the SSL certificate to be part of the config files. So a user can install the package and then upload their SSL cert via `hab file upload`. However, when including the full trust chain, this file easily exceeds 4096 bytes.

Is there a strong reason this limit has been chosen so conservatively? It doesn't seem right for us to create a habitat package with SSL certificates baked in, and we definitely don't want to fork off and have to deploy these files using some other mechanism entirely. Is it possible to bump this limit?

**Comment by gfodor** [comment]
FYI this is defined here: https://github.com/habitat-sh/habitat/blob/46a724604360e2ad6469c6a4578661b42fb77587/components/hab-butterfly/src/main.rs#L51

**Comment by eeyun** [comment]
So I believe the reason why this is set this way is specifically because file uploads actually use the gossip for dissemination. I think the potential for destructive behavior inside a ring probably grows as the size of the file being gossiped' grows. That's rather vague I know. 

@fnichol @christophermaier @reset or @adamhjk might have some deeper details on testing involved or the actual raw data behind why 4096 was chosen. That being said even if we increase the file size for this upload I would assume we'd still have to keep it pretty small.

**Comment by christophermaier** [comment]
Gossip is the reason the size is limited, but I don't know the details on why 4096 is the magic number. Given that it is gossipped, the size _will_ need to be capped at some point, though.

**Comment by gfodor** [comment]
We're still using a custom fork of `hab` to be able to upload these keys and certs. Any hope on bumping it to say 16k?

**Comment by reset** [comment]
It's 4k because it's meant for gossiping single files like a key, cert, etc. When we chose that byte count it was because we didn't believe those types of files would exceed it. It may be too conservative if you've got a cert chain that blew the cap. I'd be willing to bump it to 32k or so.

**Comment by gfodor** [comment]
yep it's due to our cert chain, with the full cert coming in at about 7k. that'd be awesome! thanks :)

**Comment by christophermaier** [comment]
With Habitat 0.56.0, the maximum size is [64K](https://github.com/habitat-sh/habitat/blob/676d024eb0b9baf1dcc7228e0dc2817560329509/components/sup-protocol/src/butterfly.rs#L16)
