### ISSUE TITLE
docker-exporter: Warn on non-standard launcher or supervisor

### ISSUE THREAD

**Issue by zeenix** [habitat-sh/habitat#4162]
docker-exporter should warn the user on non-standard launcher or supervisor package being if specified. Please read here for details:
https://github.com/habitat-sh/habitat/pull/4041/files/319d9fc6cb375f12f4a4a687e7e4151417d6713f#r153881710

**Comment by zeenix** [comment]
Oh and if the warning is launched by the docker exporter binary rather than the crate, we need to ensure k8s exporter does the same.

**Comment by eeyun** [comment]
@zeenix can you provide a bit more context on this issue? The link shared above doesn't appear to be a permalink so I can't quite see what it references and I'm not totally certain what `warn the user on non-standard launcher or supervisor package being if specified` means.

Is the idea that when you attempt to do a `hab pkg export docker` on a machine that has the `HAB_LAUNCHER_PKG` or `HAB_SUP_PKG` envvar set, to bubble up a warning?

**Comment by zeenix** [comment]
@eeyun sorry. I hate that github doesn't keep all versions of the patches. You can follow the discussion here: https://github.com/habitat-sh/habitat/pull/4041#discussion_r153881710 .

**Comment by eeyun** [comment]
@christophermaier it seems this issue was opened as a reference to your [comment](https://github.com/habitat-sh/habitat/pull/4041#discussion_r153881710) so I looked at this last week and actually even wrote up a quick PR for it but in getting some feedback from @fnichol I don't know how necessary it is?

The PR is small, like 9 lines (it doesnt fully regex the value but could with a little more effort), but it feels strange to warn a user after they would have immediately previously opted in to the behavior of a non-standard supervisor/launcher. I'm happy to open the PR if folks feel its definitely necessary but in testing it, it just felt like more pastel colored terminal noise and less like useful information. Any thoughts?

**Comment by christophermaier** [comment]
@eeyun @fnichol One thing I have noticed since that discussion on #4041 is that if you're using a non-core  Launcher, you're not actually going to get your Launcher unless you take additional steps to set `HAB_LAUNCH_BINARY` in your running container, due to how tightly we lock down the install logic (i.e., we always look for "core/hab-launcher" when trying to start a Supervisor / Launcher pair.) I believe similar logic applies to the Supervisor, as well.

If you're just specifying another version or release of `core/hab-sup` or `core/hab-launcher`, you'll be fine, but once you go outside of that, you've got extra hoops to jump through. If you're not expecting that, you'll be scratching your head for a while wondering why things aren't working like you expect.
