### ISSUE TITLE
Users should not be able to enter an email address into integration field for docker hub

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/habitat#4206]
`docker login` requires a docker username, not email address, to login via the cli. Currently the UI will allow you to submit an email address for your username. When we validate those credentials they are correct since we are checking against docker-hub, not `docker login`. We should disallow email addresses or change the verification of credentials to use `docker login`

**Comment by cnunciato** [comment]
It sounds like at most, we want some messaging on the UI to indicate that we mean username, and not e-mail address, and to run the actual `docker` subcommand behind the vailidation API. Is that right? Or should we do more than just message on the UI? 

(We could add validation, but then I'd be concerned about rejecting legitimate usernames containing `@`s and `.`s and the like.)

**Comment by tashimi** [comment]
Definitely let's be more explicit that we want username, not email addresses.

Could we look at the requirements for both a public and on-prem dockerhub username and see if we can validate it in the UI without rejecting "real" ones? That would be more about just catching typos upfront rather than trying to shoot you down for entering an email address.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #81](https://github.com/habitat-sh/builder/issues/81) via [**ZenHub**](https://www.zenhub.com/)
