### ISSUE TITLE
Look into public origin permissions

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#4270]
A couple things came up today when @stevendanna was unable to see the build jobs page for a public package in a public origin: 

- users should be able to see details for public packages in public origins (ssd was unable to see them even when he logged in, as was @smacfarlane. @schisamo was able to see them when he logged in and as a non-member of the core origin). 
- up for discussion: should people be required to sign in to see public content? this feels like an unnecessary hoop. 
- if we think people should have to log in to see certain public information, we need a modal that indicates that information exists but is hidden, to avoid looking broken or devoid of content

page in question: 
- link: https://bldr.habitat.sh/#/pkgs/core/llvm/builds
- view ssd sees: 
![image](https://user-images.githubusercontent.com/719646/33774967-87e19908-dc02-11e7-9b08-2a1301e3be78.png)

- view seth chisamore sees: 
![image](https://user-images.githubusercontent.com/719646/33774999-9ce4fe76-dc02-11e7-9f23-85d07300948e.png)

cc @cnunciato @ryankeairns @apriofrost

**Comment by cnunciato** [comment]
[According to the code](https://github.com/habitat-sh/habitat/blob/master/components/builder-api/src/server/handlers.rs#L824-L826), you need to be both signed in *and* an origin member in order to see the list of build jobs. (@schisamo is not a member of core, but he does have `privilege::BUILD_WORKER`, so he's [able to get by that particular check](https://github.com/habitat-sh/habitat/blob/master/components/builder-http-gateway/src/http/helpers.rs#L261-L263).) So it seems like at the very least, right now, we should hide that tab for non-origin members. I can take that part on.

**Comment by tashimi** [comment]
Cool, I am going to close out this issue. 

Our agreed upon follow up items: 

- all core-plans maintainers should be added as members of the core origin (take action now) 

Future development work: 
- all public information should be available publicly, without requiring a login 
- we should show people a 404 page similar to Github's, that neither confirms nor denies access of private data, if they attempt to look at a page that either does not exist, or that does exist and that they are not authorized to see. 
- we're going to review the current API permissions and make appropriate edits since it was done organically and probably needs some updates as to what returns as private or public
