### ISSUE TITLE
Automatically rebuild .rs files from their .proto dependencies

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#4290]
Rather than relying on developers to remember to run

```bash
cargo build --features protocols
```

in the [`components/builder-protocol`](https://github.com/habitat-sh/habitat/tree/master/components/builder-protocol) directory every time a `.proto` file changes, this should be an automatic part of the build process with `make`.

**Comment by reset** [comment]
It would for sure be a much better experience if these were automatically generated. Just want to provide a bit of context around why they aren't currently this way so we take this into account for the solution: The protobuf generator takes quite a bit of time to run even when nothing has changed because it processes every file instead of looking at something like checksums.

Keeping the speed of `cargo check`/`cargo build` quick is useful for IDE/RLS development which assumes that things are cached well (which Cargo itself does by default). We made the choice to require manual generation instead of doing some checksum caching ourselves out of haste. It'd be awesome if we had this :)

**Comment by baumanj** [comment]
Thanks for the context, @reset. I'm certainly in favor of keeping things as speedy as possible for local dev. I'll need to learn a bit more about how the `cargo --feature` command works, but in our case it seems like we could pretty easily set up a make rule for `.proto` → `.rs` and that should prevent us from ever running the protobuf compiler unnecessarily.

The main downside I see (h/t @chefsalim) is that it would be an additional step for Travis builds since they begin with a pristine environment. That said, running `cargo build --features protocols` on my VM only takes about 25 seconds, so I think it shouldn't be worth it.

**Comment by reset** [comment]
@baumanj yes, we 100% do not ever want the build server to automatically generate protocols. Great catch!

**Comment by baumanj** [comment]
Ok, now I'm a bit confused. You're saying we _don't_ want the Travis build to do the protobuf compilation step? Is there a reason other than the extra time it would take? I would've thought it would be _good_ to have the build server catch it if someone checked in an invalid `.proto` change.
