### ISSUE TITLE
bldr job fails with no useful output.

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#4332]
The core/libdrm build is failing but bldr provides no useful output:

https://bldr.habitat.sh/#/pkgs/core/libdrm/builds/874702749912645632

<img width="963" alt="screen shot 2017-12-18 at 9 25 35 pm" src="https://user-images.githubusercontent.com/852371/34128894-1b7a7c54-e43a-11e7-9a5a-f3ed88b7515c.png">

This plan builds without error in a local hab studio.

**Comment by elliott-davis** [comment]
This happens because we don't pipe child stderr output back up to the parent [here](https://github.com/habitat-sh/habitat/blob/master/components/builder-worker/src/runner/studio.rs#L112-L115). This was done to stop the worker from hanging if there was too much stderr output since the buffer would fill up and hang the runner process. 

To fix: We basically need to make the runner threadsafe for the streaming logging [here](https://github.com/habitat-sh/habitat/blob/master/components/builder-worker/src/runner/log_pipe.rs#L66-L74)
