### ISSUE TITLE
Prevent supervisor from being killed in studio when prompt is in foreground

### ISSUE THREAD

**Issue by themightychris** [habitat-sh/habitat#4397]
Currently, if you press Ctrl+C while the studio prompt is in the foreground, the supervisor gets killed. Ctrl+C works correctly while another process is running, but if you then press it an extra time or two, or use ctrl+c to clear out a command you've started to type as I often do, you end up with a dead supervisor

Prefixing the `hab sup run` command with `setsid` will fix this, but it's not clear to me why that's necessary since only foreground processes are supposed to receive the signal generated by ctrl+c and the supervisor is definitely in the background. SInce the PID is already being tracked and killed when the studio exits, applying `setsid` should isolate the supervisor from the studio shell without requiring any additional changes to clean it up.

I see the same behavior on an Ubuntu desktop running habitat locally, on a remote ubuntu server, and on a Mac laptop running habitat locally under Docker.

![image](https://user-images.githubusercontent.com/458494/34493481-16608700-efba-11e7-84cb-461c9e5d309d.png)

**Comment by stevendanna** [comment]
> it's not clear to me why that's necessary since only foreground processes are supposed to receive the signal generated by ctrl+c and the supervisor is definitely in the background. 

@themightychris Just in case you are interested: The issue here is that when you hit Control^C at your shell it actually sends the signal to the foreground process *group*.  Because of how we start up the hab-sup in /etc/profile, it has the same process group as the shell itself, which is why it gets the signal when you Control^C while the shell is in the foreground.

Check it out:

```
[11][default:/src:0]# sleep 600 &
[2] 230
[12][default:/src:0]# ps -a -o pid,ppid,pgrp,comm
  PID  PPID  PGRP COMMAND
  145     1   145 bash
  149   145   145 hab-launch
  160   149   145 hab-sup
  230   145   230 sleep
  232   145   232 ps
[13][default:/src:0]# ^C
[13][default:/src:130]# ^C
[1]-  Done                    hab sup run "$@" > /hab/sup/default/sup.log 2>&1  (wd: /)
(wd now: /src)
[13][default:/src:130]# jobs
[2]+  Running                 sleep 600 &
```

Note how the sleep doesn't get killed but hab sup does becasue the sleep is in a different process group (230), but hab-sup does because it is in the same proces group (145).
