### ISSUE TITLE
Locally installed packages do not obey update strategy

### ISSUE THREAD

**Issue by wduncanfraser** [habitat-sh/habitat#4504]
Currently, locally installed packages do not obey update strategy. 

Example workflow:
Load a local package with: `hab svc load <path_to_artifact> --strategy at-once`
Install new version of package with `hab pkg install <path_to_artifact>`

Expected behavior: Service should restart with the new version.
Actual behavior: Service never restarts. Has to be bounced manually.

Related to #4476 

I'll follow up with more in depth debug/specific output.

**Comment by christophermaier** [comment]
Based on your description, it seems like you're trying to circumvent the need to talk with the public Builder service in order to manage service updates. We have some work currently under way to provide an on-premises Depot (the artifact repository portion of Builder) that may help with that aspect of your use case.

At this point, I'm unsure that we would modify the Supervisor to update services from locally-updated packages.

Apart from that, though, the real reason that the service doesn't update is that when you load a package directly from an artifact, we end up using the fully-qualified identifier as the "update target" (for lack of a better term). This means that the Supervisor will be checking to see if there is a newer version of `myorigin/myservice/1.2.3/xxxxxxxxxxxx`, but releases never have a newer version, by definition, so there's never anything to update. 

This has been confusing to users in the past, and we will add some documentation, as well as warnings in the CLI when you try to load a service in this way, which should help in the future.

**Comment by tashimi** [comment]
We need to get a lot crisper around local development experience when you: 

- are using public Builder 
- want to just use what you have locally
- are using on-prem Depot

**Comment by wduncanfraser** [comment]
@christophermaier Correct on trying to circumvent the public builder as that story does not fit well with our internal private packages currently, though we are very much looking forward to being able to host a private depot/builder to alleviate these issues.  

Our current pipeline workflow is that packages get built in CI and pushed to artifactory, and then are published to environments via Chef, which by their nature are local installs. This may be partially alleviated by #4607, as the spec file for the service should no longer be tied to a specific version/release if we are able to load service from cached packages rather than directly from the artifact. 

At the very least this should allow us to roll back to earlier behavior of simply bouncing the service rather than having to do a full unload/load.

**Comment by christophermaier** [comment]
@wduncanfraser Sounds good. We had a team meeting yesterday to talk about different usecases with various levels of connectivity to a Builder instance, and have some ideas about how we can be more flexible going forward. Please keep us posted on how your deployment is going!

**Comment by wduncanfraser** [comment]
@christophermaier As a follow up to what I posted in #4607, confirmed that simply bouncing a service does indeed work as expected after locally installing a new version of packages, eliminating the need to do a full unload/load.

**Comment by christophermaier** [comment]
Closing this for now. With the 0.56.0 release, it is no longer possible to load a service directly from a hart archive (because we can now load services remotely, and we don't copy the archive over).

To achieve a similar workflow, you would install the hart locally, then load using a package identifier of the desired specificity.
