### ISSUE TITLE
Mixed Dev Environment Enhancements

### ISSUE THREAD

**Issue by nellshamrell** [habitat-sh/habitat#4531]
Hello!

TY so much to @elliott-davis and @baumanj for the fantastic work on the new dev environments making development more straightforward on the various Habitat parts.

There are a couple of scenarios I see missing from the docs - I know some people have mental workarounds for these, in the interest of recording and consolidating that knowledge (and making it easily findable by new and existing contributors alike) these should be added to the docs.

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] Making a change to the habitat repo which must interact with a change to the [builder repo](https://github.com/habitat-sh/builder) or be tested with the [builder repo](https://github.com/habitat-sh/builder)

- [ ] Making a change to [core](https://github.com/habitat-sh/core) which must interact with either the habitat or builder dev environments.

- [ ] Making a change to [the web UI](https://github.com/habitat-sh/habitat-www) and testing it with a running builder (i.e. the UI around package builds).

- [ ] Building something like an exporter in the habitat repo, and testing it with changes to the habitat command line.

- [ ] Testing changes to the habitat command line that must interact with builder
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

**Comment by baumanj** [comment]
Per @christophermaier:
```
Try something like 
[patch."https://github.com/habitat-sh/core.git"]
habitat_core = {path = "/home/maier/core/components/core"}
habitat_win_users = {path = "/home/maier/core/components/win-users"}
in the top-level Cargo.toml
```

**Comment by baumanj** [comment]
> Making a change to the habitat repo which must interact with a change to the builder repo or be tested with the builder repo

Is at least partially addressed as of https://github.com/habitat-sh/habitat/pull/4641. It's now possible to change [hab-studio-sh](https://github.com/habitat-sh/habitat/blob/master/components/studio/bin/hab-studio.sh) and run the changes with

```
env HAB_STUDIO_BINARY=/path/to/modified/hab-studio.sh hab studio […]
```

**Comment by raskchanky** [comment]
I encountered a scenario today where I needed to make a change to a crate in the habitat repo and I needed that change to interact with my local builder instance.  Concretely, I needed to debug a problem with the `github-api-client` crate, which resides in the habitat repo, and is a dependency of `builder-api`, in the builder repo.  `github-api-client` depends on the `http-client` crate, also in the habitat repo, and I thought I might need to make changes to that too, if only for debugging purposes.

Here's how I did it.

I modified `Cargo.toml` in the root of my builder directory to include the following snippet at the very bottom:

```toml
[patch."https://github.com/habitat-sh/habitat.git"]
github-api-client = {path = "/src/habitat/components/github-api-client"}
habitat_http_client = {path = "/src/habitat/components/http-client"}
```

Note the leading `/src`.  That's important because when you run `hab studio enter`, whatever directory you run it from gets mounted as `/src`.

In order to make the above path a real thing outside of the studio (so that I could e.g. run `cargo check`) I had to symlink it.  In my case, I have all of my repositories checked out into `/root`.  So `/root/builder` and `/root/habitat` are where my builder and habitat repos reside.  To make the above work, I ran:

`ln -s /root /src`

Next, I copied the `.studiorc` file that was inside my builder directory into my root directory that contained both the habitat and builder directories.  I edited it and changed every reference of `/src` to `/src/builder`.

Finally, I ran `hab studio enter` from my root directory (`/root`).

With all of this in place, I was able to edit files in `/root/habitat/components/github-api-client` and when I ran `bb` inside the studio, the changes were picked up and built into builder.

**Comment by chefsalim** [comment]
One more item - for testing web UI changes currently one has to jump through a lot of hoops. Instead, what we should do is link the index.html, app .js and .css files similar to how we link bins for the other packages. This would make the dev cycle for the UI as simple as 'bb api-proxy'.

**Comment by christophermaier** [comment]
You can also have relative paths in your overrides; that may simplify things a bit.

**Comment by mwrock** [comment]
Just to make sure this gets captured. I ran into @raskchanky 's same issue but with a change to core needing to be tested in habitat. I spent at least an hour playing with `cargo.toml`s to point to my local core repo and then getting completely off the wall compile errors unrelated to any change I made. Eventually adding
```
[patch."https://github.com/habitat-sh/core.git"]
habitat_core = {path = "/src/core/components/core"}
habitat_win_users = {path = "/src/core/components/win-users"}
```
to the top level `cargo.toml` ended up being the answer to all of my problems after running `cargo update -p hex:0.3.1` which was a fairly obvious move based on the first set of compile errors I received.
