### ISSUE TITLE
Document use of Kubernetes exporter

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4630]
We should have documentation on the website about why and how you'd want to use the Kubernetes exporter, and what its relationship to the Habitat Operator is.

**Comment by asymmetric** [comment]
Also, it should be mentioned [here](https://www.habitat.sh/docs/best-practices/#kubernetes).

**Comment by christophermaier** [comment]
@asymmetric Yeah, for sure 👍

**Comment by asymmetric** [comment]
See https://github.com/habitat-sh/habitat/pull/4636, which adds kubernetes exporter info to [here](https://www.habitat.sh/docs/best-practices/#kubernetes).

**Comment by zeenix** [comment]
@tashimi You mentioned yesterday about your preferences for blog posts for now (since things change from time to time). So I wonder if I should add to the website here or create a new blog post with updated k8s exporter demo?

**Comment by tashimi** [comment]
Blogs are nice additions, but all exporters must to be documented here: https://www.habitat.sh/docs/developing-packages/#pkg-exports 

And you should add all new or changed `hab cli` commands here, because unfortunately this page is manually created, not automatically generated: https://www.habitat.sh/docs/habitat-cli/

**Comment by zeenix** [comment]
Thanks @tashimi. I'll do that.
