### ISSUE TITLE
Supervisor tracking stable branch of a service doesn't replace packages that are demoted from stable

### ISSUE THREAD

**Issue by thomasrg** [habitat-sh/habitat#4666]
Habitat version: 0.54.0

I am running a service that tracks the stable branch on bldr.habitat.sh. If the latest stable package is demoted to unstable, the service doesn't remove the build and install the previous stable version, leaving an unstable build running.

**Steps to reproduce**
- `hab svc load tomrg/national-parks --channel stable --strategy at-once`
- Build a version of a package and promote to stable (let's call it `tomrg/national-parks/6.3.0/12345`), verify that the package is deployed to the supervisor
- Build another version and promote to stable (let's call it `tomrg/national-parks/6.4.0/12345`), verify that the package is deployed to the supervisor
- `hab pkg demote tomrg/national-parks/6.4.0/12345 stable`

**Expected behaviour**
`tomrg/national-parks/6.4.0/12345` should be replaced on the supervisor by `tomrg/national-parks/6.3.0/12345`, since this is now the latest stable version

**Actual behaviour**
`tomrg/national-parks/6.4.0/12345` is still the version running

**Comment by tashimi** [comment]
Auto-demotion isn't something we've really thought about! The use case makes sense - as a user, I'm subscribed to a channel, I expect to install whatever package is there, even if it's an older version due to a demotion activity. 

However, channel isn't currently involved in the logic of how we do this - we just assume the latest thing that satisfies your identifier on disk is the thing to do. 

We will need to think about how we would approach this.

**Comment by nathenharvey** [comment]
On first consideration, that seems like an awesome idea!

On further reflection, it could be dangerous and/or yield unexpected results.  Though you could make the argument that it's no more dangerous than auto-updating.  The real danger is in having something unexpected happen, I suppose.

Maybe this is further proof that there is no such thing as a roll back.

What would be the expected behavior if the currently running service is using the **only** version of the package in the watched channel?

At the very least, there should be some documentation updates around the update strategies and the package demotion that clarify the current state:  package demotion is not considered as part of the update strategies.

**Comment by baumanj** [comment]
One way around this without requiring much new logic would be implementing the *idea* of a rollback as a forward movement. If the previous stable artifact could be easily cloned and assigned a newer version number, I think this should satisfy the behavior from an user perspective without needing any logic changes in the underlying system.

The main downside I see is that a subsequent rebuild from source wouldn't be the same, so if we went this way, there may need to be some indication that a given version is a clone of an older one, but I think it could simplify remediating some sticky situations.

**Comment by lhasadreams** [comment]
Does this really imply that Habitat needs some sort of "release manifest" at the origin level?
A bit like using policy files for cookbooks. Some way of grouping package dependancies that drive the stable versions that each channel sees. That would imply that your origin is a project though.

**Comment by christophermaier** [comment]
This was addressed with https://github.com/habitat-sh/habitat/pull/7513
