### ISSUE TITLE
Add notification to main website when we're in an outage / incident

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4699]
We use StatusPage to manage our outage / incident / maintenance window tracking and reporting. We've set up integrations with Slack so that our community gets timely notifications of this, but we don't currently have any integrations set up with the website.

It would be very informative for users to be able to immediately see if there's an acknowledged issue that may be affecting their use of the service.

http://blog.statuspage.io/embed-system-status-within-your-webapp

**Comment by eeyun** [comment]
I think it'd be ideal to display this on the builder pages as well since (specifically with this current issue [api rate-limiting] users might not be looking at the main page but will definitely be looking at the builder pages).

Statuspage.io has a plugin for this. For an example implementation you can look here:

https://codepen.io/stevenklein/pen/mznjG

**Comment by mwrock** [comment]
Closing since habitat no longer hosts the main website.
