### ISSUE TITLE
hab-studio on linux should not require root/sudo when using docker

### ISSUE THREAD

**Issue by jeremiahsnapp** [habitat-sh/habitat#4716]
I want to use docker to enter a studio on a linux system to avoid root/sudo requirements but when I run `hab studio enter -D` I still get prompted by sudo for my password. After some [discussion in the forums](https://forums.habitat.sh/t/how-to-avoid-sudo-when-entering-hab-studio-on-linux/429) it was agreed that this is a bug since my user is a member of the `docker` group and already has appropriate permissions to start a docker container without requiring root/sudo. Can we please get `hab studio enter -D` to work on a linux system for a non-root user?

**Comment by eeyun** [comment]
In discussion with jeremiah on this subject I think we could quite easily add a quick catch to the studio enter code path for linux to check whether the `-D` flag was passed and if it was, instead of _only_ checking for root privileges, validate that the user executing the command is a member of the `docker` group. Either of these should guarantee a safe execution of studio in docker.

Doing this unblocks users that are driving habitat package builds via CI where executing with root privileges might not be the most appropriate/possible way to handle a build.

**Comment by fnichol** [comment]
Yep that makes good sense to me. There's a high chance that is just a bug that wasn't intended--and the macOS version doesn't do this either.

**Comment by eeyun** [comment]
Doing analysis on this issue I've found a couple of things worth noting here.

First the source of the bug is right here: 
https://github.com/habitat-sh/habitat/blob/9daf4399b39023690dbb23132cd92cc07c98b38b/components/hab/src/command/studio/enter.rs#L89

Effectively on linux we check whether or not you are root and if you aren't then we re-run the command with sudo. The simplest fix that I've identified is to validate whether or not the the studio call being made is for the docker studio, likely that could be done about right here: https://github.com/habitat-sh/habitat/blob/9daf4399b39023690dbb23132cd92cc07c98b38b/components/hab/src/command/studio/enter.rs#L135

We should validate in that opening if statement whether or not the studio command being run is docker based, if it is, then we simply need a function to compare the list of members in the `docker` group to figure out if the current user is listed.

This is where things start to get complicated - we don't actually consume the user crate directly in the hab component, we have access to a few utility functions that are wrapped in hcore. You can find those here: https://github.com/habitat-sh/core/blob/master/components/core/src/os/users/linux.rs

but you'll notice the group struct is never made available via any of those utilities. So I think probably what needs to happen is a new function needs to get added to that module that can take a groupname and return the struct from that string. Then up in the studio code we have access to what we need to write our comparitive function.
