### ISSUE TITLE
[hab-sup-dev] `hab sup load` no longer works with paths to harts

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#4919]
This is a bug against hab-sup/5.6-dev which we are experimenting with to make sure we understand what changes we'll need to make in the future.

Previously, you could directly call `load` on a hartifact:

```
# hab sup --version
hab-sup 0.55.0/20180321222338
# hab sup load results/ssd-deployment-service-0.1.0-20180413115500-x86_64-linux.hart
hab-sup(MN): The ssd/deployment-service/0.1.0/20180413115500 service was successfully loaded
```

Now, that same operation fails:

```
# hab sup --version
hab-sup 0.56.0-dev/20180412021923
# hab sup load results/ssd-deployment-service-0.1.0-20180413115500-x86_64-linux.hart
hab-sup(AG): » Installing results/ssd-deployment-service-0.1.0-20180413115500-x86_64-linux.hart
» Installing results/ssd-deployment-service-0.1.0-20180413115500-x86_64-linux.hart
hab-sup(AG): ☁ Determining latest version of results/ssd-deployment-service-0.1.0-20180413115500-x86_64-linux.hart in the 'stable' channel
☁ Determining latest version of results/ssd-deployment-service-0.1.0-20180413115500-x86_64-linux.hart in the 'stable' channel
hab-sup(ER)[components/sup/src/error.rs:581:9]: [Err: 0] hab-sup(ER)[components/sup/src/error.rs:479:9]: Package not found
```

I'm not necessarily advocating this be fixed, but it would probably be good to call out in any release notes on the upcoming change.

**Comment by reset** [comment]
@stevendanna sorry for the late reply, this issue slipped my radar and it just got brought to my attention!

The behaviour has been removed and the CLI help has been updated. You are now only able to pass a package identifier to this command. This is because `load` is now a "remote command" - something you can run against a Supervisor that isn't on your local machine. I opted against allowing transferring the artifact over the TCP connection from the client to the Supervisor's command and control gateway because loading an artifact directly is supposed to be more of an escape hatch in the first place. You are still able to pass a path to an artifact to the `hab run` command which will seed the Supervisor with the given service.

We'll make sure this is included in the release notes. If this is something you were depending on please re-open the issue and we can discuss further!
