### ISSUE TITLE
Supervisor filesystem is insufficiently namespaced when running multiple Supervisors

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4975]
It is possible to run multiple Supervisors on a single system by specifying the `--override-name=<NAME>` option, which will create a `/hab/sup/<NAME>` directory in which to write Supervisor-specific files (if no `--override-name` option is given, `<NAME>` will be `default`).

While this provides separation for Supervisor-specific files, other operational aspects are not so isolated. All service-related files are written into `/hab/svc/<SERVICE-NAME>`; thus, running the same service on two colocated Supervisors will result in both services using the same service directory, which means they will be reading (and rewriting) the same templated files. Additionally, `user.toml` files suffer from the same issue, being stored in `/hab/user/<SERVICE-NAME>/config/user.toml`. Multiple instances of the same service end up using the exact same `user.toml` file.

Apart from these examples, the entire `/hab/pkgs` hierarchy is shared by all Supervisors running on a host, which introduces the opportunity for services to unexpectedly upgrade when newer versions of a service package are installed, since we run the latest available package that satisfies the given service identifier. 

Granted, many of these scenarios likely only arise in extreme, unrealistic, or contrived situations (I can't imagine wanting to literally run three instances of a service in a leader topology on the same machine outside of a Supervisor testing scenario, for instance). However, these behaviors are unexpected, given the implication that `--override-name` gives around running multiple Supervisor processes on a single machine.

We should either address these shortcomings by fully namespacing all directories that Supervisors need throughout the course of their operation, or we should consider removing the ability to run multiple Supervisors on a single host.

**Comment by reset** [comment]
@christophermaier running multiple Supervisors is a YMMV practice. We warn the user if they attempt to do it because you really shouldn't be in the first place. I would rather rip the ability to run multiple Supervisors out in time for our 1.0 release than solve any additional edge cases. I only added the functionality because we hadn't proved that the multi-tenant Supervisor was ready.

The location of the `user.toml` is an issue of it's own. We don't want people manually modifying anything in `/hab` directly so both it's original location and it's new location are incorrect locations on the filesystem. We can chat about this in another thread, though ;)

**Comment by christophermaier** [comment]
@reset I lean toward ripping out the ability to run multiple supervisors, too. I think there are too many sharp edges to smooth out, for what appears to be practically zero benefit. 

Just wanted to make sure everyone had all the data 😄

**Comment by baumanj** [comment]
Confirmed valid in v0.57, keeping

**Comment by baumanj** [comment]
Since we've decided to [remove support for multiple supervisors on a single host](https://github.com/habitat-sh/habitat/issues/5266), this issue can be closed.
