### ISSUE TITLE
`hab svc status` output needs clarification

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#5063]
There are some confusing aspects of our `status` output.

First, a service can be down, yet still have a value in the `uptime` column. It's not really "uptime"; it's how long the service has been in the current state (up or down). With the 0.56.0 supervisor, I can start up a supervisor with a previously-stopped service (thus, that service will not start up again until manually told to do so with `hab svc start`). The status output looks like this:

```
package                          type        state  uptime (s)  pid     group
core/redis/3.2.4/20170514150022  standalone  down   11          <none>  redis.default
```

Really, this is saying that the service has been down for the entire 11 seconds that my Supervisor has been running.

Additionally, there is no indication what the desired state of the service is. Is it down because I've told it to stop, or is it down because there's actually something wrong with the service? Adding an additional "desired state" column would be one way to convey this information.

**Comment by jeremymv2** [comment]
@christophermaier I think the `uptime` column header could be replaced with the word `elapsed` since I believe that is closer to the intent, is easy to grok and is part of the actual name of the function call returning the column [value](https://github.com/habitat-sh/habitat/blob/master/components/hab/src/main.rs#L1356)

The additional `desired state` column appears to be a little more tricky since it is stored in the `.spec` files, is something the sup manager currently [owns](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/manager/mod.rs#L477) and we don't have a defined message protocol for querying that info from the supervisor.

I'm curious what your thoughts are these differing approaches and/or any other possibilities here:
 * adding `desired_state` to the `SvcStatus` ctl protocol message since it does make sense client-side [here](https://github.com/habitat-sh/habitat/blob/master/components/hab/src/main.rs#L895)
 * creating a new ctl proto message like, `SvcSpecs`
 * something else?

**Comment by christophermaier** [comment]
@jeremymv2 I agree that `elapsed` would work well here.

For the `desired state` column, we probably would need do something like tweak the `ServiceStatus` protocol type to bundle that information in.

**Comment by baumanj** [comment]
`elapsed (s)` column added by https://github.com/habitat-sh/habitat/pull/5214. Thanks, @jeremymv2 !
