### ISSUE TITLE
0.56.0 CLI exhibits surprising/annoying behavior around service start/load

### ISSUE THREAD

**Issue by bixu** [habitat-sh/habitat#5145]
Filing this issue in the hopes of avoiding writing yet more HCL glue code.

Have seen the following surprising behavior, which seems needlessly opinionated to me:
```
[17][default:/src:0]# hab start core/postgresql
✗✗✗
✗✗✗ [Err: 2] Failed to locate service, core/postgresql
✗✗✗

[18][default:/src:1]# hab install core/postgresql
» Installing core/postgresql
☁ Determining latest version of core/postgresql in the 'stable' channel
↓ Downloading core/postgresql/9.6.8/20180423183113
    8.52 MB / 8.52 MB \ [===============================================================================================================] 100.00 % 2.05 MB/s
☛ Verifying core/postgresql/9.6.8/20180423183113
→ Using core/acl/2.2.52/20170513213108
→ Using core/attr/2.4.47/20170513213059
→ Using core/bash/4.3.42/20170513213519
→ Using core/bzip2/1.0.6/20170513212938
→ Using core/cacerts/2017.09.20/20171014212239
→ Using core/coreutils/8.25/20170513213226
☛ Verifying core/db/5.3.28/20170513213734
→ Using core/gcc-libs/5.2.0/20170513212920
↓ Downloading core/gdal/2.2.1/20171025112525
    10.39 MB / 10.39 MB / [=============================================================================================================] 100.00 % 2.11 MB/s
☛ Verifying core/gdal/2.2.1/20171025112525
☛ Verifying core/gdbm/1.11/20170513213716
↓ Downloading core/geos/3.6.2/20171025112556
    2.07 MB / 2.07 MB | [===============================================================================================================] 100.00 % 3.40 MB/s
☛ Verifying core/geos/3.6.2/20171025112556
→ Using core/glibc/2.22/20170513201042
→ Using core/gmp/6.1.0/20170513202112
→ Using core/less/481/20170513213936
→ Using core/libcap/2.24/20170513213120
☛ Verifying core/libossp-uuid/1.6.2/20170514001348
↓ Downloading core/libxml2/2.9.6/20171025112053
    1.22 MB / 1.22 MB \ [===============================================================================================================] 100.00 % 5.42 MB/s
☛ Verifying core/libxml2/2.9.6/20171025112053
→ Using core/linux-headers/4.3/20170513200956
→ Using core/ncurses/6.0/20170513213009
→ Using core/openssl/1.0.2l/20171014213633
→ Using core/pcre/8.38/20170513213423
☛ Verifying core/perl/5.22.1/20170513213942
↓ Downloading core/proj/4.9.3/20171025112633
    333.49 KB / 333.49 KB / [===========================================================================================================] 100.00 % 1.67 MB/s
☛ Verifying core/proj/4.9.3/20171025112633
→ Using core/readline/6.3.8/20170513213506
→ Using core/zlib/1.2.8/20170513201911
✓ Installed core/db/5.3.28/20170513213734
✓ Installed core/gdal/2.2.1/20171025112525
✓ Installed core/gdbm/1.11/20170513213716
✓ Installed core/geos/3.6.2/20171025112556
✓ Installed core/libossp-uuid/1.6.2/20170514001348
✓ Installed core/libxml2/2.9.6/20171025112053
✓ Installed core/perl/5.22.1/20170513213942
✓ Installed core/proj/4.9.3/20171025112633
✓ Installed core/postgresql/9.6.8/20180423183113
★ Install of core/postgresql/9.6.8/20180423183113 complete with 9 new packages installed.
[19][default:/src:0]# hab start core/postgresql
✗✗✗
✗✗✗ [Err: 2] Failed to locate service, core/postgresql
✗✗✗
```

This is a bummer because it means we have to go back into our HCL orchestration code and add at least one line of glue code to load the service before starting it, when I think most engineers would assume that by saying “please start the service” I'm implying that I want to load the service as well. (Kind of a set theory thing - “being loaded” is a subset of “running”).

**Comment by bixu** [comment]
I get a really frustrated feeling when I see small hurdles like this erected around habitat adoption. We are promising the user that the package is essentially a self-contained pocket universe that requires minimal intervention to run successfully, yet keep adding friction to the path between the bare-bones compute environment and the running service. Maybe this is because the long-term goal of the project is integration with Automate, in which case I can see how CLI slickness isn't a high priority, but from a selfish perspective where maximum adoption is maximally good for freeloaders like me, this doesn't feel nice.

Said in a more positive way, why would we not give the use a entry point as slick as `docker run` (slicker, even). Indeed, my dream is to have a `--platform` flag or similar where we can say ```hab start <service> --platform ubuntu``` and get a sane `systemd` service installed and enabled, managing the Supervisor.

(Before anyone asks, I'm going to file a feature request for that now :)

**Comment by cnunciato** [comment]
Adding the needs-discussion label as well to this, since it does feel like some improvements could be made to the UX around this behavior. @ryankeairns thoughts?

**Comment by bixu** [comment]
@cnunciato, I'd be happy to jump on a voice/video chat to discuss this during the work week - Habitat has become really core for us, so I'm (selfishly) invested in making onboarding for new users very, very smooth :)

**Comment by reset** [comment]
Hey @bixu sorry for the weekend trouble. I saw your message after you had logged off for the day but I did post a [related PR](https://github.com/habitat-sh/habitat/pull/5147) which I think you've already seen.

The work that I'm doing right now is an effort to get us to a stable place to release a 1.0 of the Supervisor. Back when we visited with you in October you might recall there were a number of things we were trying to flesh out to improve the Supervisor to get that out the door. This was one of the changes that I developed based on those conversations. There are a two other improvements which I'm working on that are also a direct result from our onsite, specifically:

* Synchronous CLI commands. When you run `hab svc load` you shouldn't need to poll the Supervisor to see if it actually loaded the service.
* Asynchronously executing services. One long running hook of a process won't block another from executing.

I can definitely see how the error message you were getting back would cause the confusion that it did. I wanted to follow up with you though and provide this context because I need to make sure I didn't completely miss the mark on what you expected from these changes. I know it was a while ago that we came out and visited and some of those conversations may have been forgotten, and it probably doesn't feel like it right now, but I made these changes for you :smile:. Reply here or send me a message on Slack and we can get on a video chat if you wanna chat about the implementation more. Thank you so much for the feedback man!

**Comment by bixu** [comment]
@reset, yeah, I totally get (and support) what you are trying to do here. I’m just being vocal about the CLI because I want to protect the experience for adoption.

I’ll Slack you about jumping on a call to run through thoughts/options.

**Comment by baumanj** [comment]
I'd be interested to be looped into this discussion as well. Poking around just now, I see what @bixu is saying is confusing. A couple thoughts:

* `hab svc load` is a bit surprising because the name doesn't really imply that it will also start the service if it's unloaded. Add to this the fact it *won't* start the service if it's already loaded and the behavior of the command depends upon the existing state of the system. I think commands are generally easier to understand when they're idempotent. Maybe a `--run` flag would be beneficial to achieve that goal.
* `hab svc start` is probably fine as is, especially [with improved messaging](https://github.com/habitat-sh/habitat/pull/5147). It's narrowly scoped and does what it says. Still, depending on what people find most intuitive, maybe this it she command that should be able to load and start a service.

Maybe its helpful to think about use cases:
1. Load a service without starting it
2. Load and start a service which is not loaded
3. Start a service which is already loaded
4. Start a service which may or may not be loaded
5. Install a service without loading or starting it
6. Install a service and load it, but don't start it
7. Install a service, load it and start it

Right now we have:
2: `hab svc load`
3: `hab svc start`
5: `hab pkg install`

I'm not sure which of those cases are most useful to have, but my intuition says `4`, `5` and `7` are the most common things, so making those simple and supported would be a good idea. I don't really think we need separate `load` and `start` commands, assuming there's no value in `1`. If loading without starting isn't necessary, why have `hab svc load` at all? Could `hab svc start` load the service if necessary?

One final thought: it's confusing to me that we use the verb `run` with `hab sup`, but `start` with `hab svc`. There's not a meaningful distinction for me, which means I have to often check to see which is correct. Why not make them use same verb?

**Comment by bixu** [comment]
Thinking some more this morning (when I was less tired) about how service interaction might work in the CLI, I think this is how services interactions might work. I _think_ this is less surprising from a purely new-user perspective than previous UX:

`hab install <pkg_ident>` installs a package

`hab load <pkg_ident> <service args>` adds a service to the Supervisor, but _does not start it_ (will install if needed). Also takes all the same service configuration arguments that `start` later will, which the Supervisor 'remembers', but _does not start the service_

`hab start <pkg_ident> <service args>` starts a service. If the service/package is not installed, installs. If service not loaded, loads it (so that service remain in services list even if stopped).

`hab stop <pkg_ident>` stops a service

`hab restart <pkg_ident>` stops and starts a service without changing service arguments/runtime definition

`hab unload <pkg_ident>` removes service from Supervisor - will not reappear after reboot or restart of Supervisor

**Comment by baumanj** [comment]
Those make sense to me, @bixu. The thoughts that occur to me right now are:

1. What should happen if `hab start <pkg_ident> <service args>` (or `hab load`) is run for a package that has already been `hab load`ed, but with different values for `<service args>`? What about for a package that has already been `hab start`ed?
2. For commands that implicitly execute other commands (`load` → `install`, `start` → `load`), how should we handle parameters for the implied commands? Should `load` be able to specify `--binlink`? I think `--url <BLDR_URL>` may mean different things for `pkg install` and `svc load`. There's a tension between the convenience of brevity and the simplicity of single responsibility.
3. One of our [Habitat CLI UX Principles](https://github.com/habitat-sh/habitat/wiki/Principles-of-UX#make-it-readable) is "Keep commands human readable and memorizable by using a sentence like structure `hab <noun> <verb>`", so I think it would be preferable to use `hab pkg install`, `hab svc start`, etc. over `hab install`, `hab start`. We currently have a number of top-level aliases (e.g., `hab install` → `hab pkg install`), but I think those make things more confusing to users. `hab start` seems equally likely to start the supervisor as a service. `hab install` seems like a command which may install something on a remote machine (or a new version of `hab` itself, locally).

For `2`, I wonder if there's value in the `git` approach to aliases. We can provide all the basic primitives, but if we make it easy and portable for users to define their own aliases that combine commands in the way they need, that might be a good compromise.

Related to `3`, if we add in the nouns, it becomes apparent that there are some subject mismatches. It's `pkg install`, but `svc load`, which may be confusing. Perhaps the answer is that all the `svc` commands should be `pkg` commands instead (there are no conflicting verbs). The Habitat distinction between a package and service is potentially confusing, I think. Even if we did that, there's still that kind of potential conflict if we allow a `hab pkg <verb>` to implicitly execute a `hab sup` command.

**Comment by bixu** [comment]
Let me try to respond to each of your points:

1. Any CLI input should override the existing service state. If an operator is performing a scripted or manual action, we should assume they have a good reason for doing so. For safety we could optionally prompt for approval (with an --force flag for scripting) if running service state will be changed by the CLI input

2. My initial instinct is that a top-level verb should be able to call verbs needed to complete the top-level action, but should not support _flags_ that lower-level verbs take. So for example `hab start --binlink` would be invalid, because the `--binlink` flag is specific to the context of `hab install`

3.  I actually think aliases like `hab install` improve the user story for remember-ability. For example, `hab install` implies working with packages but not services (the package being a subset of the service). I agree that `start` could be though of as a way of initializing the Supervisor, but the practical truth is that most of us are starting the Supervisor in some way other than the CLI - systemd units, Chef code, Terraform provisioner, etc. (this is why I think we need a `--platform <operating system>` flag for `hab start` that would bootstrap the Supervisor for us if it's not already running).

**Comment by bixu** [comment]
re: Git aliases, despite Git's ubiquity, I think it's probably one of the best example of anti patterns for UX, so I'm not sure I'd do it that way. Besides, folks are free to use shell aliases.

**Comment by baumanj** [comment]
1. I agree "Any CLI input should override the existing service state" is a good policy. As long as all those changes can be made to a started (or loaded) service, that makes a lot of sense to me. Adding `--force`, I can see plusses and minuses, but it's a good thing to consider.

2. I was thinking the same thing: that implied commands should operate on on defaults and if you need more control, you can run the implied commands explicitly. One wrinkle there is that some commands have different behavior based on environment variables. We may need to be careful to include details about those in the higher-level command as well (e.g., `HAB_BLDR_URL`). Also, if an explicit and implicit command share the same parameter name with different semantics, I think that has the potential to be *very* confusing, so we should be careful there.

3. I'm not sure I agree with the statement "hab install implies working with packages but not services". Based on the name, it doesn't imply anything other than that it has something to do with habitat and installing things. To me, this is the tricky part of trying to design a UX which will be easy to pick up for someone who's not already familiar. It's hard for us to remove our existing knowledge about the way the system works and see it as someone new would. I *do* see the argument for an all-in-one command like `hab start` which makes for a slick demo and easy first experience, but I think it's worth being especially careful about `hab <verb>` commands, especially when `<verb>` makes sense with potentially multiple different operations.

And as for aliases, I'd be equally happy with using the shell for that. I was just thinking of git's approach in relation to @reset's concern that they wouldn't be portable across platforms.

**Comment by bixu** [comment]
I do see what you mean about git if we are talking only about aliases.

As for the bit about 'package' vs. 'service', I'm thinking about this stuff strictly in the dictionary definition sense. As metaphors, a 'package' is a bounded container for static contents. A 'service' implies action.

**Comment by baumanj** [comment]
I agree with your definition of package vs service. What makes the UX confusing to me is that some packages are services, but not all and there's not an obvious way to tell since they're both .hart files. From a design perspective, I'd say they lack affordances.

Do you think it would make things easier if there was a way to distinguish between them in terms of the identifier or file?

**Comment by bixu** [comment]
Hmm. Interesting idea. For anyone used to working with something like `apt` or `yum` we maybe don't need to differentiate, since the convention seems to be that the name of the thing (if you go google it) tells you whether it's a lib or a binary or a service?

**Comment by bixu** [comment]
If there hasn't been any other pushback from the community about this I would close this issue.

**Comment by raskchanky** [comment]
Sounds good.  Thanks everyone for the thoughts.
