### ISSUE TITLE
Plan Linting:  Syntax within associative arrays

### ISSUE THREAD

**Issue by qubitrenegade** [habitat-sh/habitat#5164]
As it stands, the following does not appear to be valid syntax for creating a `pkg_binds`

```
pkg_binds=(
  [database] = "port"
)
```

When attempting to start a plan with binds defined this way the following error results:

```
Error starting foo/bar #033[36mhab-sup#033[0m(#033[1;37mSS#033[0m)[#033[4;37mcomponents/sup/src/manager/service/spec.rs:389:24#033[0m]: Invalid bind(s), database
```

Additionally, this allows services to start even though the `pkg_binds` is defined.

Note that removing the white space around `=` allows the service to start normally and enforces the pkg_binds:

```
pkg_binds=(
-  [database] = "port"
+  [database]="port"
)
```

I think that errors like this should be caught at build time rather than once I've installed my package and am attempting to start it.

Related to #5112

**Comment by qubitrenegade** [comment]
#5065

**Comment by baumanj** [comment]
Since [`shellcheck`](http://shellcheck.net) can catch this exact error (and many more). We should look at integrating it into the plan build process. Not sure if this fits under https://github.com/habitat-sh/habitat/issues/5065 or whether we should have a separate issue for it, but this is a good example of the kind of trickiness that would improve our UX.

**Comment by qubitrenegade** [comment]
bump?
