### ISSUE TITLE
Supervisor does not restart cleanly after a hard crash

### ISSUE THREAD

**Issue by jonlives** [habitat-sh/habitat#5202]
After experiencing a hard crash of the host machine (SLES 12), the habitat supervisor produces the following error message on startup:

```
Butterfly error: Error reading or writing to DatFile, /hab/sup/default/data/3666c465f0bf46ada1446910988f37a8.rst, failed to fill whole buffer
```

Although that file can be manually removed and the supervisor starts up fully after having done so, @eeyun thinks this is likely a bug and that the supervisor should be able to restart cleanly under these conditions, so I am filing this issue to that end.

**Comment by mwrock** [comment]
I'm betting that the supervisor was writing the file during the hard crash. Then when trying to read this file it encounters an unexpected eof which would result in this error.

It's possible this is fixed in 0.56.0 since there were significant changes to the supervisor internals and specific to how state is saved to disk.

I believe Ford is using 0.55.0.

**Comment by mikemol** [comment]
FYI, the .rst file had a zero-byte size at time of crash.

**Comment by mwrock** [comment]
Oh that's good info

**Comment by mikemol** [comment]
Bleh. I should be more precise. It was zero-byte upon reboot and inspection.
