### ISSUE TITLE
supervisor manager don't use gossip_listen address from config

### ISSUE THREAD

**Issue by JonathanTron** [habitat-sh/habitat#5257]
When starting the supervisor with the `--listen-gossip` option binding it to a specific `ip:port` (eg: `192.168.0.10:9638`) then any `hab apply config` fail.

More detail can be found at https://forums.habitat.sh/t/hab-0-57-0-hab-config-apply-issue/609

From what I found in the [supervisor manager code](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/manager/mod.rs#L873) the adress is not taken from the config but hardcoded to `127.0.0.1`.

The same issue is present at:

- https://github.com/habitat-sh/habitat/blob/master/components/sup/src/manager/mod.rs#L911
- https://github.com/habitat-sh/habitat/blob/master/components/sup/src/manager/mod.rs#L1259

**Comment by gfodor** [comment]
+1 for this, we are hitting this too now on the latest supervisor. a workaround is to install a legacy `hab-butterfly` binary and run that.

**Comment by gfodor** [comment]
It seems likely that barely anyone running hab in production is using --gossip-listen since an upgrade to 0.57 breaks config updates if you are but this ticket hasn't garnered a lot of activity. We are probably going to try to stop using this switch given its low usage by others and it's susceptibility to future regressions due to it not being used in prod by many. (For example, unless I'm missing something, it's definitely not used by the habitat folks themselves otherwise they would not be able to make config updates to their ring for the last month.)

**Comment by JonathanTron** [comment]
@gfodor this flag seems to be used by Chef's folks in their builder's terraform config (see: https://github.com/habitat-sh/builder/blob/master/terraform/instances.tf#L784) but as for much of the "cloud" centric deploy, they just listen on all interfaces and filter access via security groups.

My usage being in a mixed env with bare metal + cloud instances, I really do prefer to be able to bind it to a specific ip:port for the case were I need dual private/public network accesses (ex: load-balancers, vpn, bastion...)

**Comment by gfodor** [comment]
Yep, specifying the interface certainly seems like good practice -- we are on AWS so firewall rules certainly are our first line of defense, but an extra layer to ensure we don't over-expose the ports somehow inadvertently was a nice thing to be able to do even in that environment.

**Comment by gfodor** [comment]
this has been broken for almost a month now, any plans to fix?

**Comment by christophermaier** [comment]
@gfodor It's next on my list; should be in the next release (not the one coming out later today, though)

**Comment by gfodor** [comment]
great, thank you!
