### ISSUE TITLE
Hab launcher panick after building windows Domain

### ISSUE THREAD

**Issue by TheLunaticScripter** [habitat-sh/habitat#5258]
On Windows Server 2016 when I use Habitat, run as a service through the windows-service, using habitat to build a Domain Controller causes a panick. `2018-06-26 13:42:36,672 - thread 'main' panicked at 'Error while looking up account for hab: The trust relationship between this workstation and the primary domain failed. (os error 1789)', c:\cargo\git\checkouts\core-4cdefcf00786d1eb\979c7df\components\win-users\src\account.rs:81:14`. This causes the habitat window-service to hang in a running state and needs to be restarted.

- [ ] The OS (including version) where you are running any of the Habitat commands.
Windows 2016
- [ ] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:

   Need to be gathered. Issue can be replicated by running thelunaticscripter/chef-ad-test as a service. This will build the domain controller and after the reboot is when the error occurs.

- [ ] Current Habitat environment variables where the `hab` command or supervisor is running.  These can be gathered using:

		No special hab environment variables.

**Comment by mwrock** [comment]
Discussed this offline with @TheLunaticScripter and this sounds like a race condition. The error occurs after a reboot when promoting the machine to a domain controller. But then the supervisor starts fine after a restart. This occurs when looking up the `hab` user which the supervisor always does before launching the service. If it finds it, it will run the service under that account. This lookup uses `LookupAccountNameW` which under the circumstances we are calling it will look for a local account and if it cannot find the account it will then use domain controllers trusted by the local system. Since the machine was just promoted to a DC, that would be itself but likely things are not quite fully set up when the supervisor makes its first lookup.

I think this should be treated as a bug and we should handle this internal error as if the account simply does not exist. Also we need to make sure the windows service actually stops if its supervisor crashes.

**Comment by mwrock** [comment]
Even better, if the Supervisor is running under the current user, just don't call `LookupAccountNameW`. Need to check but there might be a fair bit of untangling to make that happen.
