### ISSUE TITLE
Allow Habitat services to be loaded in a "proxy" mode for non-habitat binding.

### ISSUE THREAD

**Issue by predominant** [habitat-sh/habitat#5262]
There have been various discussions about how to proxy habitat applications through to non-habitat applications by utilising the binding interface available to developers.

This was the core of a presentation I gave at ChefConf 2018. Its also the inspiration for a small side project that reads all core plans with exports, and replicates those plans into "proxy plans" of the same name, creating a configuration-only plan with a endless loop in the run hook.

This was also discussed with @adamhjk during the Hack Day after ChefConf 2018.

Using this model:

* A service (db) is deployed off-habitat (postgres)
* A service-proxy (db) is deployed on habitat (postgres-proxy)
* postgres-proxy is configured to the upstream non-habitat postgres
* A service (app) is deployed on habitat, and bound to the postgres-proxy

References to the proxy approach:
* https://github.com/predominant/habitat-bind-service
* https://github.com/predominant/core-plans-proxy
* https://github.com/habitat-sh/core-plans/pull/1539

I propose, as discussed with @adamhjk, that the supervisor be capable of launching a configuration-only copy of a service/package. This would be configurable as a normal service through `hab config apply`.

Other services deployed could bind to this proxy/config-only service, and thus use its configuration to connect to an external service.

This would require at a minimum:

* Standard loop / fake service to keep running under the current supervisor model
* Ability to inject an IP address for `sys.ip` when linking to a proxy service

Terrible diagrams:

Standard service binding:

![image](https://user-images.githubusercontent.com/24568/41953992-b88dbfd2-7a13-11e8-8b97-875eea872c0d.png)

Proxy / Configuration-only service binding

![image](https://user-images.githubusercontent.com/24568/41953999-c4ac5396-7a13-11e8-8466-032232911634.png)

**Comment by adamhjk** [comment]
I dig it. I like that you don't have to keep two pairs, and the data stays in sync.

**Comment by predominant** [comment]
For interface/cli, I'm thinking something like:

```
hab svc load core/postgresql --proxy [.. other options ..]
```

**Comment by predominant** [comment]
After listening to the video for this weeks triage - @fnichol is correct, this is supposed to describe an Ambassador approach.

**Comment by themightychris** [comment]
Love this! Great work @predominant !

How might the manually-provided IP address be stored/provided alongside the other connection details that are within the domain of config?

For example, if I provision a mysql database at a managed provider and get back from them a hostname, port, username, password, and database name. It would complicate things greatly if 4 of those bits could travel through all the channels config can go through, but then the IP had to be applied through some side channel. Especially with how configuration is versioned, the complete set of connection details should be part of that versioned packet of config.

That then leaves the question though of what config key to use for it so that there's no conflict with existing plans? Maybe designate a top-level table for all service-level config that's intended for the supervisor to use? e.g.:

```toml
port = 3306
app_username = "abdc"
app_password = "efgh"

[-hab-sup]
proxy_host = "abcd.efgh.us-east-1.rds.amazonaws.com"
```

The public builder could be scanned to survey if that conflicts with existing plan configs, if it comes up clear maybe make it a policy to reserve `-hab-*` has top-level config tables? or `_hab_*` if that's more consistent with whatever this could be consistent with. I like the dash/underscore prefix to make it more clear that it's special/meta and not something you'll find defined in `default.toml`? That seems to be legal and not requiring quoting per the TOML spec and this [online parser](https://toml-to-json.matiaskorhonen.fi/) I just did a quick test in

**Comment by predominant** [comment]
```
[hab]

[hab.sys]

ip = "1.2.3.4"
```

Mirrors currentl `sys.ip` style.

**Comment by themightychris** [comment]
@predominant unlike the computed `sys.ip` though you'll probably often be plugging a hostname in there

Is there least-surprise violation in `ip = "abcd.efgh.us-east-1.rds.amazonaws.com"`?

**Comment by themightychris** [comment]
That raises another question -- should the supervisor resolve an IP to maintain strict compatibility with what it provided before? This could have undesirable implications where infra is relying on DNS to load balance or provide failover.

I think you'd need to distribute the hostname as-is to consuming services to deliver expected behavior and introduce the need for bound services to accept hostnames where only IPs could be before

**Comment by themightychris** [comment]
And a third question -- does a reliable implementation of this require that the supervisor provide a TCP proxy?

It would perhaps be a more consistent with Supervisor network topology if the way this worked was:

1. the provided host gets resolved and connected to by the supervisor instance in which the proxy service is loaded
2. the supervisor spawns a TCP proxy process of some sort as the running process for the loaded proxy service
3. peer supervisors connect to the proxy process, allowing the same network topology to be used for real or proxied services interchangeably

**Comment by themightychris** [comment]
Last one for today, promise: how could health checks play into this?

In habitat-sh/core-plans#1539 I implemented an adapted form of `core/mysql`'s health check for remote connections which I found very helpful

Existing health check scripts contain a mix of things that will work as-is with proxies and thing that will fail.

Maybe an acceptable approach is to expose a new boolean template var `sys.proxy` which health check scripts could use to vary their behavior. The downside would be that many existing health check plans would fail when used in proxy mode until upgraded to expressly support it

**Comment by themightychris** [comment]
@predominant I understand that your proposal isn't for a TCP proxy, the description and diagrams make that clear. In thinking through how this plays out in the field with supervisors being used in all their intended ways though, there are some fuzzy spots that are worth pondering now at least which way the pressure could push once these new patterns gain momentum. It occured to me there's a risk this could be a problematic feature without TCP proxying

Imagine that I have a container image for my application built my habitat that expects a bind named `mysql`, and a topology that locks down networking but lets me give connect my application to another managed container. I think the proxy story works best if the consuming service can be completely ignorant that it's talking to a proxy instead of a managed service. I'm doubting that can be possible while the proxied service is also ignorant that it can be used as a proxy. If swapping between a proxy service and a real service requires reconfiguring the network topology and consumer, are we really simplifying things by adding this path? That swapping operation shouldn't require me thinking about anything but the service I'm replacing and the proxy config

Also in this context, I'd want a health check that verifies the connection details work and my test client can connect. I might have even had health checks within my database service that check that required schema and permissions are set up. If health checks are a feature of running a service in habitat that I'm going to rely on so that all the logic of testing my database service is fulfilling its contracts can be bound up in my database package, and then dropping in a proxy config can short-circuit all that... now I need to copy all that logic for checking that there's a usable service behind the config back into my application plan and manage it outside the hab lifecycle. Once I do that what's the benefit of also maintaining it via habitat for the real service?

I totally see the appeal of just keeping this super simple and easily implemented, but what makes habitat so powerful for me is the guarantees it provides. I worry that letting this pattern in the wild without sufficiently caging it within the guarantees habitat makes will leave us less able to trust the floor in habitat systems and propagate workarounds that undermine the model

**Comment by predominant** [comment]
Network topology is out of scope for this.
