### ISSUE TITLE
SWIM: Incarnation and member rejoining

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#5581]
The [SWIM paper](http://www.cs.cornell.edu/projects/Quicksilver/public_pdfs/SWIM.pdf) makes many references to the incarnation number, but doesn't precisely define it. According to [the paper the SWIM paper is based upon](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.147.1818&rep=rep1&type=pdf) (section 3):

> At each member, an integer in non-volatile storage, that is incremented every time the member recovers, suffices to serve as the member’s incarnation number

Currently, our implementation does not store the incarnation number on disk, so if a supervisor restarts, it ends up sending many `Alive` messages to refute the `Suspect` messages as the incarnation number increments from 0 back to its previous value. This is almost certainly incorrect for intentional supervisor restart situations.

It's unclear under what circumstances a member should permanently leave the ring. According to the paper, a `Confirm` message cannot be refuted, so once a member has been confirmed faulty, it may never rejoin. We need to be clear about what the desired behavior is for members in the various circumstances which cause `ping` and `ping-req` failures, including restarts for supervisor upgrade, temporary network congestions, protracted net splits and intentional shutdown.

**Comment by christophermaier** [comment]
@adamhjk Yup, confirmed: we always start at 0 and just add 1 to our existing incarnation, regardless of the incarnation number in the incoming rumor. Absent incarnation persistence, a Supervisor is in for a potentially long slog to increment their incarnation step-by-step such that the rest of the network will recognize it.

I'm almost done with the persistence work, which also will allow operators the ability to affect the incarnation if absolutely required (just tweak the contents of an `INCARNATION` file and restart).

As for departures from pure SWIM, there's a desire to more clearly delineate exactly where those departures are, and to clearly document the rationale for those, in order to make it easier to reason through the overall operation of the system. If someone's reading through the SWIM paper and sees that we're doing something different, we should be immediately able to point to our code and documentation that explains that difference.

**Comment by adamhjk** [comment]
Sure. We essentially implement part of Lifeguard (https://www.hashicorp.com/blog/making-gossip-more-robust-with-lifeguard). I'm A+ on being more clear about what we do. SWIM is obviously incomplete for more than the research project they set out to do (which was confirm membership, that's it).

**Comment by raskchanky** [comment]
Full disclosure: although I've read several of the papers that butterfly is based on, my understanding of the code as it exists today is very shallow.

It's my understanding that the supervisor will never remove members from its membership list when those members depart the ring.  This runs contrary to the SWIM paper, where once a member has been confirmed as departed, the remaining alive members will drop that departed member from their membership list.  The departed member, is of course, free to return at some point in the future.

Forum posts like https://forums.habitat.sh/t/census-pollution-when-recycling-ips/817 reinforce my belief that butterfly's membership list should behave like the SWIM paper, and be a bit more fluid, rather than holding on to members forever.  I'm sure there are good reasons behind why membership is implemented the way it is today, but I'm ignorant as to what those reasons are.
