### ISSUE TITLE
Allow exporting a node's FQDN

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#5731]
Adding this issue for one of our community members from slack `@js`.

The bug here https://github.com/habitat-sh/habitat/issues/5079 is causing enough difficulty that a discussion came up around the ability to export a node's FQDN as opposed to just their hostname.

I'm not certain how this would all fit together with DNS or even if it would but perhaps it's worth a deeper discussion.

**Comment by y-me-y** [comment]
As an update to this - this issue was raised for cases where ip address advertisement reports back as the localhost and multiple sub-domains are used in organization but not all of them are in the search domains for the local node.

The idea is that not only can we get node name but the fqdn from the bind node - that way if you have no domains listed or few listed in the search domains for dns it doesn't matter we can still get the correct dns entry for the host. and specifically gets aways from the reliance on ip which could also change in the future and a better reliance on dns.

**Comment by mgamini** [comment]
Closing for now. If bug returns, we will revisit.

**Comment by eeyun** [comment]
A little further note: we discussed this as a team on the triage call today and the consensus was that we should focus hard on resolving the bug that this is a workaround for. Once that issue is resolved if this usecase pops back up, we'll go ahead and re-open!

**Comment by predominant** [comment]
I think this needs to be considered from the service producer and consumer ends of the FQDN resolution.

- Service provider knows its FQDN as a.example.com
- Service consumer reaches it via FQDN b.example.com

The source of the service is not always the best location to determine fqdn.

During the Triage call @fnichol mentioned that the user/operator being able to impose their will over the supervisor to inject a value would be the most useful implementation of this, and I tend to agree. Introducing DNS issues into the service binding story is not a required feature at the moment. However, I can see with NAT / VPC setups, that overriding or providing additional discovery options through the use of a hostname / FQDN could be useful, but this should be secondary to the IP Address being advertised.
