### ISSUE TITLE
Health checks on Windows are much more CPU intensive than Linux

### ISSUE THREAD

**Issue by thomascate** [habitat-sh/habitat#5932]
In environments using large numbers of services on Windows Server 2016 we're seeing abnormally high CPU usage related to health checks. This seems to be related to the overhead of spinning up new PowerShell sessions for each health check. The easiest way to repro this would be to make a composite package with 15+ services that all have basically empty health checks.

**Comment by mwrock** [comment]
YES! This is definitely a thing. This may improve when powershell core 6.2 comes out with improved startup overhead, but I don't think it will be the panacea to change this significantly. I think one issue for users who find themselves in a scenario where this hurts them is that they may be running services that were really never good fits as a service. However they have no choice than to run them as services for various reasons like:
* They want to take part in an update strategy
* They need a hook to complete installation
* They want a health check to tell them that the package fully installed correctly but the health check only really needs to run once ever

We are trying to add functionality to the supervisor to improve these scenarios so that users do not have to run these kind of packages as a service. They can still run a special installation hook, get feedback on whether installation completed succesfully and subscribe to automatic updates but the package does not have to implement a never ending sleep loop to run as a service and launch health checks every 30 seconds that will always report the same result.

**Comment by chefsalim** [comment]
We have a potential mitigation with updated Powershell but mostly this is beyond our control. We are deprecating composite packages so this is likely be to less of an issue moving forward.
