### ISSUE TITLE
Remove eventsrv

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#5962]
## Description
It's essentially prototype code that hasn't been touched or used in a long time. Were we to revive the feature, I'm pretty sure we'd want to look at it fresh, rather than using the existing code. I'm pretty sure the build process is broken (and has been for a while), and isn't part of our release process. 

If we removed it, we could simplify the Supervisor, and we would also make #5949 easier to implement.

## Acceptance Criteria
- [x] All source code to eventsrv is removed form Supervisor
- [x] Add `renamed_and_removed_lints` to clippy's `DENIED_LINTS` in [Makefile](https://github.com/habitat-sh/habitat/blob/master/Makefile).

**Comment by baumanj** [comment]
Yes, please!

**Comment by dmccown** [comment]
There's a command line flag that eventsrv responds to that should be deprecated as well.

**Comment by baumanj** [comment]
Deprecated implies is still works, but generates a warning; I think we should be removing this code entirely. I'd be open to the idea of a (possibly hidden) CLI option that reports that the feature has been removed, but since I really don't think anyone is using it, just deleting it seems like the most appropriate course to me.
