### ISSUE TITLE
Evaluate --strip-unnecessary vs --strip-all for x-pie-executable

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/habitat#6191]
Ref #6189 

In order to preserve behavior for the `do_default_strip` function in [plan-build](https://github.com/habitat-sh/habitat/tree/master/components/plan-build), we are passing `--strip-unnecessary` when stripping `application/x-pie-executable` files. (Details of why can be found in #6189)

The intended behavior was to `--strip-all` for executable files. Since that would be a behavior change that will impact all builds in the habitat ecosystem, we should evaluate that change as part of a base-plans refresh.  This will give us opportunity to gauge the impact(if any) across a wide sampling of software before committing to the change.

**Comment by baumanj** [comment]
A couple thoughts about how we can make [`do_default_strip`](https://github.com/habitat-sh/habitat/blob/master/components/plan-build/bin/hab-plan-build.sh#L2049-L2060) more robust going forward:

1. We should use more targeted wildcards. Currently our case statement looks like:
    ```bash
      case "$(file -bi "$f")" in
        *application/x-executable*) strip --strip-all "$f";;
        *application/x-sharedlib*) strip --strip-unneeded "$f";;
        *application/x-archive*) strip --strip-debug "$f";;
        *) continue;;
      esac
    ```
    but I think it's susceptible to unexpected matches. I'd suggest:
    ```bash
        application/x-executable;*) strip --strip-all "$f";;
        application/x-sharedlib;*) strip --strip-unneeded "$f";;
        application/x-archive;*) strip --strip-debug "$f";;
    ```
1. We can pretty confidently skip any non-`application` MIME types, but I think we should log something if we see an `application` type we're not familiar with. This would've possibly surfaced the issue fixed in https://github.com/habitat-sh/habitat/pull/6189 earlier:
    ```bash
    ```

**Comment by smacfarlane** [comment]
I'm going to close this out as won't implement.  After doing some research and experimentation, I think it's best to continue with the current implementation.  This is also the decision Arch linux has reached: https://git.archlinux.org/pacman.git/commit/?id=03272ad57142a1c7dacf1d9933d52650d3936225
