### ISSUE TITLE
Supervisor refuses to start when PID file exists/is "corrupt" for a service

### ISSUE THREAD

**Issue by qubitrenegade** [habitat-sh/habitat#6270]
```
Mar  5 22:59:29 art-psql-1 hab[1415]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SupError { err: PidFileCorrupt("/hab/svc/postgresql/PID"), logkey: "SV", file: "components/sup/src/manager/service/supervisor.rs", line: 356, column: 26 }', libcore/result.rs:945:5
Mar  5 22:59:29 art-psql-1 hab[1415]: note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
~~In the middle of troubleshooting so more to follow but wanted to make sure I captured this error.~~

Ok, long story short, we were having power maint done (ironically having a UPS put in...), and lost all power.  After `fsck` ing everything the psql nodes just wouldn't start Habitat at boot, 2/3 nodes I was able to `systemctl start habitat` and it came up no problem...  Gremlins, obviously...?  but on the third node I received this error.  The PID file did exist but it was empty.

Anyway, maybe the answer is that habitat should refuse to start if there's a PID? But in this case there wasn't a PID in the file (which is why I think the error is specifically `PidFileCorrupt` vs `PidFileExists` or something).  In the case of psql, it wasn't a big deal, since those servers only run psql, but if there were other services I would think I'd still want the supervisor to start and run those?

**Comment by stevendanna** [comment]
On master this file is definitely written non-atomically:

```
    273     /// Create a PID file for a running service
    274     fn create_pidfile(&self) -> Result<()> {
    275         match self.pid {
    276             Some(pid) => {
    277                 debug!("Creating PID file for child {} -> {}",
    278                        self.pid_file.display(),
    279                        pid);
    280                 let mut f = File::create(&self.pid_file)?;
    281                 write!(f, "{}", pid)?;
    282                 Ok(())
    283             }
    284             None => Ok(()),
    285         }
    286     }
```

**Comment by mikemol** [comment]
We've run into this a number of times as well, at this point. PID files are appearing with 0 bytes, causing the main thread to get stuck in a loop. This results in a number of queries against the on-prem builder an order of magnatude greater than hosts in any other state.

Please use atomic I/O operations, or otherwise handle corrupted PID files more gracefully. (Though I don't think it's feasible to handle corrupted PID files gracefully, since you can't really reason about the state of the system. So ensuring those PID files are handled atomically is easily the safest path forward.)

We even had a number of hosts all get knocked offline simultaneously because of an external event. After they were brought back up, over the subsequent several days, individual hosts in the set would suddenly complain about corrupted PID files and get stuck in a loop. Not on the initial boot, but sometimes only several days later. Examining the systems exhibiting the behavior revealed that some of their services' PID files were only zero bytes.
