### ISSUE TITLE
Hab sup term doesn't stop supervisor on Windows

### ISSUE THREAD

**Issue by jmassardo** [habitat-sh/habitat#6375]
Issue:

Running `hab sup term` on Windows doesn't appear to do anything.

OS Name:      Microsoft Windows Server 2016 Datacenter
OS Version:   10.0.14393 N/A Build 14393
Hab Version:  hab 0.78.0/20190313120028

Replication:
```
PS > $env:RUST_LOG="debug";$env:RUST_BACKTRACE=1;hab sup term
```

Output:
```
[2019-04-04T12:57:16Z DEBUG habitat_common::ui] UI { shell: Shell { input: InputStream { isatty: true }, out: OutputStream { coloring: Auto, isatty: true }, err: OutputStream { coloring: Auto, isatty: true } } }
[2019-04-04T12:57:16Z DEBUG habitat_core::os::process::imp] Calling child process: ("C:\\hab\\pkgs\\core\\hab-sup\\0.78.0\\20190313123218\\bin\\hab-sup.EXE") ["term"]
[2019-04-04T12:57:16Z DEBUG habitat_core::os::process::imp] sending no-op(windows) signal 0 to pid 744
[2019-04-04T12:57:16Z DEBUG hab_sup] start() returned Ok(()); Exiting 0
```

After running `hab sup term`, there are still running hab processes:
```
PS C:\Users\labadmin\hab_plans> Get-Process -ProcessName hab*

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    110       8     1820       7080       0.00   8276   2 hab
     61       6     1804       5896       0.50    744   2 hab-launch
    207      25     8276      17340       0.27   4700   2 hab-sup
```

Desired Behavior:
`hab sup term` should instruct all running services to gracefully shutdown, run any `post-stop` hooks, remove any PID references, then shut down the hab processes.

**Comment by mwrock** [comment]
Yes. The implementation is currently linux only and sends a SIGTERM to the supervisor. Given the nature of windows signaling this strategy won't work on windows. I have thoughts for 2 possible implementations:

1. Use the supervise ctrl_gateway to handle `term` and then kill itself with `OK_NO_RETRY_EXCODE` so the launcher shuts down any running services and does not try to restart the sup.
2. Terminate the running launcher which should cause the supervisor to stop all services and shutdown.

I actually have a branch that implements the first but I think the second strategy is better since it is more in the spirit of puting as little logic in the launcher as possible.

**Comment by mwrock** [comment]
This is effectively implemented and merged but just keeping this open until we merge the e2e tests.
