### ISSUE TITLE
Unable to docker export or enter a docker studio on windows 2019

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#6412]
We may need to add the ability to use alternate base images based on OS. On windows server SKUs, the kernel of the host and container mush match which means we need to use the appropriate version tag according to the host we are on.

**Comment by stuartpreston** [comment]
Could a possible implementation not just relate to the version allow a plan to specify something like ```$pkg_parent_image=mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019``` rather than be baked into the tooling?  Selecting an appropriate base/parent image would allow smaller layer deltas when the supervisor and source payload are added, for example.

**Comment by mwrock** [comment]
I'm thinking likely an argument passed to `hab pkg export docker` since you may not want a 1 to 1 relationship between plan and base image.

**Comment by stuartpreston** [comment]
Yes, I guess it would need to be that way. :( Implementing a CI for image creation at build time would mean you need to be running the same kernel as your target on your build server so that it can be built with the install hooks so putting it in the plan just opens up more opportunity for unexpected results.

**Comment by mwrock** [comment]
closed by #6643
