### ISSUE TITLE
Unable to recover Supervisor network when using self-peering

### ISSUE THREAD

**Issue by dmccown** [habitat-sh/habitat#6447]
- [x] The OS (including version) where you are running any of the Habitat commands.
Linux
- [ ] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:

		No stacktrace available.

- [ ] Current Habitat environment variables where the `hab` command or supervisor is running.  These can be gathered using:

		No Hab environment vars available.

We have a report where users are creating a self-peered Habitat network. Given three Habitat Supervisors:
1. One is bootstrapped referencing itself as `127.0.01` and the other two nodes as peers.
2. The remaining nodes are bootstrapped in the same fashion, each peering to itself with `127.0.0.1` and the IP address for the other nodes.
3. All Supervisors are shutdown
4. When the Supervisor are started again the network does not get re-established. In order to get the network healthy again we must delete the ` /hab/sup/default/data/*.rst ` from one of the nodes. The remaining nodes are started normally (without deleting the rst files) and the network is healthy again.

Is self-peering causing an issue that prevents the members from rejoining the ring? Is there an alternative approach that could reduce the overhead of requiring bastion peers to manage many large Habitat networks?

**Comment by raskchanky** [comment]
I'm unable to replicate this problem.  Here's what I did.

I started 3 EC2 nodes on the same subnet, and verified network connectivity between all 3 of them via `ping`.

I installed hab `0.79.1` on all 3 nodes.

Node A is `172.21.102.137`.
Node B is `172.21.102.193`.
Node C is `172.21.102.173`.

On node A I ran:  `sudo hab sup run --peer=127.0.0.1 --peer=172.21.102.193 --peer=172.21.102.173`
On node B I ran: `sudo hab sup run --peer=127.0.0.1 --peer=172.21.102.137 --peer=172.21.102.173`
On node C I ran: `sudo hab sup run --peer=127.0.0.1 --peer=172.21.102.137 --peer=172.21.102.193`

All 3 supervisors came up.  I waited 5 seconds or so and then on node A ran:
`curl -v http://localhost:9631/butterfly | jq ".member"` which shows me the butterfly network as node A sees it.  This is the result:

```json
{
  "members": {
    "27dd563088404c278a75f8ae99dc90fd": {
      "id": "27dd563088404c278a75f8ae99dc90fd",
      "incarnation": 0,
      "address": "172.21.102.173",
      "swim_port": 9638,
      "gossip_port": 9638,
      "persistent": false,
      "departed": false
    },
    "8ff1d422fc0d429a87177c12fe08ad5a": {
      "id": "8ff1d422fc0d429a87177c12fe08ad5a",
      "incarnation": 1,
      "address": "172.21.102.137",
      "swim_port": 9638,
      "gossip_port": 9638,
      "persistent": false,
      "departed": false
    },
    "560492065d82462e883b28e7200139f5": {
      "id": "560492065d82462e883b28e7200139f5",
      "incarnation": 0,
      "address": "172.21.102.193",
      "swim_port": 9638,
      "gossip_port": 9638,
      "persistent": false,
      "departed": false
    }
  },
  "health": {
    "27dd563088404c278a75f8ae99dc90fd": "Alive",
    "560492065d82462e883b28e7200139f5": "Alive",
    "8ff1d422fc0d429a87177c12fe08ad5a": "Alive"
  },
  "update_counter": 5
}
```

One thing worth noting here is that all 3 nodes are at incarnation 0.

Next, I shut all 3 supervisors down via ctrl+c.  Now nothing is running anywhere.  Finally, without touching any files, I restarted all 3 supervisors.  I ran the same curl command that I ran above, again, still from node A.  Here is the result this time:

```json
{
  "members": {
    "8ff1d422fc0d429a87177c12fe08ad5a": {
      "id": "8ff1d422fc0d429a87177c12fe08ad5a",
      "incarnation": 3,
      "address": "172.21.102.137",
      "swim_port": 9638,
      "gossip_port": 9638,
      "persistent": false,
      "departed": false
    },
    "27dd563088404c278a75f8ae99dc90fd": {
      "id": "27dd563088404c278a75f8ae99dc90fd",
      "incarnation": 1,
      "address": "172.21.102.173",
      "swim_port": 9638,
      "gossip_port": 9638,
      "persistent": false,
      "departed": false
    },
    "560492065d82462e883b28e7200139f5": {
      "id": "560492065d82462e883b28e7200139f5",
      "incarnation": 1,
      "address": "172.21.102.193",
      "swim_port": 9638,
      "gossip_port": 9638,
      "persistent": false,
      "departed": false
    }
  },
  "health": {
    "8ff1d422fc0d429a87177c12fe08ad5a": "Alive",
    "27dd563088404c278a75f8ae99dc90fd": "Alive",
    "560492065d82462e883b28e7200139f5": "Alive"
  },
  "update_counter": 11
}
```

All 3 nodes are alive, and all of them see each other.  I haven't deleted any files.  One thing to note is that now, node A is at incarnation 3 and nodes B and C are at incarnation 1.

I'm wondering if this is an issue with the version of hab that's running on the supervisors in question.  Could the behavior be due to bug in a previous version that's been fixed?

**Comment by dmccown** [comment]
I'm closing this issue due to no response.
