### ISSUE TITLE
Investigate the possibility of making `core/hab-backline` a formal dependency of the Studio

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#6509]
The `core/hab-backline` package is really a "meta-package", containing only dependencies, and is only used in `core/hab-studio`. However, it is not a direct dependency in the traditional Habitat sense (i.e., it's not in the `pkg_deps` or `pkg_build_deps` lists of `core/hab-studio`), but is pulled in dynamically in the actual executing code of the Studio.

If possible, we should try and make `core/hab-backline` a direct runtime dependency of the Studio. It would would eliminate a non-standard "indirect" dependency, making Habitat (and by extension, Builder) aware of the relationship between the Studio and its dependencies. It would simplify our release process (and possibly help to make it possible for more of our release to run out of Builder itself). It would also stand to simplify the code of the Studio, since it would eliminate a bunch of runtime logic that would now be handled by core Habitat logic.

With all that said, it remains to be seen whether it is actually possible to modify the Studio this way. We need to ensure that any changes that are made are compatible with the needs of the bootstrapping Studio, which is used for building the initial foundation of Habitat in a non-Habitat environment. This work may also reveal ways to tease bootstrapping requirements apart from "normal" Studio requirements, which may help clarify and simplify code for both of these usecases.

**Comment by christophermaier** [comment]
Pinging @smacfarlane and @scotthain

**Comment by smacfarlane** [comment]
One advantage backline provides is that it gives you a single package that contains all of studios "internal" dependencies that is then controlled by a single variable: `HAB_STUDIO_BACKLINE_PKG`. 

The backline package is also used by the [rootless studio](https://github.com/habitat-sh/habitat/blob/master/components/rootless_studio/default/Dockerfile#L5) that makes up our Docker image, so we'd need to track any changes in two places. These changes rarely happen (in the past 3 years the only change has been the pinning and then un-pinning of dependencies to pre-core-plans-refresh versions), but because it is rare it would be easy to forget to make both updates. 

That being said, I do think as a first pass making backline a run dependency for the studio is the right thing to do. I suspect that if we had that, the need for `HAB_STUDIO_BACKLINE_PKG` would go away.  Then, if we're able to address #6056, we should be able remove the need for backline completely. 

Random thought: Would we want/need to always build a studio with `--ignore-local` if we're moving items to direct dependencies of the studio?

**Comment by christophermaier** [comment]
@smacfarlane Agreed... if we still need the package, that's fine. I think having it be a proper dependency is the key thing here (I'll adjust the issue title, etc. to reflect that; thanks for clarifying that).

As for `--ignore-local`... maybe? Might be worth revisiting that feature in a more holistic way, too.

**Comment by smacfarlane** [comment]
@cm Updated the `--ignore-local` comment with some context where that idea came from.

**Comment by smacfarlane** [comment]
Closed by #6549
