### ISSUE TITLE
hab pkg install behaviour changes in 0.81.0

### ISSUE THREAD

**Issue by predominant** [habitat-sh/habitat#6582]
Since 0.81.0 the behaviour of `hab pkg install` has changed slightly. the argument for `--binlink` used to be able to be used before the pkg_ident.

Previously:

```
hab pkg install --binlink core/bats
```

Now:

```
hab pkg install core/bats --binlink
```

I don't understand why this change was made, and why this only applies to some(?) options.

For example, the `--force` option can still exist before pkg_ident.

```
hab pkg install --force core/bats --binlink
```

This change affects every core plan that has binlinks. Almost all tests include these.

The change also seems counterintuitive, to require options / flags after the final argument, this somewhat goes against standard conventions of CLIs allowing options before their last argument.

This kind of change would be like requiring AWK to do the following:

```
echo "hello/habitat/friends" | awk '{print $2}' -F'/'
```

I'd like to propose we restore the previous behaviour.

**Comment by wduncanfraser** [comment]
If I remember from a discussion in slack, it was moved to the end as --binlink now has an optional parameter, and due to the current CLI parsing would take the next argument as the optional parameter. May have been a path of least resistance thing.

**Comment by christophermaier** [comment]
Here's some context: https://github.com/habitat-sh/habitat/pull/6423

**Comment by christophermaier** [comment]
After talking it over, we should go through with https://github.com/habitat-sh/core-plans/pull/2591 in the near term, while we dig in a bit more on the UX of this command to ensure that it does what we need, doesn't violate expectations, and is consistent with other binlinking functionality in other commands.

(cc: @smacfarlane )

**Comment by baumanj** [comment]
@predominant: https://github.com/habitat-sh/habitat/pull/6423 was far more disruptive than I anticipated*. I'm very sorry about that. I do still think the reasoning behind the change is sound: the binlinking done by `hab pkg install` and `hab pkg binlink` should be consistent and environment variable overrides should be implemented in a standard way so that they're discoverable and validated immediately. Not doing so is what led to the 0.80 incident, and we'd like to avoid repeating that mistake.

I don't think we want to go back to the previous behavior, but after thinking more about it, perhaps there's a good middle ground. The confusing change is due to making `--binlink`, which was previously a flag (i.e., no associated value) into an option with a default value. It's the default value which is confusing when `--binlink` gets placed in the middle of a command. The mistake here seems to be overloading `--binlink` to both toggle a behavior (should a link be created?) and customize the behavior (where should that link be created?). I think we can decouple these concerns.

For discoverability and consistency with `hab pkg binlink`, we need a way to specify the binlink destination directory with `hab pkg install`, but it doesn't have to be through the `--binlink` argument. If we change `--binlink` back to a flag, and add a `--binlink-dir <PATH>` argument whose argument is required, I think we'll get the best of both worlds. Plus, this should make https://github.com/habitat-sh/core-plans/pull/2591 and other similar fixups unnecessary.

Would that approach address your concerns here?

\* Perhaps naïvely, I didn't foresee the disruption at all.

**Comment by predominant** [comment]
@baumanj I think this addresses the problem.

**Comment by baumanj** [comment]
I tried this out with https://github.com/habitat-sh/habitat/pull/6597, but I'm concerned that it results in a more confusing experience, especially for new users.

**Comment by baumanj** [comment]
After discussing with the team, we're planning to go ahead with the change in https://github.com/habitat-sh/habitat/pull/6597, but eventually deprecate `--binlink` since `--binlink-dir` subsumes its functionality and is clearer on its own.
