### ISSUE TITLE
Env var HAB_BLDR_CHANNEL, HAB_BLDR_URL (and maybe others?) are not respected by supervisor

### ISSUE THREAD

**Issue by russellseymour** [habitat-sh/habitat#6649]
- OS: Linux (Ubuntu 18.04.1)
- VARS:

HAB_BLDR_CHANNEL=dev 
HAB_LICENSE=accept

I have had a setup working with my application deployed into Kubernetes and using Habitat Operator and Habitat Updater. 

Until today, when I updated my application and forced an update, Habitat would respect the `HAB_BLDR_CHANNEL` of dev. However in version `hab 0.82.0/20190605214032` it appears that this does not happen anymore.

If I interrogate the services in the app I get the following:

![image](https://user-images.githubusercontent.com/791658/59351387-39cc5480-8d16-11e9-8a16-19dc03cb7e13.png)

As can be seen the channel is set to stable whereas I would expect it to have been set to `dev`.

Is this a regression issue with this version? Is there another way I can set the channel, e.g. through the services api.

**Comment by russellseymour** [comment]
I have just run some tests on different versions of Habitat to work out which version respected the `HAB_BLDR_CHANNEL` environment variable.

I have not had a chance to go through all the versions but have tested the following:

0.82.0 - Does not work
0.79.1 - Does not work
0.68.0 - Works

I appreciate that there are a number of versions that I have not tested, but it certainly looks like more recent versions are not working.

**Comment by kenlangdon** [comment]
This issue includes the HAB_BLDR_URL environment variable as well.  In similar testing as above by a customer:

0.82.0 - Does not work
0.79.0 - Works

I suspect that other environment variables might have the same problem.

**Comment by ericcalabretta** [comment]
Confirmed 0.82.0 will not respect HAB_BLDR_URL. I've attempted to set in cli.toml, as an environment variable, and in .studiorc. 

When set in .studiorc it does set the HAB_BLDR_URL variable in the studio, it shows set with `printenv`, but it is not used by the studio. All commands will still use the default bldr URL. You must feed the -u option for studio to use the non-default bldr URL.

**Comment by neodingo** [comment]
Is this still in an issue in new versions of the supervisor?  It looks like it was verified/confirmed above and then ignored...

**Comment by mikemol** [comment]
If you run `HAB_BLDR_URL=${my_builder} hab svc load ${my_service}`, then the service will be configured with whatever builder the `hab` CLI tool thinks the builder should be, irrespective of whatever environment variables are exposed to the supervisor itself. If you don't define `HAB_BLDR_URL` in the environment when you call `hab`, then `hab` will use the hardcoded default, and tell the supervisor to do so for that service, too.

That's how you get `bldr.habitat.sh` in the output shown above; the CLI utility that loaded the service was not itself told what builder to consider.

I'd bet that's why it seems to work or not work in different versions; the environment for the CLI tool wasn't consistent when being tested by the user, because it wasn't expected to have an impact.

**Comment by mikemol** [comment]
As for the studio, if you define `HAB_SECRET_HAB_BLDR_URL` with the desired builder, it'll get passed through into the studio environment after the `HAB_SECRET_` prefix is stripped off.
