### ISSUE TITLE
[certs] Expose cert info in the hab cli UI

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#6799]
Related to https://github.com/habitat-sh/habitat/pull/6759

Currently we only expose information about the certs that the hab cli is using via debug statements. This might be good to expose to users as part of the regular UI status.

**Comment by smacfarlane** [comment]
After some initial research, we'll need to add the `habitat-common` crate as a dependency to `http-client` in order to use the UI components.  This adds a circular dependency `http-client -> common -> builder-api-client -> http-client`.

It appears that the `builder-api-client` is a dependency of `habitat-common` in order for `common::command::package::install` to manage package installs.  This file is depended on by `hab-sup`, `hab-pkg-export-tar` and `hab-pkg-export-docker` so any refactoring to remove the circular dependency would likely be a pretty impactful change.

**Comment by dmccown** [comment]
This issue is looking a lot bigger than we thought, so we're going to remove this from this iteration.

**Comment by krasnow** [comment]
We are unlikely do this work. Closing the issue.
