### ISSUE TITLE
Cleanup on-prem-builder on-prem-archive script

### ISSUE THREAD

**Issue by markan** [habitat-sh/habitat#7018]
Now that we have the new package download/upload flow (see #6878 & #6903) we have an opportunity to substantially simplify the flow of the on-prem-archive script. Large portions of the script (https://github.com/habitat-sh/on-prem-builder/blob/master/scripts/on-prem-archive.sh) are either obsoleted or greatly simplified.

## Open Questions:
* do we continue to support the LATEST.tgz flow it's gotten huge (>5GB) to the point of usability problems
* do we have a starting kernel built into the system to replace LATEST.tgz
* are there simple extensions to the download/upload commands to improve the flow for this (perhaps the manifest work described in #6963)

**Comment by jeremymv2** [comment]
Instead of spending cycles on cleaning up the on-prem-archive script we decided to simply update the main README with the new preferred process using `hab pkg download|bulkupload` and to mark the bootstrap and sync sections of the README as deprecated.

The README updates are happening in https://github.com/habitat-sh/on-prem-builder/pull/212
