### ISSUE TITLE
Supervisor configuration is easy to manage

### ISSUE THREAD

**Issue by krasnow** [habitat-sh/habitat#7036]
## Description

**What problem are we solving?**

It's difficult to configure a supervisor today, especially when trying to set up the data collector to Automate. There are a ton of options that must be defined with command line parameters.

**Objective and key results.**

By making configuration easier, we expect to see

- Usage of Automate reporting increases.
- Quicker on-boarding

**Acceptance criteria.**

I can

- Define the supervisor's configuration in a file.
- Override the file by using CLI parameters.
- Continue to use only CLI parameters if I choose

**Dependencies and blockers.**

none

**Evidence.**

Customers who have tried the Automate reporting features in beta have complained about the friction required for setup.

**Out of scope.**

n/a

**Open questions.**

Need UX input on how to structure the file.

How should CLI params and the config file interact with each other?

What's the recommended workflow to

- Create a file?
- Get the file on a node and start the supervisor?
- Update the entire file?
- Change a single parameter?

**Comment by davidMcneil** [comment]
This epic has undergone a significant rework. When #7600 lands #7537 #7240 #7415 will be closed leaving #7536 #7623 #7624 in this epic.

The rework of this epic spawned several new issues several of which should be made into epics:
* Verify CLI configuration  #7621
* Cleanup CLI parsing logic #7504
* Add ability to load multiple services in a single command #7622
* Use `structopt` structs internally instead of `ArgMatches` #7239
* Make configuration dynamically configurable #7243
