### ISSUE TITLE
Use futures instead of event loop for handeling service hook state

### ISSUE THREAD

**Issue by davidMcneil** [habitat-sh/habitat#7112]
I think we should consider having a single `Service` future and removing this [`tick`](https://github.com/habitat-sh/habitat/blob/c6c8a7e736788325f2c31bab4206cc23ec816453/components/sup/src/manager/service.rs#L508) method. The [`execute_hooks`](https://github.com/habitat-sh/habitat/blob/c6c8a7e736788325f2c31bab4206cc23ec816453/components/sup/src/manager/service.rs#L988) method could be greatly simplified by removing the need to track `InitializationState`. It would also allow us to easily make all hooks async (#5329) as well as allowing a saner order to hook execution. For example, `post-run` actually after run instead of running concurrently with `run`.

**Comment by christophermaier** [comment]
Minor note: `post-run` is perhaps poorly named. Since the `run` hook is actually the real service process, actually running after it has completed would basically turn it into a `post-stop` hook. The intention was to run it alongside of `run` to allow you to take care of any kind of startup logic that you actually needed a running service for.

**Comment by davidMcneil** [comment]
Agreed. My statement, "For example, post-run actually after run instead of running concurrently with run." was confussing and is not what I meant.

Would it make sense to make `post-run` effectively be `post-first-successfull-healthcheck`?

**Comment by christophermaier** [comment]
Yeah, that is probably a better way to think about it :smile: :+1:
