### ISSUE TITLE
Existing PATH handled differently by supervisor and `pkg exec`

### ISSUE THREAD

**Issue by robbkidd** [habitat-sh/habitat#7135]
**OS:** The Linuxes

# The Problem

I cannot `hab pkg exec` a command that shells out to a utility provided by the host OS.

"Of course not, Robb," you might say. "A Habitat package can only run commands from within itself or its dependencies."

Except, I _can_ run that command in a supervised process.

* Supervised processes get [a PATH that includes the PATH from the Supervisor's start up environment](https://github.com/habitat-sh/habitat/blob/c20916cdb2694f58fb7aa26be29d347404e5bc1b/components/sup/src/command/shell.rs#L31).
* Commands run with `hab pkg exec` do not.

This has made testing difficult for a package of command line tools that expect to be able to call commands provided by the OS because the patterns for testing commands in a hab package are to `hab pkg exec` them and verify their exit code and output.

## Some Related Issues

I have searched through the issues for discussions about `hab pkg exec` and the symlinks/binstubs generated by `binlink`. These two seem the closest, but are focued on binlinks.

* #6657 - Windows binlinks are PowerShell wrapper scripts for a package's executables that include the Windows system paths. (I [commented on that issue](https://github.com/habitat-sh/habitat/issues/6657#issuecomment-533168366) when I first noticed _this_ issue.)
* #6812 - A design proposal for changing generated binlinks on not-Windows and how that may be ~fraught with peril~ tricky.

Changing the behavior of binlinks appears to be complicated, particularly hard if opt-in/out for the behavior is required.

# Idea №1

🤔💭 { `hab pkg exec --preserve-path pumpkin/pie eat_it_up` }

Add an option (of some name to-be-determined) to `pkg exec` to do what the supervisor does with including the existing `PATH`.

While this would violate the purity of "Habitat provides all your dependencies," the supervisor appears to already do so. This would allow users to have `pkg exec` behavior that is consistent with the supervisor while also making it an opt-in behavior.

# Idea №2

Similar to №1, but modeled after `sudo`'s options (thanks, @jsirex):

```
  -E, --preserve-env            preserve user environment when running command
      --preserve-env=list       preserve specific environment variables
```

✋ **I'd be satisfied with any option that allowed me to include the calling context's `PATH`.** Similarity with `sudo`'s options seems interesting, but I totally acknowledge that would over-reach the goal of `PATH` behavior consistent with the supervisor.

# Idea №3

Update the supervisor to _not_ include the "system" `PATH` in the supervised process' runtime environment. If an application requires commands from outside the directories provided by itself and its dependencies, the plan authors must write scripts to wrap their executables to include other directories. Pseudo-codey example (again, thanks @jsirex):

```
# some where in $pkg_path/bin/wrapper-executable

PKG_PATH="$PATH"

# load host system's profile
unset PATH
source /etc/profile

export PATH=$PKG_PATH:$PATH

what_i_really_want_to_do
```

**Comment by smacfarlane** [comment]
I'm going to throw a wrinkle in your ideas with a №4

# Idea №4
Is this a build time concern or a run time concern?   "**DUH**, run time because we're running the software" you might say.

However, for the software in question where it _requires_ the system path to be present, the consumer of the package would need to know to pass `--pumpkin-pie-or-whatever-we-name-this` to the `hab pkg exec`.  

Perhaps this is a build time concern? Encoding something like `include path from running environment when exec'd` in your plan.sh would allow generation of additional metadata that can be encoded as part of the artifact.  The author of the plan _should_ know best if they have adequately described their dependencies (or if they're unable to). This would, in turn, allow the package itself to describe how it needs to be run and consumers would always get the right behavior.  Over time (since this would be a change in the defaults) the supervisor could also use this metadata to align in behavior with `exec`. 

Of course, this could also be a giant bag of snakes, wrapped in more snakes, covered in snake frosting.

**Comment by robbkidd** [comment]
My initial reaction to **Idea №4** "bake `i-need-the-running-context-path` into the package" is positive. I think that'd get me to where I want to go.

(`pumpkin/pie` was my example package, not a proposed option name. I'm trying to branch out from `foo/bar`.)

**Comment by christophermaier** [comment]
Option 4 also strikes me as a good solution, and more in keeping with the "package authors know how the thing should be run" philosophy of Habitat, as @smacfarlane has detailed.

I can neither confirm nor deny the presence of snakes, frosted or otherwise.

**Comment by mwrock** [comment]
Number 4 sounds reasonable to me as well but I'd like to add 2 details:

* Windows should always include the system paths. Note this is not the full running environment paths but just those paths included in [`windows_system_paths`](https://github.com/habitat-sh/habitat/blob/e9d0f57edf7ec86357b8685a725c8f27f9ea9082/components/core/src/fs.rs#L327).
* Provide a feature flag or just an environment variable/config that tells the supervisor to always append the running environment's PATH. Because this (no. 4) could be a breaking change, it seems important to provide a work around.

**Comment by christophermaier** [comment]
@mwrock Rather than being a feature flag or environment variable (which would apply to the entire Supervisor, and thus to all services running on it), wouldn't we need to have a per-service option (e.g., for `hab svc load`) to provide the appropriate escape hatch?

**Comment by smacfarlane** [comment]
@cm @mwrock If we preserved the existing supervisor behavior for now, with a plan to change the default later, would it make sense to have it as a supervisor-level opt-in? That would give time for packages to start encoding their desired behavior without forcing an immediate breaking change.

**Comment by christophermaier** [comment]
@smacfarlane Yeah, I guess the Supervisor could be smart and look to the package metadata, using the supervisor-level option as a fallback behavior.

**Comment by mwrock** [comment]
I've been wrestling with this for a couple days and while on the one hand I completely recognize that there is a beauty in ensuring that everything a service/package needs to run lies inside of your explicitly declared dependencies and if you need to cross that boundary then you should be aware that you are doing just that. I believe that is the spirit of idea No. 4.

What I have been feeling awkward about is that we are now adding another concept to package development for authors to be cognizant about. This will result in changes to the build system, packaging metadata and the supervisor. Again these changes might be great but they are not responding to any known pain from our users. No one is complaining about us appending the environment's run time PATH to a service's path, and removing that PATH could very well break running services.

Really what this issue is about is aligning `hab pkg exec` and supervisor PATH behavior. After talking to @smacfarlane offline, I think we came to some consensus that we can address this issue in the near term by simply aligning `exec` with the supervisor's current behavior. Then possibly at a later point move that overall behavior to align with the spirit of No. 4.

**Comment by robbkidd** [comment]
So, like, an idea №0: "make `hab pkg exec` do `PATH` like the supervisor does"? With a later possibility to implement the philosophically pure №4.†

† Philosophically Pure №4, a cologne for nerds.

**Comment by robbkidd** [comment]
![I'm excited.](https://user-images.githubusercontent.com/517302/79363801-62187700-7f16-11ea-8d6c-247b39c94fe4.gif)
