### ISSUE TITLE
Rolling updates likely break after a leader is removed from the group

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#7160]
Rolling updates will likely break after a leader is removed. From my observations, removing a `leader` topology leader will have one of the following effects upon a rolling update:

1. Everything is fine. This assumes #7159 is merged
1. If there were only 2 members and you lose quorum after killing the current leader AND a newly added member becomes the leader AND that member has an older version of the service on disk (likely if a docker exported image) THEN the follower will try to "update" itself to the leader's version which may likely be less than its current version. This results in a continuous looping of updating to the lower version, starting as the higher version and then "updating" to the previous version again and again and again and again.
1. If an existing follower becomes the new leader, even though according to the census data it appears to reflect its new leadership role, its internal update `state` continues to reflect `UpdaterState::Rolling(RollingState::Follower(ref mut state))` and thus acts like a follower so everyone is following and no one is leading and therefore no one is updating.

This arose from #7150

**Comment by osellers** [comment]
I'm very pleased to see this issue opened. We have been 'fighting' with rolling strategy since introducing Habitat many months ago but have so far been unable to reliably reproduce or identify any patterns to open an issue. @mwrock's summary is a great one, with points 2 and 3 perfectly summing up our experience. We'll typically experience 2 when we resort to manual deployment after rolling strategy has no impact (presumably due to 3).

We do scale our infrastructure regularly resulting in members being added and departed, although I _feel_ like we've also seen the problem appear in freshly-deployed census groups that sit untouched for some days (though no evidence of that right now).

Fixing rolling strategy is really the only remaining blocker to our having a stable, reliable, low maintenance Habitat production deployment, so I'll be more that happy to answer any questions or perform tests that might help verify behaviour.

For now it would be great to know if there's some way we could interrogate our census to know in advance that "yes, rolling strategy will fail/succeed". But of course that's secondary to getting the root issue resolved.

**Comment by sirajrauff** [comment]
Just want to comment that I encountered this same scenario, and was able to reproduce locally with 5 nodes, Node 1 used just as a peer (_not_ a permanent peer!) and the other four nodes used to load **sample-node-app**. Steps:
1. Load Supervisor on Node 1 with the following unit file:
    ```
    [Unit]
    Description=Habitat Supervisor
    Documentation=https://habitat.sh

    [Service]
    Environment=HAB_LICENSE=accept-no-persist
    ExecStart=/bin/hab sup run \
                           --listen-ctl 0.0.0.0:9632
    Restart=always
    RestartSec=2

    [Install]
    WantedBy=default.target
    ```
2. Load Supervisor on nodes 2-5 with the following unit file:
    ```
    [Unit]
    Description=Habitat Supervisor
    Documentation=https://habitat.sh

    [Service]
    Environment=HAB_LICENSE=accept-no-persist
    ExecStart=/bin/hab sup run \
                           --listen-ctl 0.0.0.0:9632 \
                           --peer <ip-of-node-1>
    Restart=always
    RestartSec=2

    [Install]
    WantedBy=default.target
    ```
3. Load application on Nodes 2-5 with `strategy` equal to `rolling`, starting with node 2. Checking `/butterfly` at the end of this should show that node 2 should be the update leader with a single vote.
4. Stop Supervisor on Node 2, any other node should now be the update leader with _four_ votes.
5. Promote a new version of the application to the **stable** channel. None of the nodes will update even though the election shows as finished with a new update leader, and there are at least three alive nodes so Quorum should be guaranteed.
