### ISSUE TITLE
Incorrect Error Message when Private Habitat Package Loaded without Authorization

### ISSUE THREAD

**Issue by sirajrauff** [habitat-sh/habitat#7202]
Trying to load a private Habitat package without exporting my **HAB_AUTH_TOKEN** I get the following:

```
# hab svc load <pkg-ident>
» Installing <pkg-ident>
↓ Downloading <pkg-ident>
↓ Downloading <pkg-ident>
↓ Downloading <pkg-ident>
↓ Downloading <pkg-ident>
↓ Downloading <pkg-ident>
↓ Downloading <pkg-ident>
✗✗✗
✗✗✗ [Err: 0] We tried 5 times but could not download <pkg-ident>. Last error was: description() is deprecated; use Display
✗✗✗
```
Once I exported the token, the command worked.

This should probably be more descriptive/indicative of the real error.

**Comment by christophermaier** [comment]
This would also be helped by #7671

**Comment by christophermaier** [comment]
Not quite sure where it's happening, but something is calling [std::error::Error#description](https://doc.rust-lang.org/1.34.1/src/std/error.rs.html#45-203) and giving us the default trait implementation's message (since we no longer implement this method). This may be from some error we end up wrapping, and thus inheriting some bad behavior. I can't find any place in our code where we call `description` ourselves.
