### ISSUE TITLE
Research Spike: Rollback

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#7378]
We should examine the ways we might provide rollback support and the implications it will have on the Supervisor.

In particular, the assumption that the "latest package on disk wins" is deeply ingrained in the Supervisor. If we were to allow demotion operations to cascade out to Supervisors, this would no longer be the case. Deletion of the current package _could_ address this (really, deletion of any package more recent than what's currently coming from Builder), but may have unforeseen implications. Ways to limit the scope of such a behavior to only running services would be ideal.

Investigation of how the user indicates that a particular service is able to be safely rolled-back is another important factor. Is this a permanent aspect of the package itself (_probably_ not), or a runtime option that can be invoked at service load time? Should the service _always_ be "rollback-able", or are there situations where users may wish to toggle this feature dynamically?

Other questions may suggest themselves during the course of this research.

The outcome of this issue should be one or more approaches to enabling rollback, along with an enumeration of the anticipated benefits and shortcomings of each approach.

(It is my suspicion that the [service updater](https://github.com/habitat-sh/habitat/blob/73bd50e005b7f798ee7641f10fb0dfe7a01b0e02/components/sup/src/manager/service_updater.rs) will need to be modified to make rollback happen. Refactoring this file to make it much more comprehensible and maintainable is long overdue; any work for rollback should factor this refactoring cost into the ultimate planned approach.)

**Comment by davidMcneil** [comment]
Refactoring from #7420 and #7389 should help lay the groundwork for this feature.

## Dynamic Rollback
One way to achieve dynamic rollback would be to integrate it into the lifecycle hooks. We could attribute special significance to a particular exit code that would indicate to rollback (similar to how we handle the `health-check` hook). The exit code could either come from the `post-run` hook or a new `rollback` hook.

## Alternatives to deleting the package in order to rollback
1. Temporarily modify the ident in the spec file to point at the desired version
2. Somehow mark the package as "yanked" (to use cargo parlance). This would indicate to the supervisor not to use that version unless the desired version matched exactly.

## Conflict with auto-updates
No matter what approach is taken, I think the interaction between rollback and auto-updates is going to lead to very "interesting" (aka painful) edge cases. It is probably worth detailing various scenarios and stating what the desired behavior is. This might be one area in which approach number 2 would shine as auto-updates could just be made to ignore "yanked" packages.

**Comment by christophermaier** [comment]
I now realized I left out some important motivating context from my initial writeup :man_facepalming: 

Users have often struggled with the idea that when they demote a package from a channel, any Supervisors that were running that demoted package don't correspondingly "roll back" to whatever is now at the head of the channel. 

Our advice since forever is to always roll forward, creating a new package in your CI/CD pipeline and letting that roll out. This is the "correct" thing to do, but often customers have very long pipeline processes, and often network bandwidth issues at remote sites that can make this difficult to do in practice. Additionally, the previous working version of the package is often already on disk, which just adds insult to injury. If the service in question is also stateless, that's even worse. These customers are basically just asking for an "escape hatch" they can use when needed.

One potential implementation path I envisioned was having a new load time option for a service that would mark it as "rollback-able" (since this is not something we want to make an across-the-board behavior). In such cases, when the Supervisor queries Builder to see what the latest version is, if that does not end up being the latest available on disk, we could basically delete packages until what's latest matches what Builder is telling us. This would allow a demotion to serve as a rollback signal, in line with most users' assumptions.

**Comment by davidMcneil** [comment]
Thanks, @christophermaier that extra context really helps crystallize my understanding and I think significantly narrows the scope from what I was originally envisioning.

I wonder if we could make the service updater and the rollback logic essentially be one and the same. Instead of thinking about upgrading or downgrading (rolling back) a package. What if we think of the service updater as simply syncing what is running with the latest version in a channel. So any change to that channel (promotion or demotion) will cause the supervisor to sync the running service if an update policy is set.

If we implemented it this way would we even need a load time option? If a user does not want to rollback they simply dont demote the package, right?

**Comment by christophermaier** [comment]
I don't think I'd want to make this a blanket policy just now (i.e., we should keep it a load-time option), because not every service can actually be safely rolled back. The classic example of this is a service that makes database schema changes; if v2 changes the schema, but you roll back to v1, you potentially break yourself if those changes are not backwards compatible.

In such a case, you could find a problem in v2, demote it in Builder so future deployments don't get it, but get v1 instead, and then roll forward, bringing everything up to v3.

For services where it _is_ OK to roll back, keeping things in sync with what's at the head of a given channel can be useful, and would provide the kind of "escape hatch" for those customers that need it. But I think that's better left as an operational decision at this stage.

(I'm sure there's additional feature work that could be done, perhaps at a higher level (Automate?) that could let you see from a bird's-eye view how all of your services are currently running, in order to better understand the implications of demotions.)

**Comment by davidMcneil** [comment]
> But I think that's better left as an operational decision at this stage.

Those are good points. Agreed, we should require a flag be set.

Do we think we would use the same update strategy for rollbacks as we do for up upgrades, `at-once` and `rolling`, or would we basically always to an `at-once` update?

**Comment by christophermaier** [comment]
The way I was thinking, we'd just have a flag like `--allow-rollback`, `--follow-head-of-channel`, or something similar (that last suggestion is probably not the best :sweat_smile:... we'll need to do some thinking on that) which would modify how a particular update strategy operated.

Or were you asking if we were in a rolling update scenario and needed to do a rollback, should that rollback also occur in a rolling manner, or should everything basically do an "at-once" rollback? I would imagine we'd want the former.

**Comment by davidMcneil** [comment]
Yeah, I was asking how the actual rollback would occur. Agreed we should probably allow doing either `rolling` or `at-once` based on how the user configures the arguments.

Maybe this is overthinking it, but it seems like we might want the user to specify two strategies one for rollback and one update. This would allow the user to enable rollback without needing to enable updates as well as any other combination of those options.

**Comment by davidMcneil** [comment]
#7428 opened as the implementation issue

**Comment by apriofrost** [comment]
@christophermaier @krasnow To cm's point about a high level over in Automate providing users the impact of a demotion operation. We've considered a similar use case for the promotion operation before. The minimal useable solution (not the best 😄  ) we've delivered is to allow users to filter the service groups by a package identifier, something like this:
![image](https://user-images.githubusercontent.com/9401459/74078914-237db200-49e5-11ea-9669-fe49cd5a06e0.png)
This filtered view shows which services are running the specific package so that users can consider the impact before performing a promote or demote operation.
I realized this is less than ideal. Since it is technically not an overview of all services, and users still need to toggle through all the groups in the table to get a sense of the overall impact. But it is usable at the minimum. 
We've considered creating another higher-level view for "deployments", maybe we can incorporate the idea for solving this problem there. For example, when filtering by a package identifier, show all the deployments (an app in an environment) that have this package running. In the example above, it will show that it is run by the same app "mobile-app-api" in two environments "qa"  and "production", instead of the current service-group-centric view.

**Comment by ericcalabretta** [comment]
@davidMcneil your statement is exactly what I've heard from my customers & the behavior I think would be most beneficial. Folks want to be able to control what exactly is running, if they use the channel model we give them this dynamic upgrade method but no escape hatch. This forces them to write their own method or create some higher concept on-top of what we provide instead of channels. 

"make the service updater and the rollback logic essentially be one and the same. Instead of thinking about upgrading or downgrading (rolling back) a package. What if we think of the service updater as simply syncing what is running with the latest version in a channel. "

I would expect the roll-back behavior to just execute the run hook and not rely on a special hook. If customers are using Habitat for upgrades they should test those upgrades & if they're using us for roll-back they should test roll-back as well. If anything we could provide testing and proper run hook examples here rather than create a new hook. The run hook already needs a lot of that logic to clean-up after the old version for applications that are compatible with roll-back it'd be very similar. Separately we could streamline the hooks but I'd think that's a different effort, the run-hook today can get pretty complex with all the logic required but that's not roll-back specific. 

@christophermaier @davidMcneil I think rollback should be something configured when you load the service. That's the point where the operator will understand what behavior is safe and what behavior they desire. The "sane default" to me would be to do nothing, which is what we to today and I'd want the operator to opt in with something like `--allow-rollback`. I don't care about the specific flag name, just using the same example as above. 

Just like how we won't auto-upgrade a service by default, we require a user to specifically `opt-in` to `at-once` or `rolling` upgrades, we shouldn't roll-back by default. This should also make this a non-breaking event for any current users. They can choose to opt-in to the roll-back feature if needed, or do nothing and keep the identical behavior.
