### ISSUE TITLE
error with support/linux/install_dev_9_linux.sh

### ISSUE THREAD

**Issue by bm16ton** [habitat-sh/habitat#7454]
support/linux/install_dev_9_linux.sh errors with
support/linux/install.sh: command not found
workaround ;
curl https://sh.rustup.rs | sh
add ~/.cargo to path

Now support/rustfmt_nightlly.sh should work.

**Comment by christophermaier** [comment]
Hrmm... it looks like this was changed in #6589. It works in Vagrant, because our Vagrantfile runs this script via the `shell` provisioner, which uses a default [upload_path](https://www.vagrantup.com/docs/provisioning/shell.html#upload_path) of `/tmp/vagrant-shell`. Because the `components/hab/install.sh` file was copied into `tmp` earlier, that makes all the math work out correctly.

https://github.com/habitat-sh/habitat/blob/f416554c45549f21bddfde661cd9150ee8d7df4d/Vagrantfile#L16-L19

However, all that falls seem to apart if you're running it outside of Vagrant :frowning_face:

Looks like we just need to modify things so things are consistent both in and out of Vagrant.
