### ISSUE TITLE
Add hook that executes after a service is healthy

### ISSUE THREAD

**Issue by davidMcneil** [habitat-sh/habitat#7495]
It is common to want to configure a service or run additional logic after a service is in a known good state.

There are many potential ways to achieve this functionality:
1. Add a `post-healthy` hook that runs after the first successful health check. We could also change the `post-run` hook to have this behavior.
2. Through environment variables pass in if the service has ever been healthy and its last status to the health check hook. This would allow the user to add whatever functionality they desire but overloads the health check hook.
3. Through an environment variable pass in the health check status.

There are probably many other ways to achieve this functionality and there should be a design investigation before an implementation is decided upon.

**Comment by jeremymv2** [comment]
I think another option is to model off of `systemd` and [ExecStartPost](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStartPre=).

I may be mistaken, but I think that the crux of the issue is that `post-run` is misleading now that it is async in that it fires essentially at the same time as the `run` hook, not after the command from the `run` hook has been invoked successfully. 

If we can change this behavior and make it fire in sequence after the run hook, then much of this problem is mitigated by the user implementing a brief pause in the hook before doing the next operations.

**Comment by davidMcneil** [comment]
> not after the command from the run hook has been invoked successfully.

@jeremymv2 how can we determine when the `run` hook is ready? My thought is that the first successful health check is a pretty good indicator.

Agreed `post-run` is a bad name. It is really `concurrent-run`. A true `post-run` would basically be a `pre-stop`.

**Comment by jeremymv2** [comment]
Hmm, yes, systemd has levels of sophistication there because of a controlled/defined execution model:
> ExecStartPost= commands are only run after the commands specified in ExecStart= have been invoked successfully, as determined by Type= (i.e. the process has been started for Type=simple or Type=idle, the last ExecStart= process exited successfully for Type=oneshot, the initial process exited successfully for Type=forking, "READY=1" is sent for Type=notify, or the BusName= has been taken for Type=dbus).

The one use-case I'm aware of where the health check wouldn't work to determine when to run `post-run` was where the post-run's responsibility is to inject security credentials into Elasticsearch via an ES admin cli command. Only afterwards could the service go healthy.  In that case, they had to implement a side-car approach to achieve the desired post configuration.

Alas, I don't have an answer for when we determine the hook can be run (in our current state). I just wanted to vocalize that using the healthy check might not solve a known use case.

**Comment by jsirex** [comment]
I personally vote for borrow experience from systemd - It well known and  battle proofed.
In our case there is always `Type=Simple`, so we're starting service and immediately firing `post-run` and its ok. It will happen so quick, so no ports were opened or something useful have initalized. `post-run` hook must expect this. For example, when creating database in `post-run` I see first try with `connection refused` and then `success` on subsequent retry.

Regarding current case: `post-healthy` is same as do `source health-check` in a `post-run` hook:
``` bash
# post-run

set -e

do_some_mandatory_stuff 

source "{{pkg.svc_path}}/hooks/health-check"
do_only_after_success_health_check

echo "we are set!"
```
I see the following picture regarding hooks (my opinion):

- init: redundant, any initialization/reinitialization can be easily done in `run` hook. Possible replacement: `pre-run` - just for simplifying hooks and split logic
- run: all good
- post-run: run after service `run` with retries until success. Because it is impossible to do it in the `run` after `exec` instruction. All good
- stop: run this hook if present instead of sending `$pkg_shutdown_signal`. Retries until success or `kill -9` on timeout
- post-stop: runs always after service has stopped or unloaded
