### ISSUE TITLE
hab pkg export fails on clean installation

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/habitat#7639]
1. Install hab
2. run `hab pkg export docker --help`

# Expected Result
Help for exporter is displayed

# Actual Result

```
hab pkg export docker --help
∵ Missing package for core/hab-pkg-export-docker/1.6.0
» Installing core/hab-pkg-export-docker/1.6.0
☁ Determining latest version of core/hab-pkg-export-docker/1.6.0 in the 'stable' channel
↓ Downloading core/hab-pkg-export-docker/1.6.0/20200420202330
    3.80 MB / 3.80 MB / [======================================================================================================================================================================] 100.00 % 82.96 MB/s 
☛ Verifying core/hab-pkg-export-docker/1.6.0/20200420202330
→ Using core/docker/19.03.3/20191025053746
» Installing core/hab-pkg-export-docker/1.6.0
☁ Determining latest version of core/hab-pkg-export-docker/1.6.0 in the 'stable' channel
☛ Verifying core/hab-pkg-export-docker/1.6.0/20200420202330
→ Using core/docker/19.03.3/20191025053746
» Installing core/hab-pkg-export-docker/1.6.0
☁ Determining latest version of core/hab-pkg-export-docker/1.6.0 in the 'stable' channel
☛ Verifying core/hab-pkg-export-docker/1.6.0/20200420202330
→ Using core/docker/19.03.3/20191025053746
» Installing core/hab-pkg-export-docker/1.6.0
☁ Determining latest version of core/hab-pkg-export-docker/1.6.0 in the 'stable' channel
☛ Verifying core/hab-pkg-export-docker/1.6.0/20200420202330
→ Using core/docker/19.03.3/20191025053746
» Installing core/hab-pkg-export-docker/1.6.0
☁ Determining latest version of core/hab-pkg-export-docker/1.6.0 in the 'stable' channel
☛ Verifying core/hab-pkg-export-docker/1.6.0/20200420202330
→ Using core/docker/19.03.3/20191025053746
» Installing core/hab-pkg-export-docker/1.6.0
☁ Determining latest version of core/hab-pkg-export-docker/1.6.0 in the 'stable' channel
☛ Verifying core/hab-pkg-export-docker/1.6.0/20200420202330
→ Using core/docker/19.03.3/20191025053746
✗✗✗
✗✗✗ `hab-pkg-export-docker' was not found on the filesystem or in PATH
✗✗✗
```
The same for tar exporter

**Comment by christophermaier** [comment]
This is due to a confluence of factors:

1) `hab` will automatically download the `core/hab-pkg-export-docker` package if the correct version isn't already installed the first time you run `hab pkg export docker my/cool-app`. This is actually where the "help" output lives.
2) To install a package, you have to run under `sudo`. This is doubly confusing, because (once it's installed) you can actually *run* the export command without `sudo`.
3) The retry logic in the package install flow isn't currently smart enough to know that it's failing to install because you don't have permission to write to the `/hab` directory, and not because of a network error, API issue, etc.

Combine all those together, and you get the behavior you see :frown:

While there could be some broader rethinking of how atomized the entire `hab` CLI is, a good first step here would be making the installation logic smarter by giving it a distinction between recoverable errors (like network issues) and non-recoverable errors (like insufficient permissions).

Here's the function that is ultimately doing the retries and mapping the error into the "file not found" message shown: https://github.com/habitat-sh/habitat/blob/c1c08bd63b93a785ac353ffe261aee19bdcaa408/components/hab/src/exec.rs#L59-L95

**Comment by jeremymv2** [comment]
closed by https://github.com/habitat-sh/habitat/pull/7869
