### ISSUE TITLE
Update Tokio, Prost, and Bytes crates

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#7998]
We currently use Tokio's 0.2 line (see https://github.com/habitat-sh/habitat/pull/7982). This in turn of this pulls in changes to the `bytes` crate. However, we also use `bytes` in our protobuf-releated code via `prost`, which has yet to cut a release using the 0.6.0 release of `bytes` (see https://github.com/habitat-sh/habitat/pull/7990#issuecomment-728979351)

All of this conspires in our codebase to apparently require the updates to these crates to go in together (`prost` and `bytes` seem to need to come together, at least, with `tokio` going in later).

Once a post-`0.6.1` version of `prost` exists, we should bump our `prost` and `bytes` dependencies. After that, we can address `tokio`.

**Comment by korrat** [comment]
`prost 0.7.0` is out now (see #8113 and #8114), and it depends on `bytes` 1.0. However, updating `prost` seems not so straight forward, since the `bytes` crate is used to interface with `tokio-util` as well. Upgrading `tokio-util` requires updating `tokio`, which requires updating almost all dependencies. 

Would you accept a PR updating all dependencies at once?

**Comment by mwrock** [comment]
we are currently waiting for actix-web 4 to release. Bumping bytes, tokio, et al runs into problems with the latest version of actix-web in the supervisor.

**Comment by mwrock** [comment]
this has been done and we are on the latest.
