### ISSUE TITLE
Chef Habitat OnPrem Builder API rdeps fails with 404

### ISSUE THREAD

**Issue by krusolu** [habitat-sh/habitat#8148]
When I try to use the following builder api, I get a 404 error:
https://docs.chef.io/habitat/builder_api/#operation/GET_rdeps-origin-name

$ curl -ik https://bldr.chef.mastercard.int/v1/depot/rdeps/mastercard/cacerts
HTTP/1.1 404 Not Found
Server: nginx/1.18.0
Date: Thu, 18 Mar 2021 18:40:55 GMT
Content-Length: 0
Connection: keep-alive

Other api calls work good, for example this call returns data:
curl -ik https://bldr.chef.mastercard.int/v1/depot/pkgs/mastercard/cacerts

I have also tried without the depot as suggested by support via this ticket:
https://getchef.zendesk.com/hc/en-us/requests/27369

$ curl -ik https://bldr.chef.mastercard.int/v1/rdeps/mastercard/cacerts
HTTP/1.1 500 Internal Server Error
Server: nginx/1.18.0
Date: Thu, 18 Mar 2021 22:13:57 GMT
Content-Length: 0
Connection: keep-alive

**Comment by mwrock** [comment]
Just dug into this and discovered that the rdeps api is not available for on prem builder

**Comment by mwrock** [comment]
To clarify this issue, the rdeps API is exposed by the job server (because it uses the graph) which is not deployed onprem. I think we should edit the description of all APIs dealing with the `job` resource in [api.raml](https://github.com/habitat-sh/builder/blob/main/components/builder-api/doc/api.raml#L414) to specify that the API is not available for onprem installations.

**Comment by pozsgaic** [comment]
Addressed here:  https://github.com/habitat-sh/builder/pull/1715
