### ISSUE TITLE
Specify dependency versions

### ISSUE THREAD

**Issue by killercup** [habitat-sh/habitat#848]
Please don't use `*`  for dependency versions. This basically skips all the nice properties of using SemVer for crates (which cargo assumes).

It probably doesn't matter that much to you right now since you have `Cargo.lock` files anyway, but in general it's just… not good. It should be easy to replace all `*` versions in `Cargo.toml` files with the specific version used in the corresponding `Cargo.lock`.

**Comment by reset** [comment]
We have no intentions to release Habitat as a crate to `crates.io` at this time. We've decided to stick with "*" because we try to aggressively update our dependencies and it helps facilitate for that. If we do release Habitat or any of it's components as a consumable crate then we will absolutely update our constraints!
